### ISSUE TITLE
devnet deploy error: unrecognized signer source

### ISSUE THREAD

**Issue by shivam-agarwal-0** [project-serum/anchor#1000]
I created setup project using `anchor init testproject --javascript` in `$HOME/solana project` directory.
After:
1. setting up to devnet using `solana config set --url devnet`
2. changing localnet to devnet in `Anchor.toml`
3. changing program id in `lib.rs` and `Anchor.toml` file same as `solana address -k target/deploy/testproject-keypair.json`
4. `anchor build` --> success
5. `anchor deploy` --> error

anchor deploy error:
```
Deploying workspace: https://api.devnet.solana.com
Upgrade authority: $HOME/.config/solana/id.json
Deploying program "testproject"...
Program path: $HOME/solana project/target/deploy/testproject.so...
error: Invalid value for '--program-id <PROGRAM_ID>': unrecognized signer source
There was a problem deploying: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "" }.
```

I have followed same steps as above but created project in `$HOME/solana_project` directory, `anchor deploy` worked properly.

Observation:
project path containing space could have caused the whole issue.

Analysis:
In the `solana program deploy....` command [here](https://github.com/project-serum/anchor/blob/ac3fbe8d386daedd8ed90dc2be452b2e9db54619/cli/src/lib.rs#L1842-L1855) 
for 2nd project command will be `solana program deploy ... --program-id ... $HOME/solana_project/...`
for 1st project command will be `solana program deploy ... --program-id ... $HOME/solana project/...`
a space in the whole command is causing the issue similar to how a copy/move command errors out in linux

**Comment by vit0rr** [comment]
Yeap, i had the same problem.

I started my studies very recently and am following [this text](https://dev.to/dabit3/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291) 

I ran `solana address -k target/deploy/mysolanaapp-keypair.json`, put the key in the code as requested in the article and ran `anchor test" and "anchor deploy`, got the same error.

**Comment by vit0rr** [comment]
My solution about this problem is run `anchor deploy` with `--program-name` parameter.

`anchor deploy --program-name <your ID>`

To get this ID, i use [this](https://docs.solana.com/cli/deploy-a-program) doc.

@shivam-agarwal-0

**Comment by shivam-agarwal-0** [comment]
thanks @vit0rr for the workaround solution.

I hope someone will fix the issue to make it work without passing this extra argument.

**Comment by titocosta** [comment]
> 

`--program-name <program id>` solved it for me on `anchor deploy` but I still get the same error when using `anchor test` which doesn't seem to accept a `--program-name` option.

**Comment by buck06191** [comment]
Just to bump this as I have the same problem as @titocosta. I'm following the instructions from Buildspace as found[here](https://github.com/buildspace/buildspace-projects/blob/main/Solana_And_Web3/en/Section_2/Resources/m1_setup.md#-create-a-local-keypair) and running on an M1 Macbook Air.

Using `anchor deploy --program-name <PROGRAM ID>` lets it deploy but `anchor test --skip-local-validator` causes the error
```
Deploying workspace: http://localhost:8899
Upgrade authority: /Users/joshbuckland/.config/solana/id.json
Deploying program "myepicproject"...
Program path: /Users/<my_local_username>/development/blockchain/solana/myepicproject/target/deploy/myepicproject.so...
error: Invalid value for '--program-id <PROGRAM_ID>': unrecognized signer source
There was a problem deploying: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "" }.
```

I have the Solana validator running locally as per the linked documentation

**Comment by jlubeck** [comment]
@armaniferrante  Is there a reason why this ticket is closed? Running into the same issue and my path does not contain any spaces, so I don't believe that was the problem... @buck06191 snippets shows also the same error and no spaces on his path either

**Comment by armaniferrante** [comment]
Have you tried the master build? As stated above, this was closed in #1046, which is not yet released.

**Comment by jlubeck** [comment]
> Have you tried the master build? As stated above, this was closed in #1046, which is not yet released.

Thank you for the quick reply. I installed anchor with this: 
`cargo install --git https://github.com/project-serum/anchor anchor-cli --locked` and when I run `ancho --version` i get `anchor-cli 0.18.2`

If you can point me in the right direction to install a master build, I'll me more than happy to test it

Thanks!

**Comment by BowTiedUrsus** [comment]
I ran the same install and I'm having the issue on linux as well still.

**Comment by tomlinton** [comment]
The correct command to update to current master is `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`. Without the `--force` it won't do anything because the version hasn't been bumped.

**Comment by BowTiedUrsus** [comment]
Still happens after force installing.

**Comment by jlubeck** [comment]
> The correct command to update to current master is `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`. Without the `--force` it won't do anything because the version hasn't been bumped.

I tried this and the error is till happening for me...

**Comment by kfartusov** [comment]
The same for me, last build, with fix  https://github.com/project-serum/anchor/pull/1046. Still the same behavior

**Comment by jlubeck** [comment]
@armaniferrante looks like #1046 is not fixing this, would you mind re-opening it please? Thanks!

**Comment by tomlinton** [comment]
@jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?

If the issue continues, could you please confirm there are no spaces in the path to your project directory.

**Comment by vpontis** [comment]
> @jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?
> 
> If the issue continues, could you please confirm there are no spaces in the path to your project directory.

@tomlinton worked for me! I was able to just do `anchor test` and it worked :) :)

**Comment by kfartusov** [comment]
@vpontis it worked for me too. Thank you. There wasn't spaces in my path, but was "_", probably it also triggered the problem

**Comment by MarkBennett** [comment]
I believe I'm experiencing this issue as well. Is there an `anchor doctor` or `anchor env` command you'd like me to run to collect information about my version and set up?

**Comment by MarkBennett** [comment]
> @jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?
> 
> If the issue continues, could you please confirm there are no spaces in the path to your project directory.

@tomlinton I was advised on the _buildspace Discord to try this command, which fixed the issue for me:

```
cargo install --git https://github.com/project-serum/anchor --tag v0.18.0 anchor-cli --locked
```

I'm trying your now. Thanks for the work on Anchor!

**Comment by MarkBennett** [comment]
@tomlinton I can confirm that this also worked for me and I'm able to deploy with Anchor:

```
cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force
```

**Comment by jlubeck** [comment]
> @jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?
> 
> If the issue continues, could you please confirm there are no spaces in the path to your project directory.

Works now! Thanks!

**Comment by BowTiedBrothers** [comment]
> @jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?
> 
> If the issue continues, could you please confirm there are no spaces in the path to your project directory.

Was having the very same problem and this fixed it, thank you!

**Comment by AliMora83** [comment]
Hey there, what should I type after that install in complete? 'Coz `anchor test` gave error.

> > @jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?
> > If the issue continues, could you please confirm there are no spaces in the path to your project directory.
> 
> Was having the very same problem and this fixed it, thank you!

**Comment by glaksmono** [comment]
So I'm getting a success:

```
 $ anchor deploy --program-name 7xurYiJYztaosgqyCdtKer5MDmgJJHn2gPdtUthUXs6n
Deploying workspace: https://api.devnet.solana.com
Upgrade authority: /Users/glaksmono/.config/solana/id.json
Deploy success
```

But for some reason I can't see it here : https://explorer.solana.com/address/7xurYiJYztaosgqyCdtKer5MDmgJJHn2gPdtUthUXs6n?cluster=devnet

Ideas?

**Comment by glaksmono** [comment]
> @jlubeck @kfartusov @BowTiedUrsus would you mind trying again with an updated version installed via `cargo install --git https://github.com/project-serum/anchor anchor-cli --locked --force`?
> 
> If the issue continues, could you please confirm there are no spaces in the path to your project directory.

This still doesn't work, is that because there are spaces in my project directory?

```
Deploying program "myepicproject"...
Program path: /Users/glaksmono/Dropbox/My Mac (Gradys-MBP.lan)/Documents/Sandbox/myepicproject/target/deploy/myepicproject.so...
```

**Comment by amalnathsathyan** [comment]
> So I'm getting a success:
> 
> ```
>  $ anchor deploy --program-name 7xurYiJYztaosgqyCdtKer5MDmgJJHn2gPdtUthUXs6n
> Deploying workspace: https://api.devnet.solana.com
> Upgrade authority: /Users/glaksmono/.config/solana/id.json
> Deploy success
> ```
> 
> But for some reason I can't see it here : https://explorer.solana.com/address/7xurYiJYztaosgqyCdtKer5MDmgJJHn2gPdtUthUXs6n?cluster=devnet
> 
> Ideas?

Same issue here ! can't find it either in the explorer or find what's happening by this command.

**Comment by Anish-Mukherjee** [comment]
> So I'm getting a success:
> 
> ```
>  $ anchor deploy --program-name 7xurYiJYztaosgqyCdtKer5MDmgJJHn2gPdtUthUXs6n
> Deploying workspace: https://api.devnet.solana.com
> Upgrade authority: /Users/glaksmono/.config/solana/id.json
> Deploy success
> ```
> 
> But for some reason I can't see it here : https://explorer.solana.com/address/7xurYiJYztaosgqyCdtKer5MDmgJJHn2gPdtUthUXs6n?cluster=devnet
> 
> Ideas?

Facing the same issue here.  Here's my devnet url:
https://explorer.solana.com/address/CYEVGYNRRnQwgvELRP9ig2kPqX6RjFHApfWv1vymnzrW?cluster=devnet

**Comment by jintli** [comment]
Same err but I fixed after I changed the Chinese chars in program path to english.

**Comment by LELUK911** [comment]
i think have of resolve this problem using 
`solana program deploy ./target/deploy/NameProgramm.so --url devnet `
this command deploy and return new id that i have change in "anchor.tolm" and "lib.rs" and i run
`anchor build`
and contract is on chain and solana-explorer

**Comment by hongquan** [comment]
Figure out that it failed because one of parent folder has whitespace in name.
