### ISSUE TITLE
Allow passing named account vectors in a context

### ISSUE THREAD

**Issue by mgild** [project-serum/anchor#1001]
Example:
```
#[derive(Accounts)]
pub struct PaymentAction<'info> {
    #[account(mut)]
    pub wallets: Vec<Account<'info, TokenAccount>>,
}
```

**Comment by mgild** [comment]
Also, this presents a pretty easy way to make named accounts optional (ie when the vector is empty)

**Comment by CherryMan** [comment]
Related to #617.

**Comment by mgild** [comment]
> Related to #617.

This issue is unrelated

**Comment by fanatid** [comment]
Duplicate of https://github.com/project-serum/anchor/issues/69
