### ISSUE TITLE
Remove console logging from node package

### ISSUE THREAD

**Issue by theycallmeswift** [project-serum/anchor#1016]
I started writing tests around expected failures _(e.g. when an unauthorized account attempts to perform an action)_ and noticed that the `@project-serum/anchor` library is logging errors to the console automatically ([example here](https://github.com/project-serum/anchor/blob/0a660d26c4ae65a772d2ef76623f6c468adf1d58/ts/src/program/namespace/rpc.ts#L27)). 

Logging errors should be the responsibility of the end user, not the underlying library. If the error is uncaught, it will implicitly bubble up to the point of being logged. If the error is caught, logging it could create confusion around whether or not an error exists.

If we really want to retain logging, adding a debug flag or creating a way to override the logger feel like good solutions.

**Comment by fanatid** [comment]
Yes, we need to remove console logging or add some flags which enable it.
