### ISSUE TITLE
Bump up rust to 2021 edition

### ISSUE THREAD

**Issue by zkwarlock** [project-serum/anchor#1026]
Any reasons for sticking to 2018?

**Comment by fanatid** [comment]
With `2018` -> `2021` change we will need to add field `rust-version` to `Cargo.toml`.
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

**Comment by armaniferrante** [comment]
Looks like the build is broken until this is addressed.

**Comment by paul-schaaf** [comment]
we're now using rust 2021 so im closing this
