### ISSUE TITLE
Valid syntax for `init_if_needed`

### ISSUE THREAD

**Issue by sadsnake42** [project-serum/anchor#1027]
I expected the syntax to be identical to `init`, however, if you upgrade the [current example](https://github.com/project-serum/anchor/blob/49679a4f75c32b985f23ddadc7c1291835a70249/tests/misc/programs/misc/src/context.rs#L248-L254) to:
```rust
#[derive(Accounts)]
#[instruction(bump: u8)]
pub struct TestInitIfNeeded<'info> {
    #[account(
        init_if_needed,
        seeds = [b"SEED"],
        bump = bump,
        payer = payer
    )]
    pub data: Account<'info, DataU16>,
    pub payer: Signer<'info>,
    pub system_program: Program<'info, System>,
}
```
You'll get:
```bash
To deploy this program:
  $ solana program deploy .../anchor/tests/misc/target/deploy/misc.so
The program address will default to this keypair (override with --program-id):
  .../anchor/tests/misc/target/deploy/misc-keypair.json
thread 'main' panicked at 'Code not parseable: Error("expected `=`")', lang/syn/src/idl/file.rs:338:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Looks like an error while creating IDL after .so build

**Comment by armaniferrante** [comment]
Looks like a version mismatch. What version of the CLI are you on?

**Comment by sadsnake42** [comment]
@armaniferrante 
Yes version upgrade helped, thanks!

There was a problem with the clap dependency while updating to the latest version of anchor, which I did not notice while `cargo install-update`. I will later check the relevance of this issue for users and highlight the issue if necessary.
