### ISSUE TITLE
lang: Log instruction names by default

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1038]

**Comment by armaniferrante** [comment]
It's also been suggested to turn this on by default, instead of requiring a feature flag. Curious on thoughts from others.

**Comment by fanatid** [comment]
I think the feature flag is better because logs require instructions which can be critical for some programs.

**Comment by paul-schaaf** [comment]
making it a default feature sounds good to me. devs that want to optimise can turn off default features.

**Comment by paul-schaaf** [comment]
the PR makes this a new feature called `log-ix-name`. It's a feature of the program crate _not_ the anchor crate. the same way `no-idl` works. 

I'm not sure whether it's a good idea to have `log-ix-name` and `no-idl` be program features and not anchor features but I've made it a program feature for now to keep it consistent with `no-idl`'s usage
