### ISSUE TITLE
cli: Add Support for `-c` Flags for Test Validator

### ISSUE THREAD

**Issue by callensm** [project-serum/anchor#1040]
The `solana-test-validator` supports a series of `-url <net> [-c <pubkey> ...]` flags that will clone the account at the address from the current block of the argued cluster network and write it to the genesis block of the test validator.

It would be nice if `anchor test` supported this as well so that they can be propagated down to the execution of the test validator behind the scenes. This would lighten the burden of mocking things such as token mints, serum markets, and other heavily used cross-program accounts when writing integration tests for Anchor programs.

**Comment by tomlinton** [comment]
This was done in https://github.com/project-serum/anchor/pull/834 🙂

**Comment by callensm** [comment]
> This was done in #834 🙂

oh wow....definitely missed that 😅 . I'll close!
