### ISSUE TITLE
error ->  mocha -t 1000000 tests/: No such file or directory (os error 2) in ancho test

### ISSUE THREAD

**Issue by PanupongDeve** [project-serum/anchor#1044]
I find some issues in command "ancho test"

![image](https://user-images.githubusercontent.com/20473767/142720455-e7bcfd26-1dcb-4d3a-8eba-b18225adedcd.png)

I think mocha don't usd by local node_modules

I try to frix

1.  add code in package.json.
    "scripts": {
        "test": "mocha -t 1000000 tests/"
    }
![image](https://user-images.githubusercontent.com/20473767/142720509-21e25f7d-a8cd-4f9d-9a04-efb2d06c75d0.png)
2. change command test script in Anchor.toml.
test = "npm run test"
![image](https://user-images.githubusercontent.com/20473767/142720558-72990d71-ee28-4c9a-ad18-8827bc69af3a.png)

now command "anchor test" is work.

![image](https://user-images.githubusercontent.com/20473767/142720594-06b9734d-9a61-4bfa-857f-b6eb65564cf0.png)

**Comment by fanatid** [comment]
Which `anchor` version do you use? I tried `0.18.2` right now and everything works. https://github.com/project-serum/anchor/pull/990 updates code for local modules usage.
