### ISSUE TITLE
Faster CI

### ISSUE THREAD

**Issue by kevinheavey** [project-serum/anchor#1047]
We could make the CI faster using something similar to Synthetify's approach https://github.com/Synthetify/synthetify-protocol/blob/master/.github/workflows/test.yml

Their CI runs in a few minutes because it's more parallel (GH actions offers up to 20 parallel jobs on the free plan) and because they do a bunch of caching.

**Comment by fanatid** [comment]
@armaniferrante are you ok with CI migration to GitHub actions?

**Comment by armaniferrante** [comment]
> @armaniferrante are you ok with CI migration to GitHub actions?

Fine with me! Do we need to pay for anything? I've never used it before, admittedly.
