### ISSUE TITLE
Calling rpc function with an argument type of u64 results in an error

### ISSUE THREAD

**Issue by zhvng** [project-serum/anchor#1048]
My project contains this function

    pub fn upvote_gif(ctx: Context<UpvoteGif>, gif_id: u64) -> ProgramResult {
        Ok(())
    }

And in my test script I call

    await program.rpc.upvoteGif(0, {
      accounts: {
        baseAccount: baseAccount.publicKey,
        user: provider.wallet.publicKey,
      },
    });

When I run `anchor test`, I get 
  
    TypeError: src.toArrayLike is not a function

**Comment by fanatid** [comment]
You need to use `bn.js`:
```js
await program.rpc.upvoteGif(new BN(0), {
  accounts: {
    baseAccount: baseAccount.publicKey,
    user: provider.wallet.publicKey,
  },
});
```

**Comment by zhvng** [comment]
oh lol thanks
