### ISSUE TITLE
Seed constraint can only be used on own program account PDAs

### ISSUE THREAD

**Issue by Konrad97** [project-serum/anchor#1055]
The current implementation of the seed constraint only allows for PDA validation of program accounts owned by the current program. It would be helpful if there was a way to validate accounts from different programs.

Current: 
`#[account(seeds = [<seeds>], bump = <target>)]`
Always calls find_program_address on the own `program_id`.

Desired:
`#[account(seeds = [<seeds>], bump = <target>, program? = <target>)]`
The `program` parameter defaults to `program_id` but can be set to derive PDAs from other programs.

**Comment by Konrad97** [comment]
Will open PR

**Comment by paul-schaaf** [comment]
closed in favour of https://github.com/project-serum/anchor/issues/1131
