### ISSUE TITLE
Missing metadata and address with anchor build generated IDL

### ISSUE THREAD

**Issue by bilalmotiwala** [project-serum/anchor#1059]
Hi guys,

This is regarding a recent error that I have spent the better part of a day on. There's something seemingly wrong with `anchor build`.

Whenever `anchor build` is run, it produces a set of output which is something like the following:

> This is from the **buildspace** project that I am building at the moment for Solana and Web3 so I'm not much fussed on the sensitivity of anything if I end up publishing it here and I shouldn't have in reality.

```
{
  "version": "0.0.0",
  "name": "myepicproject",
  "instructions": [
    {
      "name": "startStuffOff",
      "accounts": [
        {
          "name": "baseAccount",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "user",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "systemProgram",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": []
    },
    {
      "name": "addGif",
      "accounts": [
        {
          "name": "baseAccount",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "user",
          "isMut": true,
          "isSigner": true
        }
      ],
      "args": [
        {
          "name": "gifLink",
          "type": "string"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "BaseAccount",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "totalGifs",
            "type": "u64"
          },
          {
            "name": "gifList",
            "type": {
              "vec": {
                "defined": "ItemStruct"
              }
            }
          }
        ]
      }
    }
  ],
  "types": [
    {
      "name": "ItemStruct",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "gifLink",
            "type": "string"
          },
          {
            "name": "userAddress",
            "type": "publicKey"
          }
        ]
      }
    }
  ]
}
```

When I take this into Replit or Vercel, it doesn't work and throws an error regarding metadata.address being undefined which is fair because metadata.address doesn't exist in the above IDL. However manually editing the above to add the following after the closing square brackets of type seems to resolve the problem.

```
  "metadata": {
    "address": "AaUs68swNHNGiDRW4H3TwLWeV38k6AmPwWfUyjWnsde1"
  }
```

I would make a pull request on the above if I realised how anchor build worked yet I don't so opening this issue with the solution to the problem faced in hopes someone else can take it from here.

**_### Fix suggested by DISCORD: coal#6876_**

**Comment by tomlinton** [comment]
The `metadata.address` gets populated when you run `anchor deploy`.

**Comment by bilalmotiwala** [comment]
@tomlinton I have struggled with this for over 7 hours today and it didn’t.

**Comment by bilalmotiwala** [comment]
@tomlinton Actually my apologies. I think this is a mistake on my end. I couldn't get `anchor deploy` running in the first place which meant I did a direct `solana program deploy <PATH>` which would be the case on why I didn't have it.

This is actually not an issue then I suppose and closing it. Thanks for the support and apologies for the direct bluntness of my response.
