### ISSUE TITLE
install v0.18.2 failed on aarch64 linux

### ISSUE THREAD

**Issue by gotope** [project-serum/anchor#1067]
$  cargo install --git https://github.com/project-serum/anchor --tag v0.18.2 anchor-cli --locked
    Updating git repository `https://github.com/project-serum/anchor`
error: the given reference name 'refs/remotes/origin/tags/.l2s.v0.18.2.lock0001' is not valid; class=Reference (4)
- - - - - - - - - - - - - - - - 

why here comes the "tags/.l2s." ?

**Comment by fanatid** [comment]
What is your environment?

**Comment by gotope** [comment]
> What is your environment?

here are some of configuration, 
$ uname -a                                Linux localhost 5.4.0-faked #1 SMP PREEMPT Thu Nov 11 23:00:01 CST 2021 aarch64 GNU/Linux

$ rustup show                             Default host: aarch64-unknown-linux-gnu       rustup home:  /usr/local/.rustup   
                                                           installed toolchains                          --------------------                                                                        stable-aarch64-unknown-linux-gnu (default)    
bpf                                           1.52.1-aarch64-unknown-linux-gnu             1.55.0-aarch64-unknown-linux-gnu
                                                            active toolchain                              ----------------                                                                            stable-aarch64-unknown-linux-gnu (default)   
rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by paul-schaaf** [comment]
closing because it's been a while since opening. pls reopen if this is still an issue
