### ISSUE TITLE
Can't find crate std error when using anchor build

### ISSUE THREAD

**Issue by JIVIN0902** [project-serum/anchor#1068]
```
error[E0463]: can't find crate for `std`
  --> /Users/jivinvaidya/.cargo/registry/src/github.com-1ecc6299db9ec823/bs58-0.3.1/src/lib.rs:73:1
   |
73 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `bpfel-unknown-unknown` target may not support the standard library
   = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `bs58` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Solana version is 1.8.5
anchor-cli 0.18.2
On an m1 mac with rosetta.
using x86_64 toolchains for rust

**Comment by fanatid** [comment]
It's not an anchor issue.
I'm not sure that it's possible to compile bpf target on m1 with x86_64 toolchain, please try aarch64. Or you can try to add `rust-std-..` component with rustup.

**Comment by JIVIN0902** [comment]
> It's not an anchor issue. I'm not sure that it's possible to compile bpf target on m1 with x86_64 toolchain, please try aarch64. Or you can try to add `rust-std-..` component with rustup.

It was compiling before. This happened recently. Can I use tha aarch64 toolchain with solana too?

**Comment by hogyzen12** [comment]
cargo clean and updating to most recent version of anchor resolves this problem. I encountered the same error on WSL2 and resolved it by updating everything i had and rebuilding after cargo clean. cargo build and then anchor build solved the issue for me

**Comment by paul-schaaf** [comment]
doesnt look like an issue with anchor, so Im closing this
