### ISSUE TITLE
CpiAccount deprecated warning incorrect?

### ISSUE THREAD

**Issue by awcchungster** [project-serum/anchor#1088]
The Anchor compiler gives a warning that the CpiACcount is deprecated. However CpiAccount has a distinct usage for remote contract calls. The [docs also don't mention](https://docs.rs/anchor-lang/0.9.0/anchor_lang/prelude/struct.CpiAccount.html) there being a deprecation. Is the warning an error?

The code is part of a smart contract that makes a CPI to a Token contract to mint new coins to a specific address. 

Code:
```
#[derive(Accounts)]
pub struct Interaction<'info> {
    #[account(mut, has_one = owner)]
    mint: CpiAccount<'info, TokenAccount>,
    // #[account(mut, "mint == to.mint")]
    to: CpiAccount<'info, TokenAccount>,
    #[account(signer)]
    owner: AccountInfo<'info>,
    token_program: AccountInfo<'info>,
}
```

Warning:

> warning: use of deprecated struct `anchor_lang::CpiAccount`: Please use Account instead
>   --> programs/contractMint/src/lib.rs:27:11
>    |
> 27 |     mint: CpiAccount<'info, TokenAccount>,
>    |           ^^^^^^^^^^
>    |
>    = note: `#[warn(deprecated)]` on by default
> 
> warning: use of deprecated struct `anchor_lang::CpiAccount`: Please use Account instead
>   --> programs/contractMint/src/lib.rs:29:9
>    |
> 29 |     to: CpiAccount<'info, TokenAccount>,
>    |         ^^^^^^^^^^
>

**Comment by armaniferrante** [comment]
The warning is not an error. It's recommended to use `Account` instead.

**Comment by awcchungster** [comment]
Thanks for the super fast response. Quick follow up, in my comment line, there is an account annotation `// #[account(mut, "mint == to.mint")]`. How do I call the mint public address to match the TokenAccount's mint address? 

```
#[program]
pub mod contract_mint {
    use super::*;
    pub fn interaction(ctx: Context<Interaction>, amount: u64) -> ProgramResult {
        let cpi_accounts = MintTo {
            mint: ctx.accounts.mint.to_account_info().clone(),
            to: ctx.accounts.to.to_account_info().clone(),
            authority: ctx.accounts.owner.clone(),
        };

        let cpi_program = ctx.accounts.token_program.clone();
        let cpi_ctx = CpiContext::new(cpi_program, cpi_accounts);
                token::mint_to(cpi_ctx, amount)?;
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Interaction<'info> {
    #[account(mut, has_one = owner)]
    mint: CpiAccount<'info, TokenAccount>,
    // #[account(mut, "mint == to.mint")]
    to: CpiAccount<'info, TokenAccount>,
    #[account(signer)]
    owner: AccountInfo<'info>,
    token_program: AccountInfo<'info>,
}

#[error]
pub enum ErrorCode {
    #[msg("The derived interaction signer does not match that which was given.")]
    InvalidInteractionSigner,
}
```

**Comment by fanatid** [comment]
```rust
#[account(mut, constraint = mint.mint == to.mint)]
```
If you have further questions please ask them in discord.
