### ISSUE TITLE
cli: anchor expand

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1111]
1. ship cargo expand with anchor and make it available through `anchor expand` 
2. anchor expand also redirects the output into a file in a directory that we include in .gitignore
3. instead of overwriting existing files in that directory, it creates a new one every time with some informative name. maybe the time , anchor-version etc.

to me this isn't that important and just a nice little ux improvement but maybe there are more reasons this would be a good idea (or wouldn't be)

**Comment by tomlinton** [comment]
This is a good idea - even if it is just to encourage people to expand when debugging as it is very useful. I think we could reused the `.anchor` dir for the .gitignored path.
