### ISSUE TITLE
Installing Anchor on MacOs or Using a Dockerfile

### ISSUE THREAD

**Issue by Kaleb47** [project-serum/anchor#1124]
Alright,
I'm fairly new at building on Solana and using anchor, but I keep hearing that setting up anchor is similar to Hardhat. Nothing could be further from the truth.

First I tried installing it locally on my MacOs by following these instructions https://project-serum.github.io/anchor/getting-started/installation.html#install-rust

While anchor installs successfully, every time I run a single anchor command, I receive this error.

```

Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Globally installed anchor version is not correct. Expected "anchor-cli 0.18.2", found "anchor-cli 0.19.0".

```

I tried to build the binaries myself and I got the same issue.

So then I thought anchor just isn't compatible so I tried creating a linux docker container to build and run the anchor CLI

```

FROM ubuntu:latest


RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_17.x  | bash -
RUN apt-get -y install nodejs
RUN npm install -g npm@8.3.0
RUN npm i -g @project-serum/anchor-cli
RUN apt-get update && apt-get upgrade && apt-get install -y pkg-config build-essential libudev-dev

CMD ["solana-install", "anchor-cli", "pkg-config"] 

```

Interestingly, I got the same error.

please help

<img width="970" alt="Screen Shot 2021-12-10 at 12 13 08 PM" src="https://user-images.githubusercontent.com/63081938/145623813-8631059f-811a-4e5b-9da4-0a28146eec2a.png">

**Comment by tomlinton** [comment]
> Globally installed anchor version is not correct. Expected "anchor-cli 0.18.2", found "anchor-cli 0.19.0".

This seems to indicate you had the anchor cli installed via building with cargo but you also installed it via npm and the npm version is first in PATH. Doing `npm uninstall -g @project-serum/anchor` should resolve your problems.

I won't attempt to debug that Dockerfile, but the error isn't the same. It seems like `npm` is missing in your path so maybe something like `sudo apt-get install npm` in place of `npm install -g npm@8.3.0` might solve it. It looks like you are also missing the Solana source though. If you want to run it using Docker I recommend you base your build on https://github.com/project-serum/anchor/blob/master/docker/build/Dockerfile

**Comment by hetdagli234** [comment]
I am facing the same error, I uninstalled the npm package using `npm uninstall -g @project-serum/anchor`, it didn't resolve the error, here is my error message:
`Globally installed anchor version is not correct. Expected "anchor-cli 0.17.0", found "anchor-cli 0.19.0".`

**Comment by fanatid** [comment]
This error from npm package `@solana/anchor-cli`. You need to remove this package because it's only working on Linux.
