### ISSUE TITLE
using #buildspace and unable to execute anchor test --skip-local-validator

### ISSUE THREAD

**Issue by Suveett** [project-serum/anchor#1132]
@ChewingGlass / Anchor Team, 
I am really sorry writing basic questions,  but I am absolutely new to Solana. I have just learnt rust and i wanted to get started with Solana ecosystem. 

I followed all instructions as mentioned in link :
https://github.com/buildspace/buildspace-projects/blob/main/Solana_And_Web3/en/Section_2/Resources/m1_setup.md

However, i get the error as below : **anchor test --skip-local-validator error: no such subcommand: build-bpf**
`Last login: Sat Dec 11 19:01:21 on ttys003
aadyakalra@Aadyas-MacBook-Air solana % cd myepicproject
aadyakalra@Aadyas-MacBook-Air myepicproject % yarn -v
1.22.17
aadyakalra@Aadyas-MacBook-Air myepicproject % anchor --version
anchor-cli 0.19.0
aadyakalra@Aadyas-MacBook-Air myepicproject % anchor test --skip-local-validator
error: no such subcommand: `build-bpf`
aadyakalra@Aadyas-MacBook-Air myepicproject % `

> Also, if you see my Terminal with cd solana , even the solana local validator is **actually running**
<img width="1440" alt="Screenshot 2021-12-11 at 7 17 20 PM" src="https://user-images.githubusercontent.com/75737576/145679095-e9e93e8e-d14a-40d7-aa3a-535c998f3ed4.png">

_I am unable to figure out how to proceed, if you could help me I shall be extremely obliged @project-serum/anchor_

Thanks and Regards

Suveett Kalra

**Comment by PaulEbose** [comment]
Have you tried reinstalling `anchor`?

**Comment by fanatid** [comment]
If it's still actual please move the question to discord.
