### ISSUE TITLE
Clippy warnings aren't being enforced by github action tests

### ISSUE THREAD

**Issue by kevinaud** [project-serum/anchor#1148]
It looks like [there is already a test](https://github.com/project-serum/anchor/blob/a7e80079dab0beffea77c3336b0680fc11b4e128/.github/workflows/tests.yaml#L37) that enforces clippy compliance but it doesn't seem to be working. When I run `cargo clippy --all-targets -- -D warnings` on a fresh version of master I am getting a few failures.

**Comment by paul-schaaf** [comment]
@kevinaud have you checked that youre using the same rust version as the tests (`1.57`)?

**Comment by kevinaud** [comment]
Oops, should've thought of that. Nope I'm on 1.59 so that should explain it. Thanks!

**Comment by fanatid** [comment]
I think it would be good to add clippy for nightly channel in addition to fixed version.
