### ISSUE TITLE
ts: when starting a new anchor project, the workspace type is missing

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1153]
After running
```
anchor init hello-world
```

In `tests/hello-anchor.ts`: 

```
Property 'workspace' does not exist on type 'typeof import("/Users/paul/Coding/solana/forks/hello-anchor/node_modules/@project-serum/anchor/dist/cjs/index")'.ts(2339)
```

The js object does exist because my tests are running fine. It's just the type that is missing

**Comment by lucasnad27** [comment]
I've ran into this issue as well, running v0.19.0

**Comment by dan-garay** [comment]
Stuck on this too

**Comment by ton11797** [comment]
Workaround
change
`import * as anchor from '@project-serum/anchor';`
to
`const anchor = require("@project-serum/anchor");`

**Comment by janlegner** [comment]
Also `Wallet` is missing. It is caused by recent changes with
```
if (!isBrowser) {
  exports.workspace = require("./workspace.js").default;
  exports.Wallet = require("./nodewallet.js").default;
}
```

The workaround with `require` is not good enough as the type is then `any`. Of course, another workaround would be to add custom declaration files. But also maybe this could work: #1182. What do you think?

**Comment by ron-liu** [comment]
We hit this problem too, hope can be released soon.

**Comment by paul-schaaf** [comment]
fixed by https://github.com/project-serum/anchor/pull/1137
