### ISSUE TITLE
Invalid blockhash error when I try to deploy

### ISSUE THREAD

**Issue by Sargnec** [project-serum/anchor#1157]
I dont know how to solve this. When I try to deploy to solana  with _anchor deploy_ its always gives me this error
`Error: Custom: Invalid blockhash`
`There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.`

I'm following tutorial made by [buildspace](https://app.buildspace.so/home) and the tutorial name is **Build a Web3 app on Solana with React and Rust**. I get this error in section 3 lesson 1

**Comment by monkeyMax-SVG** [comment]
I am getting exactly same issue

**Comment by enzoampil** [comment]
getting this issue now. Interesting bit is i notice it correlating with deployments taking longer. Could it be that larger programs are now being validated in time; hence, the "timeout error" (`ExitStatus(unix_wait_status(256))` seems like a timeout error)

**Comment by enzoampil** [comment]
I was able to resolve my error by reverting to earlier versions of `solana-cli` and `anchor-cli`

```
solana-cli 1.8.0 (src:4a8ff62a; feat:1813598585)
anchor-cli 0.18.2
rustc 1.57.0 (f1edd0429 2021-11-29)
```

**Comment by armaniferrante** [comment]
This is likely not related to Anchor. Closing.

**Comment by AuroraLantean** [comment]
I have solved this:

```
Local npm package: @project-serum/anchor 0.20.1
Solana program dependencies: anchor-lang 0.20.1, anchor-spl 0.20.1, solana-program 1.9.4
deployment to devnet failed

Local npm package: @project-serum/anchor 0.18.2
Solana program dependencies: anchor-lang 0.18.2, anchor-spl 0.18.2, solana-program 1.9.4
deployment to devnet succeeded!
```

in both cases, the global environment is:

```
Rust 1.57.0
solana-cli 1.9.4
@project-serum/anchor-cli 0.20.1
```

**Comment by abhi3700** [comment]
For Mac M1,
```
Rust 1.57.0
solana-cli 1.9.4
@project-serum/anchor-cli 0.20.1
```
these tools' versions work.
I tried myself.

**Comment by jeffhu1** [comment]
Reverting solana-cli from `1.9.5` to `1.8.0` fixed this for me

**Comment by saintsol** [comment]
@abhi3700 @jeffhu1 did u have issues compiling solana 1.8.0 on M1 mac? 

i'm getting 

```
 Installing spl-token-cli v2.0.15
error: failed to compile `spl-token-cli v2.0.15`, intermediate artifacts can be found at `/var/folders/5x/qdyndvsd67924z389z1dxngh0000gn/T/cargo-installEv9kzL`

Caused by:
  failed to download `ed25519 v1.4.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.4.0/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
```

**Comment by qbig** [comment]
solana-cli 1.8.12 works

**Comment by Abusayid693** [comment]
One main reason for this error is **poor internet connection**, make sure your internet connection is fast enough before deploying.
