### ISSUE TITLE
translateAddress caused bug in production build [ts]

### ISSUE THREAD

**Issue by dongnguyen9186** [project-serum/anchor#1163]
This check is quite weird: address.constructor.prototype.constructor.name === "PublicKey" in https://github.com/project-serum/anchor/blob/v0.19.0/ts/src/program/common.ts#L61
The PublicKey class name will be mangled with production build/minification. Then the runtime error can happen

**Comment by armaniferrante** [comment]
An early release has been published taking out this check. See v0.19.1-beta.1.
