### ISSUE TITLE
Pattern for transferring SOL from an escrow PDA

### ISSUE THREAD

**Issue by ChristopherEhmann** [project-serum/anchor#1172]
Hello everybody. 
To learn solana/anchor I'm trying to implement a simple lock program (code [here](https://github.com/ChristopherEhmann/solana_lock/blob/mac/programs/lock/src/lib.rs)):
* Owner creates a vault where they can pay in SOL
* Authority can unlock/lock vault
* Owner can withdraw SOL only if account is unlocked.

I'm struggling to find a pattern how to escrow SOL. My first idea is to store everything in one account
```Rust
#[account]
pub struct LockAccount {
    pub owner: Pubkey,
    pub authority: Pubkey,
    pub locked: bool,
    bump: u8,
}
```
and initialize this as a PDA
```Rust
#[derive(Accounts)]
#[instruction(bump: u8)]
pub struct Initialize<'info> {
    #[account(init,
    payer=owner,
    space=8 + 32 + 32 + 1 + 1 ,
    seeds=[owner.key().as_ref()],
    bump=bump)
    ]
    pub lock_account: Account<'info, LockAccount>,
    #[account(mut)]
    pub owner: Signer<'info>,
    pub system_program: Program<'info, System>,
}
```
Initialization, locking and unlocking is working. But I'm struggling with withdrawl:
```Rust
    pub fn withdraw(ctx: Context<Withdraw>, lamports: u64) -> ProgramResult {
        let lock_account = &mut ctx.accounts.lock_account;
        let transfer_instruction = &transfer(
            &lock_account.to_account_info().key,
            &lock_account.owner,
            lamports,
        );
        msg!("Withdrawing {}", lamports);

        invoke_signed(
            transfer_instruction,
            &[
                lock_account.to_account_info(),
                ctx.accounts.owner.to_account_info(),
                ctx.accounts.system_program.to_account_info()
            ],
            &[&[
                ctx.accounts.owner.to_account_info().key.as_ref(),
                &[lock_account.bump],
            ]],
        )
    }
```
But I'm getting:
```bash
  logs: [
    'Program E41ZWCPjxsHmAv6DhUdfduj8W2bt7VCnq4RiypAL1RYc invoke [1]',
    'Program log: Withdrawing 1000000000',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Transfer: `from` must not carry data',
    'Program 11111111111111111111111111111111 failed: invalid program argument',
    'Program E41ZWCPjxsHmAv6DhUdfduj8W2bt7VCnq4RiypAL1RYc consumed 5027 of 200000 compute units',
    'Program E41ZWCPjxsHmAv6DhUdfduj8W2bt7VCnq4RiypAL1RYc failed: invalid program argument'
  ]
```
After some digging[ I think I found out](https://githubmemory.com/repo/solana-labs/solana/issues/19763), that you can't withdraw from pda accounts with data. 

So here are my questions:
* If I generate an account via `#[account(init)]`, who owns this? SystemProgram or my program?
* Are calls like `invoke` always calls to SystemProgram? I initially thought so but 
```Rust
    pub fn payin(ctx: Context<Payin>, lamports: u64) -> ProgramResult {
        let lock_account = &mut ctx.accounts.lock_account;
        let transfer_instruction = &transfer(
            &lock_account.owner,
            &lock_account.to_account_info().key,
            lamports,
        );
        msg!("Paying in {}", lamports);
        invoke(
            transfer_instruction,
            &[
                ctx.accounts.owner.to_account_info(),
                lock_account.to_account_info(),       
            ]
        )
    }
````
seems to work without passing it. But if I try to omit SystemProgram in the `withdraw` function I get an error that an account is missing.
* Can pda accounts with data _not_ have SOL deducted if they are owned by SystemProgram or in general? Assuming my PDA is owned by the lock program it looks like it.
* If so what would the pattern look like to escrow SOL? 
   * Does the `lock` program create a second escrow PDA in the initialize function without the client needing to specify it? If so how?
   * Does the client need to generate a second PDA that only holds SOL and no data? Something like?
 ```Rust
#[account]
pub struct LockEscrowAccount {}
```

I know many questions, but thank you in advance.

**Comment by armaniferrante** [comment]
Please ask these questions in Discord. Closing as this is not development related.
