### ISSUE TITLE
Account Subscriptions for Rust Client

### ISSUE THREAD

**Issue by r614** [project-serum/anchor#1183]
The latest version of Solana-Client supports [Account Subscriptions](https://docs.rs/solana-client/latest/src/solana_client/pubsub_client.rs.html#228-267) via `PubsubClient::accounts_subscribe`. Does the Rust `anchor-client` plan to support the same API? At the moment it looks like it only supports event emissions via `PubsubClient::logs_subscribe`.

**Comment by fanatid** [comment]
I'm not sure that I understand but why account subscription should be added?

**Comment by r614** [comment]
Sorry about that! Here's some more context: 

In the Typescript SDK, I can add an event listener to a specific account address, on a program, via the [AccountClient.subscribe](https://github.com/project-serum/anchor/blob/08174e84a6db0e945e93a91bb1f2770365f68f4c/ts/src/program/namespace/account.ts#L257) method, and listen to on-change events. For example, in [Drift Protocol's Typescript SDK](https://github.com/drift-labs/protocol-v1/blob/master/sdk/src/accounts/webSocketAccountSubscriber.ts):

```typescript
export class WebSocketAccountSubscriber<T> implements AccountSubscriber<T> {
	data?: T;
	accountName: string;
	program: Program;
	accountPublicKey: PublicKey;

	async subscribe(onChange: (data: T) => void): Promise<void> {
		this.data = (await this.program.account[this.accountName].fetch(
			this.accountPublicKey
		)) as T;

		onChange(this.data);

		this.program.account[this.accountName]
			.subscribe(this.accountPublicKey, this.program.provider.opts.commitment)
			.on('change', async (data: T) => {
				this.data = data;
				onChange(data);
			});
	}
}


```

I am trying to do the same thing in Rust, but we don't have an equivalent method in the `anchor::lang` crate. Instead, I have to listen to a generic event using `Program.on`, and then parse it myself to see if it applies to a specific account I am looking for changes to. Imo this is too much overhead, especially if Solana exposes a RPC connection per account. 

I am just curious if I am missing something, in the library/docs or the best path forward is to bypass and use the Solana API instead.

**Comment by fanatid** [comment]
You need to use `account_subscribe` from `solana-client` crate.
https://docs.rs/solana-client/latest/solana_client/pubsub_client/struct.PubsubClient.html#method.account_subscribe

**Comment by y2kappa** [comment]
Have a look at https://github.com/hubbleprotocol/solana-shadow/
