### ISSUE TITLE
Simple access control in CPI

### ISSUE THREAD

**Issue by ppoliani** [project-serum/anchor#1185]
I have looked into the source code and checked the examples as well but It still very confusing to accomplish the following simple scenario. 

I want to extend the basic-3 CPI example so it includes so access control. Basically, I would like the `set_data` to be only called by the `puppet-master` program. Unfortunately, at the moment it is very hard to understand how this can be done with anchor.

**Comment by paul-schaaf** [comment]
if this hasnt been solved by now, please use the discord for support questions https://discord.gg/7uU5srpa
