### ISSUE TITLE
Custom program error 0xbbf

### ISSUE THREAD

**Issue by krishnawinit** [project-serum/anchor#1193]
I am getting custom program error 0xbbf how can i solve it

**Comment by fanatid** [comment]
0xbb7 is 3007, you can find errors description in error.rs file:
https://github.com/project-serum/anchor/blob/51aeb08ae1c93f9f759c6e244e3fa724c9a916a7/lang/src/error.rs#L81

If you have further questions please ask in discrod: https://discord.gg/sxy4zxBckh
