### ISSUE TITLE
lang: Add feature flag for using repr(packed) for zero copy

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1198]
https://github.com/project-serum/anchor/pull/1106 introduced a breaking change to use repr(C). However, this breaks existing programs using repr(packed). We should introduce a feature flag to use repr(packed) instead (or alternatively add an optional argument, e.g. `#[account(zero_copy, repr(packed))]`).

**Comment by paul-schaaf** [comment]
closed by #1273
