### ISSUE TITLE
why windows sys is no run?

### ISSUE THREAD

**Issue by 624133262** [project-serum/anchor#1200]
anchor test
Solana Rust BPF toolchain is not available on Windows
![image](https://user-images.githubusercontent.com/28002830/147542465-9e8522b2-c848-4eef-88c3-b98d5e564bc8.png)

**Comment by fanatid** [comment]
Anchor can not support what solana does not support. Please use Linux/MacOS. https://forums.solana.com/t/solana-rust-bpf-toolchain-is-not-available-on-windows/2711
