### ISSUE TITLE
lang, docs: anchor does not export data structures idiomatically

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1206]
Example:

<img width="1029" alt="Screenshot 2021-12-29 at 12 19 03" src="https://user-images.githubusercontent.com/29666990/147657098-7b6ea429-4ba1-4c73-b623-dad9ccfa734e.png">

- Anchor `prelude` paths are included in `docs.rs`. They should not be included because `prelude` is just a helper module (that is what the rust std docs do at least).
- `Account` is exported directly under the root. It should be exported with its proper path (`anchor_lang::accounts::account::Account`).

Account is just one example of many. For Account (and the other types in the accounts folder) it can be solved by removing the Account export in `lib.rs`, making the accounts mod in `lib.rs` a `pub mod` and exporting `accounts::account::Account` in the prelude instead of just `Account`. Doing it this way makes `Account` a re-export instead of a struct inside `prelude`.

I dont think `doc(hidden)` on the prelude mod is the solution because if you search for it, you should find it, but its members shouldnt show up in the search because theyre just re-exports (or they should be re-exports, but arent right now, which is causing these problems)

**Comment by paul-schaaf** [comment]
open question: how to deal with crates like `anchor_attribute_account`. These are also currently not re-exported by anchor and can therefore be found in the docs in the prelude module, but not anywhere else. If the prelude just re-exported these, they could not be found in the docs of `anchor_lang` at all.

**Comment by armaniferrante** [comment]
Note that crates like `anchor_attribute_account` must be in their own crate (or shared within a still separate crate) because they are proc macros.

**Comment by paul-schaaf** [comment]
yes. I didnt mean that we should actually move them into anchor_lang.

prelude currently `pub use`s them but this does not re-export them (any idea why?). instead it defines them as members of prelude. my idea is to have a separate module `pub use` them. that way, they can be found in the docs via that module because it wont reexport them either. but I havent managed to reexport them from that module by the prelude yet. it still defines them as members of prelude.
