### ISSUE TITLE
`Signer` that's used as `payer` for `init` is read only in cpi `to_account_metas` which cause cpi to fail

### ISSUE THREAD

**Issue by crispheaney** [project-serum/anchor#1218]
If you specify an `AccountInfo` as `Signer` and also specify the signer as `payer` in `#[account(init)`, the `cpi` module will create a read only `AccountMeta`. The `AccountMeta` needs to be writable for the signer to act as payer, so this causes cpi to fail.

The workaround seems to be to use `#[account(mut, signer)]` instead of `Signer`.

Example:
I specify a `Signer` [here](https://github.com/drift-labs/protocol-v1/blob/master/programs/clearing_house/src/context.rs#L94) and  use it as a `payer` [here](https://github.com/drift-labs/protocol-v1/blob/master/programs/clearing_house/src/context.rs#L85). When I run `cargo expand --features cpi` I get in ToAccountMetas:
```
account_metas.push(
   anchor_lang::solana_program::instruction::AccountMeta::new_readonly(
      anchor_lang::Key::key(&self.authority),
      true,
   ),
);
```

This leads to the `{address}'s writable privilege escalated`

If I change the `Signer` to be `#[account(mut, signer)]` `cargo expand --features cpi` gives me:

``` 
account_metas.push(anchor_lang::solana_program::instruction::AccountMeta::new(
   anchor_lang::Key::key(&self.authority),
   true,
));
```
And the cpi works.

**Comment by armaniferrante** [comment]
I'm surprised `#[account(signer)]` has any affect on the AccountMeta.

**Comment by paul-schaaf** [comment]
maybe Im misunderstanding but it looks like normal behaviour to me.

The payer needs to be mutable to pay, cpi or not. You didnt mark it as such so the generated code created a cpi with a read-only Account.

What was the expected behaviour?

> The workaround seems to be to use #[account(mut, signer)] instead of Signer.

This is not a workaround. It's what you are supposed to do.

**Comment by crispheaney** [comment]
Ok I was wrong! 

I thought that anchor was marking the `authority` (`Signer`) as mutable because it saw it used as `payer`. But actually this was working without `#[account(mut)]` because the ts client makes the provider wallet account mutable by default, so when i executed this instruction using ts client it is writable but when i did it with cpi it failed.

So the right thing to do is mark the Signer with `#[account(mut)]`.
