### ISSUE TITLE
lang: Error if account init payer account is not marked mutable

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1219]
This coincidentally works if the account is not marked mutable since the client will use the provider to pay for the transaction (and thus it is mutable). However, we should require the developer to explicitly mark these paying accounts mutable.

**Comment by losman0s** [comment]
I'm up for giving this a spin. First time I dive into this part of Anchor though, so do you have a specific place where adding this logic would be best, maybe?

I see there seems to be constraint checks done [here](https://github.com/project-serum/anchor/blob/master/lang/syn/src/parser/accounts/constraints.rs#L893), but they seem limited to per-account checks (e.g. `payer` attribute unique per account), and I have not found an instance of cross-account check yet.

Would it make sense to add these checks [here](https://github.com/project-serum/anchor/blob/master/lang/syn/src/idl/file.rs#L27)?

**Comment by paul-schaaf** [comment]
@losman0s are you still interesting in doing this?

If so, you can add the checks in this new function https://github.com/project-serum/anchor/blob/01ff03b09b30b974f2854dd0b0b9a958dd509622/lang/syn/src/parser/accounts/mod.rs#L40

**Comment by losman0s** [comment]
@paul-schaaf yes, been a bit tied up the last few days but I'll get to it soon. Thanks for the update.

**Comment by adimnaka** [comment]
Hi guys im experiencing this error, can any one help

thread 'main' panicked at 'Code not parseable: Error("the payer specified for an init constraint must be mutable.")', lang/syn/src/idl/file.rs:360:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by losman0s** [comment]
> Hi guys im experiencing this error, can any one help
> 
> thread 'main' panicked at 'Code not parseable: Error("the payer specified for an init constraint must be mutable.")', lang/syn/src/idl/file.rs:360:58 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

It should pretty much be what the error describes. You are likely init-ing an account through the `init` macro, but forgot to mark the `payer` account you specified as `mut`.
If this does not fix your issue, please post your question on Discord instead.

**Comment by adimnaka** [comment]
Oh thanks, that solved the issue. but im finally trying to deploy to dev net but i get this error again 

error: Custom: Invalid blockhash
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.

**Comment by losman0s** [comment]
> Even if this does not fix your issue, please post your question on Discord instead.

**Comment by adimnaka** [comment]
Whats the link to the discord channel seems the one i'm on wont allow me post anything
Thanks
