### ISSUE TITLE
Is there any sample code access and read anchor program from standard program?

### ISSUE THREAD

**Issue by huybuidac** [project-serum/anchor#1228]
For example: how a standard program read anchor zero_copy account or normal account?

```rust
    pub pool: AccountLoader<'info, PoolAccount>,
```

**Comment by paul-schaaf** [comment]
@huybuidac yes there is sample code. the official anchor tutorial https://project-serum.github.io/anchor/tutorials/tutorial-1.html#defining-a-program tells you how to read from and write to accounts.
