### ISSUE TITLE
RangeError: encoding overruns Buffer . Error while sending invoking rpc method with data more than 700 chars

### ISSUE THREAD

**Issue by aabidsofi19** [project-serum/anchor#1229]
i am a solana newbie . and while i am trying to create a bloggapp on solana using the anchor framework . 
if i send a string of less than about 700 chars the instruction runs successfully . but when i excced this limit of data . the anchor ts client throws the following error .

`RangeError: encoding overruns Buffer
    at Blob2.encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:30884)
    at Structure.encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:30408)
    at WrappedLayout.encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:31148)
    at WrappedLayout.encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:31148)
    at Structure.encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:30408)
    at InstructionCoder._encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:32353)
    at InstructionCoder.encode (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:32341)
    at :3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:37673
    at ix (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:37041)
    at txFn (:3000/node_modules/.vite/@project-serum_anchor.js?v=eb4c9659:37129)`

i am a little confused because i have allocated a space for 2400 chars int the instruction in rust program . 
also some times i get an error of transaction is too large . but i think the max length is 10mb and for cpi its 10200 . in anchor .

below is my anchor and js code ..

`
const DISCRIMINATOR_LENGTH: usize = 8;
const PUBLIC_KEY_LENGTH: usize = 32;
const TIMESTAMP_LENGTH: usize = 8;
const STRING_LENGTH_PREFIX: usize = 4; // Stores the size of the string.
const MAX_TITLE_LENGTH: usize = 100 * 4; // 100 chars max.
const MAX_CONTENT_LENGTH: usize = 2420 * 4; // 2800 chars max.

#[derive(Accounts)]
pub struct CreatePost<'info> {
    
    #[account(init,payer=authority,space=BlogPost::LEN)]
    pub blog_post: Account<'info,BlogPost> ,
    #[account(mut)]
    pub authority : Signer<'info> ,
    #[account(address = system_program::ID)]
    pub system_program: AccountInfo<'info>
    

}

#[account]
pub struct BlogPost{

    pub authority : Pubkey ,
    pub timestamp: i64,
    pub content :  Vec<u8>,
    pub title : String,
    
}

impl BlogPost {
    const LEN: usize = DISCRIMINATOR_LENGTH
        + PUBLIC_KEY_LENGTH // Author.
        + TIMESTAMP_LENGTH // Timestamp.
        + STRING_LENGTH_PREFIX + MAX_TITLE_LENGTH // Topic.
        + STRING_LENGTH_PREFIX + MAX_CONTENT_LENGTH; // Content.
}
`

and this is the js code 

`
async function createPost(program:Program<Blog> ,provider:Provider ,postData:BlogData){

    // conver our blog account strig to public Key
    console.log("blog data",postData)

    console.log("program", program)
    console.log("provider", provider)
    let content = Buffer.from(postData.content)
    let blogPostAccount = web3.Keypair.generate()
    
    let tx = await program.rpc.createPost(
        postData.title,content,    
        {
            accounts:{
                blogPost:blogPostAccount.publicKey,
                authority : provider.wallet.publicKey,
                systemProgram: SystemProgram.programId,
            },
            signers:[blogPostAccount]
        }
    )
    console.log("Your transaction signature for createpost ", tx)
    return blogPostAccount
}
`

**Comment by paul-schaaf** [comment]
@aabidsofi19 max size of a tx is 1232 bytes.

**Comment by aabidsofi19** [comment]
Thanks @paul-schaaf  .  If the max size for a transaction is 1232 bytes  . What should be the proper way of initilializing an acount with  data larger than that 1232 bytes.

**Comment by paul-schaaf** [comment]
@aabidsofi19 multiple transactions. you could have a counter and each tx includes an increasing number and the program will reject tx that come out of order or you could calculate locally at which offset in the account each tx would save its part of the blog in and then you dont get canceled transactions

**Comment by aabidsofi19** [comment]
Thanks @paul-schaaf  . This will help a lot .. 😊

**Comment by flyingdreams1** [comment]
I also encountered this problem. Can you give me an example? Please help me
