### ISSUE TITLE
ts: Browser detection should not depend on BROWSER environment variable

### ISSUE THREAD

**Issue by aximili-dev** [project-serum/anchor#1232]
In [/ts/src/utils/common.ts](https://github.com/project-serum/anchor/blob/5edaf7af841296079906e16bf8b9fb8795249403/ts/src/utils/common.ts) the `BROWSER` environment variable is used to determine if the program is running inside a web browser, however, it is common practice for GNU/Linux distros to use it to specify which app should be used to open web links. 

As an example this causes issues when trying to connect to a localnet, since the local provider is not available inside a browser. If the fix is as easy as removing [this line](https://github.com/project-serum/anchor/blob/5edaf7af841296079906e16bf8b9fb8795249403/ts/src/utils/common.ts#L6) I'd be happy to submit a pull request with just that.

**Comment by akutruff** [comment]
Similar issue: https://github.com/project-serum/anchor/issues/1145

**Comment by aximili-dev** [comment]
Similar to #1145

**Comment by ndrewtl** [comment]
I'm running into this in `anchor-cli 0.24.2`. It doesn't seem to have been fixed. Can we reopen the issue?
