### ISSUE TITLE
Anchor test failed with 

### ISSUE THREAD

**Issue by abdul-maajid** [project-serum/anchor#1235]
![Screenshot from 2022-01-05 00-08-01](https://user-images.githubusercontent.com/53260291/148115878-849c57f2-ac69-4d32-81d1-34a7b9b6ea8c.png)
I am getting this error when i run anchor test.

**Comment by paul-schaaf** [comment]
answered on discord https://discord.com/channels/889577356681945098/889702325231427584/928037853789835264
