### ISSUE TITLE
Download error when invoking npm command 

### ISSUE THREAD

**Issue by JayHoward16** [project-serum/anchor#1237]
I've been receiving the same : notfoundram error when attempting to npm install yarn and the anchor cli. Please and Thank you to all ! 

Error: 
input: npm i @project-serum/anchor-cli

cli output: : not foundram Files/nodejs/npm: 3:
: not foundram Files/nodejs/npm: 5:
/mnt/c/Program Files/nodejs/npm: 6: Syntax error: word unexpected (expecting "in")

I am currently running Ubuntu on my Windows 11 machine. 

P.S. Happy New Years !

**Comment by fanatid** [comment]
Do you have node and npm installed?

**Comment by JayHoward16** [comment]
Hey Fanatid thanks for the reply. I have downloaded node.js and npm I am also receiving this error in my cli when I invoke any npm command. 

Output:
/mnt/c/Program Files/nodejs/npm: line 3: $'\r': command not found
/mnt/c/Program Files/nodejs/npm: line 5: $'\r': command not found
/mnt/c/Program Files/nodejs/npm: line 6: syntax error near unexpected token `$'in\r''
'mnt/c/Program Files/nodejs/npm: line 6: `case `uname` in

Im starting to believe my npm file is tampered. 



> Do you have node and npm installed?

**Comment by fanatid** [comment]
Just start with simple commands, like
```bash
node --version
npm --version
```
If you have problems here it's not an `anchor` issue.

**Comment by JayHoward16** [comment]
> npm i @project-serum/anchor-cli

my command line output both outputs. But now when I invoke the npm package command I receive an unsupported error go figure. 

 Unsupported platform for @project-serum/anchor-cli@0.19.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
 
Thank you for the reply btw.

**Comment by fanatid** [comment]
`@project-serum/anchor-cli` only works on linux/x64 at the moment. You need to install anchor from the source, if you have futher questions about installation please move it to Discord.
