### ISSUE TITLE
  Every time i try building my anchor project this is the major error that i get  consider adding `cargo-features = ["edition2021"]` to the manifest

### ISSUE THREAD

**Issue by Nishchay1571999** [project-serum/anchor#1254]
I am trying to build a project using anchor and then have been stuck at the start.     I have no code in my program file and a s i run the file  I get this error
`anchor build 
BPF SDK: /home/basementwolfe/.local/share/solana/install/releases/1.7.11/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
error: failed to download `solana-frozen-abi v1.9.3`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/basementwolfe/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-frozen-abi-1.9.3/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest`
 This is my rust version :
`rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0-nightly (cfa4ac66c 2022-01-06)``
and this is my anchor version :
`anchor-cli 0.19.0`

**Comment by Nishchay1571999** [comment]
Can some one help me

**Comment by paul-schaaf** [comment]
@Nishchay1571999 looks like your solana version is quite old. update with `solana-install update`

**Comment by Nishchay1571999** [comment]
yaa i just did that now i can build the project .... Thanks
