### ISSUE TITLE
ts: Installing @project-serum/anchor 0.20.1 on client crash due to missing module `assert` 

### ISSUE THREAD

**Issue by AlberErre** [project-serum/anchor#1290]
On a fresh install `@project-serum/anchor` version `0.20.1` crashed on client (in this case React) due to missing `assert` module. 

A quick workaround is to install this module manually ✅ 
```
yarn add assert
``` 

🚨 Just pointing this out, as I assume it's not intended. Since webpack 5, polyfills for node.js core modules are not included.

**Comment by fanatid** [comment]
It looks like an issue related with React (or webpack) issue, not anchor. I think we can close this and #1194.

**Comment by AlberErre** [comment]
@fanatid I've digged a bit more and it's indeed a `webpack 5` issue. Taking a rollback to last `webpack 4` stable version makes the trick.

In my case, just needed to run `yarn add --exact react-scripts@4.0.3`.

**Comment by AlberErre** [comment]
I've opened a PR(#1320) to add this detail to documentation, in case someone else is facing it.

Closing issue.
