### ISSUE TITLE
Making TokenAccount / Mint Zero Copy?

### ISSUE THREAD

**Issue by dovahcrow** [project-serum/anchor#1296]
... so that we can save more stack space from account deserialization?

**Comment by paul-schaaf** [comment]
dont think thats possible.

the token program accounts do not follow the `zero_copy` rules and even if they were, forcing users to use the `load` functions which is an advanced feature for getting access to the the basic feature that is token program accounts it not good DX. the zero_copy api might improve in the feature but token program accounts will still not follow the zero copy rules then

**Comment by dovahcrow** [comment]
@paul-schaaf Yeah I see your point. The unpack interface Mint/TokenAccount used is not compatible with zero_copy.
