### ISSUE TITLE
ts: getProgramAccounts for each account type

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#13]
We should provide a `getProgramAccounts` method that filters on the account discriminator, which has the effect of getting all accounts of a given type associated with a program.

**Comment by kevinrodriguez-io** [comment]
@armaniferrante Was this implemented or has an alternative?

**Comment by armaniferrante** [comment]
Yes it was implemented via the all method. https://project-serum.github.io/anchor/ts/classes/AccountClient.html#all
