### ISSUE TITLE
anchor fails windows 

### ISSUE THREAD

**Issue by tomnenel** [project-serum/anchor#1315]
Hello,

I started a brand new project on Windows x64.
When I do `cargo metadata` from my project folder, it works correctly and I get an expected output.
When I do from the same folder `anchor test` or `anchor build`, it is not working and I get the following output:
```
Failed to obtain package metadata: 'cargo metadata' exited with an error: error: failed to load manifest for workspace member '\\?\C:\Users\thugu\Documents\OneDrive\OneDrive_Doc\Crypto-project\solequapp\programs\*'

Caused by:
  failed to read '\\?\C:\Users\thugu\Documents\OneDrive\OneDrive_Doc\Crypto-project\solequapp\programs\*\Cargo.toml'

Caused by:
  The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

I dont understand why the path generated looks like this with anchor while it is correct when doing the cargo metadata directly.
Any help welcome.

Thanks

**Comment by hippiemeraki** [comment]
I also face some issue in installing anchor!!!!!! in windows 11

**Comment by arunavo4** [comment]
Use the WSL2 Ubuntu, works like charm for me

**Comment by kgilliam125** [comment]
As a workaround without using WSL, what you can do here is execute the command which `anchor test` is running (see your Cargo.toml). In this case that would be something like `yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts` for the repo I have set up.

It seems like there may be an issue to the path building logic in anchor vs. something with your local setup. I don't know the code well, so not sure where to fix at the moment, but I think it might be in https://github.com/project-serum/anchor/blob/a604f8595c875a23b8e13c8569577d6a6b1c79bd/cli/src/config.rs .

**Comment by JacobWarner** [comment]
In desperate need of an actual solution. I can't find anything on it.

**Comment by arunavo4** [comment]
Hey @JacobWarner this development cycle works great for me.
```
# Make sure you’re on the localnet.
solana config set --url localhost
# And check your Anchor.toml file.

# Code…

# Run the tests.
anchor test

# Build, deploy and start a local ledger.
anchor localnet
# Or
solana-test-validator
anchor build
anchor deploy

# Copy the new IDL to the frontend.
anchor run copy-idl

# Serve your frontend application locally.
npm run serve

# Switch to the devnet cluster to deploy there.
solana config set --url devnet
# And update your Anchor.toml file.

# Airdrop yourself some money if necessary.
solana airdrop 5

# Build and deploy to devnet.
anchor build
anchor deploy

# Push your code to the main branch to auto-deploy on Netlify.
git push
```

For Ref use this link : https://lorisleiva.com/create-a-solana-dapp-from-scratch/getting-started-with-solana-and-anchor

I have used it on Windows WSL2 and Linux and MacOS 12 (M1 Pro) all works perfectly fine. Reach out if you need help and can provide with a github git if you need.

**Comment by tomnenel** [comment]
Hello
Thank you for your replies.
I use Windows WSL2 and with your tip, got it working. Cheers

**Comment by SwayStar123** [comment]
using wsl is a work around not a fix, not sure why the issue was closed

**Comment by amTechie** [comment]
I face same issue on windows 10. Isn't there any other way except for using WSL?

**Comment by kgilliam125** [comment]
> I face same issue on windows 10. Isn't there any other way except for using WSL?

@amTechie I actually looked into this for a bit. Turns out the issue is with solana cli, which anchor calls for quite a few things. Right now, outside of fixing it in solana cli, you need to resort to WSL.

All in all it isn't that big of a change. Just make sure you run your local validator from the WSL Home area, not the default Windows home. You can set up a profile w/ Windows Terminal that just automates this.

**Comment by metta0714** [comment]
Setting your HOME env variable on windows fixes this issue.

I had this issue on windows and set HOME env variable to C:/Users/MyUserName

"anchor build" runs cargo build-bpf which checks for HOME env variable ( see link below ) . On bash shells this is set automatically, but its not set on windows cmd prompt terminal.

https://github.com/solana-labs/solana/blob/d5dec989b93fc94c9416a60193e52e8b68bd7133/sdk/cargo-build-bpf/src/main.rs#L474

**Comment by EF08** [comment]
@metta0714 I did this. Still same error

**Comment by charleslukes** [comment]
I noticed this error happened when I added dependencies in the cargo toml at the root of my project. 

Add all your dependencies in the programs/<<project name>>/cargo.toml folder
