### ISSUE TITLE
Incompatible with current react-scripts (v5.0.0) while using create-react-app 

### ISSUE THREAD

**Issue by Apra487** [project-serum/anchor#1318]
Maybe it's an issue of webpack 5/react-scripts but the latest version of anchor is incompatible with `create-react-app` due to webpack 5 no longer do auto-polyfilling for node core modules. To fix this issue one workaround is to install assert by doing `npm i assert` or downgrading react-scripts to 4.0.3

**Comment by AlberErre** [comment]
Yes, @Apra487  this issue has been documented on (#1320).

Take into account you need to install all the missing polyfills, such as `buffer`, ...etc. Not just `assert`. 
 
The easiest workaround is taking a rollback to `webpack 4`, using `react-scripts 4.0.3` as you suggested.
