### ISSUE TITLE
Incompatible with windows 11

### ISSUE THREAD

**Issue by hippiemeraki** [project-serum/anchor#1319]
**I ran though this code for installation :**
 cargo install --git https://github.com/project-serum/anchor --tag v0.20.1 anchor-cli --locked

**After a while it throws me this Error!**

error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `C:\Users\user\AppData\Local\Temp\cargo-installFIAv7a\release\build\ring-48b5c8223ff50bc3\build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

  --- stderr
  running "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oC:\\Users\\user\\AppData\\Local\\Temp\\cargo-installFIAv7a\\release\\build\\ring-1a40152b80392b70\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"
  thread 'main' panicked at 'failed to execute ["gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-g3" "-DNDEBUG" "-c" "-oC:\\Users\\user\\AppData\\Local\\Temp\\cargo-installFIAv7a\\release\\build\\ring-1a40152b80392b70\\out\\aes_nohw.o" "crypto/fipsmodule/aes/aes_nohw.c"]: The system cannot find the file specified. (os error 2)', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\ring-0.16.20\build.rs:653:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.20.1 (https://github.com/project-serum/anchor?tag=v0.20.1#a81ff88d)`, intermediate artifacts can be found at `C:\Users\user\AppData\Local\Temp\cargo-installFIAv7a`

Caused by:
  build failed

**Comment by fanatid** [comment]
Try with target `x86_64-pc-windows-msvc` instead of `x86_64-pc-windows-gnu`

**Comment by RushiChandalia** [comment]
> Try with target `x86_64-pc-windows-msvc` instead of `x86_64-pc-windows-gnu`

how to do it?

**Comment by fanatid** [comment]
`rustup target --help`
`cargo build --help`

**Comment by fanatid** [comment]
Closed due to issue creator inactivity.
