### ISSUE TITLE
Error Deploying Hello, World & Basic-0 Example App

### ISSUE THREAD

**Issue by topherPedersen** [project-serum/anchor#1333]
I keep running into the same error on two different MacBook Pros (1 with Intel Chip, 1 with M1 Chip) when attempting to deploy the Basic-0 example app as well as the default starter template which is created when running $ anchor init hello-world. Everything seems to go okay until I get to:

$ anchor deploy

Then I keep getting an error which reads:

Deploying workspace: http://localhost:8899
Upgrade authority: /Users/christopherpedersen/.config/solana/id.json
Deploying program "hello-world"...
Program path: /Users/christopherpedersen/Desktop/hello-world/target/deploy/hello_world.so...
Error: RPC request error: cluster version query failed: error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 61)
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.
christopherpedersen@TophersMacbookPro13 hello-world % 

NOTE: I am running the solana-test-validator when attempting to deploy.

**Comment by topherPedersen** [comment]
I ended up getting this to work on my second MacBook Pro. Not sure exactly what was going on with my Intel based MacBook Pro. But when I followed all of the instructions again on my newer (but slower) M1 MacBook Pro everything worked fine. I just had to make sure the test validator program was running when I went to deploy:

$ solana-test-validator

**Comment by TikiCat7** [comment]
what version is your solana on your M1? I'm having issues deploying to localnet on my M1 mac 😢
