### ISSUE TITLE
InvalidDigit error at anchor build

### ISSUE THREAD

**Issue by AuroraLantean** [project-serum/anchor#1335]
when building from my solana program, I got this error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', lang/syn/src/idl/mod.rs:143:76
`
But after updating my Anchor from 0.18.2 to 0.20.1, that error went away, although my Solana anchor-lang and anchor -spl are still in 0.18.2 ! 
Could you make some checking or more clear error messages? Thank you

**Comment by fanatid** [comment]
> But after updating my Anchor from 0.18.2 to 0.20.1

After updating anchor cli?

If there is no error with 0.20.1 what is the problem then?

**Comment by AuroraLantean** [comment]
Ok there is no problem for the Anchor 0.20.1
