### ISSUE TITLE
Can't get home directory path: environment variable not found

### ISSUE THREAD

**Issue by coruscateor** [project-serum/anchor#1337]
hey, I'm following the book and I'm a quarter of the way down when it first wants me to compile and I get this:

PS F:\SoftwareProjects\Rust\tic-tac-toe\programs\tic-tac-toe> anchor build
BPF SDK: \\?\C:\Users\Paul\.local\share\solana\install\releases\1.9.4\solana-release\bin\sdk\bpf
Can't get home directory path: environment variable not found

relevant details:

PS F:\SoftwareProjects\Rust\tic-tac-toe\programs\tic-tac-toe> solana --version
solana-cli 1.9.4 (src:8ce65878; feat:3258470607)

PS F:\SoftwareProjects\Rust\tic-tac-toe\programs\tic-tac-toe> yarn --version
1.22.4

PS F:\SoftwareProjects\Rust\tic-tac-toe\programs\tic-tac-toe> rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)

PS F:\SoftwareProjects\Rust\tic-tac-toe\programs\tic-tac-toe> anchor --version
anchor-cli 0.20.1

does anyone have any idea what I should do?

this is on Windows 10 x64

Also I got this:

PS F:\SoftwareProjects\Rust> anchor init tic-tac-toe
Error: yarn install failed: The system cannot find the file specified. (os error 2)

When I created the project

**Comment by aayush-mittal9** [comment]
Hey, I am currently facing the same issue. Did you resolve it yet?

**Comment by baltarifcan** [comment]
`set HOME=C:\Users\<username>` seems to do the trick for the env variable part
 (W11 x64)

**Comment by fanatid** [comment]
Thanks, @baltarifcan! I'll close the issue then.

**Comment by Akshay-Anand-Code** [comment]
> set HOME=C:\Users\

Thank you, it worked. Also, don't the solana smart contracts take really long time to build? I have a simple hello world program and it shows 350 Mib and 50 mins. Have you had a similar experience
![sbf](https://user-images.githubusercontent.com/85056404/215018835-132dfa7e-624a-4704-95ff-5565ae5257d1.png)
?

**Comment by DORTROX** [comment]
> > set HOME=C:\Users\
> 
> Thank you, it worked. Also, don't the solana smart contracts take really long time to build? I have a simple hello world program and it shows 350 Mib and 50 mins. Have you had a similar experience ![sbf](https://user-images.githubusercontent.com/85056404/215018835-132dfa7e-624a-4704-95ff-5565ae5257d1.png) ?
Thats cargo installing platform-tools, It seems it was the first time you ran the build command.

**Comment by Rizary** [comment]
> `set HOME=C:\Users\<username>` seems to do the trick for the env variable part (W11 x64)

this doesn't work on my end.. I'm using Win111

**Comment by DORTROX** [comment]
> > `set HOME=C:\Users\<username>` seems to do the trick for the env variable part (W11 x64)
> 
> this doesn't work on my end.. I'm using Win11

Set it inside your system variables with the name of user account, also make sure to restart your cmd.
![image](https://github.com/coral-xyz/anchor/assets/78467470/461cf280-53ae-41a1-98f7-ac82804c5a2d)
![image](https://github.com/coral-xyz/anchor/assets/78467470/5a08f225-3ff6-4f7e-8df5-bd430c0e60c9)

**Comment by Rizary** [comment]
> > > `set HOME=C:\Users\<username>` seems to do the trick for the env variable part (W11 x64)
> > 
> > 
> > this doesn't work on my end.. I'm using Win11
> 
> Set it inside your system variables with the name of user account, also make sure to restart your cmd. ![image](https://private-user-images.githubusercontent.com/78467470/331312437-461cf280-53ae-41a1-98f7-ac82804c5a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjk2NDQsIm5iZiI6MTcxNTkyOTM0NCwicGF0aCI6Ii83ODQ2NzQ3MC8zMzEzMTI0MzctNDYxY2YyODAtNTNhZS00MWExLTk4ZjctYWM4MjgwNGM1YTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDkxMWQzY2Y3ZjUyM2MzY2NjNzU1MzhkMjM5NzhlMDU3YTUxZmRhMWFhM2Y5NWQ0YTZlM2QwYTY3ODg5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTdrKsbbSWVymKuoZjvG9Jjz3du1fo8DNv-jcL1wR8Y) ![image](https://private-user-images.githubusercontent.com/78467470/331313273-5a08f225-3ff6-4f7e-8df5-bd430c0e60c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjk2NDQsIm5iZiI6MTcxNTkyOTM0NCwicGF0aCI6Ii83ODQ2NzQ3MC8zMzEzMTMyNzMtNWEwOGYyMjUtM2ZmNi00ZjdlLThkZjUtYmQ0MzBjMGU2MGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjk0MDM4MzZlODIxMmY1OGMwY2I4YTFiZThhODFiMmFjM2Y2ODJkZTNlYjRmMjU3ZGZkYTQ3YTA3Y2ZlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jgh5H5ARfSrsLmGd-zamAtD097RITN17ux7ljENhQl0)

I got the following error when running `anchor build`

![image](https://github.com/coral-xyz/anchor/assets/7221768/4c46c84b-c80d-4b18-afef-b6a31c4122b5)

**Comment by Shradhesh71** [comment]
Hey @Rizary, I am currently facing the same **issue**. Did you resolve it yet?

**Comment by CryptoNinja0331** [comment]
> `set HOME=C:\Users\<username>` seems to do the trick for the env variable part (W11 x64)

should I use this command on Powershell?

**Comment by baltarifcan** [comment]
> > `set HOME=C:\Users\<username>` seems to do the trick for the env variable part (W11 x64)
> 
> should I use this command on Powershell?

@CryptoNinja0331 that syntax is for cmd. For powershell you should use;

$Env:HOME = "C:\Users\<username>"

**Comment by mohakchakraborty2004** [comment]
@aekiratli were you able to solve this ? I am also facing similar issue 

![Image](https://github.com/user-attachments/assets/af708474-e047-40e4-abc7-c5ad1f244edf)

**Comment by aekiratli** [comment]
> [@aekiratli](https://github.com/aekiratli) were you able to solve this ? I am also facing similar issue
> 
> ![Image](https://github.com/user-attachments/assets/af708474-e047-40e4-abc7-c5ad1f244edf)

It has been a while so I do not exactly remember but I should have given up and worked on my mac instead of windows
