### ISSUE TITLE
anchor typescript is not supported in 0.20.1

### ISSUE THREAD

**Issue by jeff0723** [project-serum/anchor#1339]
this command `anchor init --typescript myapp ` is not recognized by anchor in 0.20.1. 

```
error: Found argument '--typescript' which wasn't expected, or isn't valid in this context

	If you tried to supply `--typescript` as a value rather than a flag, use `-- --typescript`

USAGE:
    anchor init [FLAGS] [OPTIONS] <NAME>
```

**Comment by nibbus0x** [comment]
I think typescript is the default. If you run `anchor init myapp` you should get a typescript project.

**Comment by callensm** [comment]
As @nibbus0x said, Typescript is now the default configuration for new executions of `anchor init`. The `--typescript` flag was replaced by the `-j/--javascript` flag to disable Typescript as the default.
