### ISSUE TITLE
 Anchor test not a directory

### ISSUE THREAD

**Issue by 19-xiaogao** [project-serum/anchor#1344]
I trying to run **anchor test**  , But an error:

BPF SDK: /Users/xxx/saftware/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: rustup toolchain link bpf /Users/xxx/saftware/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
error: not a directory: '/Users/xxx/saftware/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'

**Comment by fanatid** [comment]
It is not an anchor issue. Most probably you have corrupted solana tool suite due to an update. You need to remove the tool suite completely and reinstall it. At least these directories, maybe some others too:
- `~/.cache/solana/`
- `~/.local/share/solana`

**Comment by 19-xiaogao** [comment]
Thanks for your reply。

**Comment by shubhraagarwal** [comment]
> You need to remove the tool suite completely and reinstall it

How do I remove the suite?
