### ISSUE TITLE
Zero copy deserialization

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#135]
Explore adding a zero-copy deserialization feature that can be opted into instead of using borsh.

**Comment by armaniferrante** [comment]
Not having this is the main reason I can think of that someone wouldn't use Anchor. Bumping to P1.

**Comment by armaniferrante** [comment]
Addressed by #202.

**Comment by dzmitry-lahoda** [comment]
Is that zero copy based on structs references as API to state or traits?  Is it borsh compatible in binary format? Does it works on non x86 cpus? how it works with growing stuctrues?  and just wire this to other stuff https://github.com/solana-labs/solana/issues/13391#issuecomment-815553048

**Comment by armaniferrante** [comment]
Zero copy here directly re-interprets the bytes from the AccountInfo's `&mut [u8]` as a `Ref` or `RefMut` of the zero-copy data structure, where all fields are POD types. 

More specifically the account struct must implement `pub trait ZeroCopy: Discriminator + Copy + Clone + bytemuck::Zeroable + bytemuck::Pod {}`. 

Growing structures aren't currently supporrted, and it's not necessarily borsh compatible in binary format (though some subset of things conveniently are, like arrays and structs), and there's no expectation it works on non x86 cpus.
