### ISSUE TITLE
Compile time warning whenever AccountInfo or UncheckedAccount is used

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1387]
We should emit warnings from `anchor build` whenever these types are used. To suppress the warnings, a special comment can be added. For example, `SAFETY: ` or `CHECK: `, as is commonly done with unsafe code in rust.

**Comment by acamill** [comment]
What's the best practice for CPI to non anchor program? 
- UncheckedAccount
- AccountInfo
- Account with wrappers, although checked at the final destination... ?

**Comment by armaniferrante** [comment]
`Account` with wrappers is my preferred solution. See how we do this for the spl token program and others here https://github.com/project-serum/anchor/blob/master/spl/src/token.rs.

**Comment by Flaque** [comment]
If not `AccountInfo`, what's the best way to refer to a PDA? 

ie, is this bad? 
```rust
#[account(
  init,
  payer=user,
  token::mint = mint,
  token::authority = escrow_authority,
)]
pub escrow: Account<'info, TokenAccount>,

#[account(
  seeds=[b"authority", escrow.key().as_ref()],
  bump=escrow_authority_bump,
)]
pub escrow_authority: AccountInfo<'info>,
```

**Comment by armaniferrante** [comment]
You can use `SystemAccount<'info>` to refer to an account owned by the system program.

**Comment by Flaque** [comment]
> then a simple // CHECK: comment would be sufficient with UncheckedAccount. Since the seeds constraint will assert it is the correct address.

I might be confused here. What's the difference between an `UncheckedAccount` and an `AccountInfo`? Why would be using either be bad? (other than not having the underlying data?)

**Comment by armaniferrante** [comment]
`UncheckedAccount` is a more accurate alias of `AccountInfo`. Other types, e.g., `Account<T>` have additional checks on them, for example, the owner and the type of data, which make them a safer alternative. If you use `UncheckedAccount`, you need to manually do such account checks on your own.

**Comment by Flaque** [comment]
Ah, then can I make a request that `UncheckedAccount` doesn't error or warn? If it does, it might discourage folks from creating composable programs.

For example, if SPL Token's `owner` field was required to be a `SystemAccount`, then most programs wouldn't be feasible to be built, because you couldn't make the owner a program. 

But also, I dunno anything and I might be thinking about this wrong.
