### ISSUE TITLE
Allow anchor build/deploy to be given a keypair for the programid.

### ISSUE THREAD

**Issue by akutruff** [project-serum/anchor#1394]
Right now `anchor build` and `anchor deploy` generate a keypair in the `target` directory.  This prevents being able to generate consistent program id's across different environments.  

Suggest adding something like:
`anchor build --program-keypair <keypair.json>` and `anchor deploy --program-keypair <keypair.json>`
Which will use the provided keypair and not generate a file in the `target` directory.

**Comment by callensm** [comment]
This new argument would need to be only allowed if `--program-name` is specified, otherwise `anchor build` and `anchor deploy` act on all workspace programs.
