### ISSUE TITLE
Cannot construct `Wallet`

### ISSUE THREAD

**Issue by acheroncrypto** [project-serum/anchor#1397]
```js
import { web3, Wallet } from "@project-serum/anchor";

const wallet = new Wallet(web3.Keypair.generate());
```

The error I get is: `This expression is not constructable. Type 'NodeWallet' has no construct signatures.`

`"@project-serum/anchor": "^0.20.1"`

**Comment by fanatid** [comment]
Try this:
```js
const { Wallet } = require("@project-serum/anchor");
const wallet = new Wallet(web3.Keypair.generate());
```

**Comment by acheroncrypto** [comment]
Thank you, it used to work on previous versions of anchor. Is there an important reason why `require` works but `import` doesn't? Or is it one of those weird JS things?

**Comment by acheroncrypto** [comment]
#1363 fixes this backwards compatibility issue but packages haven't been updated yet.
