### ISSUE TITLE
unrecognized signer source upon creating a token...

### ISSUE THREAD

**Issue by Meloneat** [project-serum/anchor#1401]
With common setting following the steps to create a SPL token in https://spl.solana.com/token#example-creating-your-own-fungible-token, but get a error stunning me several days named unrecognized signer source.
Anyone could give me some suggestions to resolve the problem?

**Comment by fanatid** [comment]
How is this related to Anchor?

**Comment by paul-schaaf** [comment]
doesnt seem to be. closing this.
