### ISSUE TITLE
How to split program into multiple files?

### ISSUE THREAD

**Issue by tuphan-dn** [project-serum/anchor#1433]
For better dev exp, I would like to split the program into multiple files. In each file, they will take care of a single task or function. For example:

```rust
// lib.rs

#[program]
mod foo {
  use super::*;
  pub fn initialize(_ctx: Context<Initialize>) -> ProgramResult {
    Ok(())
  }
}

#[derive(Accounts)]
pub struct Initialize {}
```

To something like:

```rust
// initialize.rs

pub fn initialize(_ctx: Context<Initialize>) -> ProgramResult {
  Ok(())
}

#[derive(Accounts)]
pub struct Initialize {}
```

```rust
// lib.rs

pub mod initialize;

#[program]
mod foo {
  use super::*;
  pub use initialize::initialize;
}
```

How can I organize Anchor like that?

**Comment by armaniferrante** [comment]
Put the program macro in a single file and call out to handlers providing the implementation. See https://github.com/jet-lab/jet-v1/ for an example.

**Comment by tuphan-dn** [comment]
appreciate that
