### ISSUE TITLE
TS: Builder API types are cascaded as any after .method call.

### ISSUE THREAD

**Issue by kevinrodriguez-io** [project-serum/anchor#1434]
```ts
const result = await program.methods
      .makeConnection(to)
      .accounts({
        from,
        systemProgram: anchor.web3.SystemProgram.programId,
      })
      .signers([fromWallet.payer])
      .rpc();
```

.accounts is cascaded as any, breaking completion.

<img width="386" alt="Screen Shot 2022-02-10 at 22 12 33" src="https://user-images.githubusercontent.com/6248571/153536569-79f6d2f3-b1a0-492a-adce-37c47ed3ae71.png">

**Comment by Eliascm17** [comment]
I am also experiencing this. Might just stick to the `Instruction` namespace until this is fixed.
