### ISSUE TITLE
`account.close()` is not safe to call directly

### ISSUE THREAD

**Issue by billythedummy** [project-serum/anchor#1437]
`account.close()` is not safe to call in the program since it does not actually result in the `CLOSED_ACCOUNT_DISCRIMINATOR` being written to the account data if an account is only decorated with `#[mut]` and not `#[close]`.

This is because `#[mut]` without `#[close]` generates 
```
anchor_lang::AccountsExit::exit(&self.account, program_id)?;
```

instead of 

```
anchor_lang::AccountsClose::close(&self.account, self.destination.to_account_info())?
```

`AccountsExit::exit()` then calls `account.try_serialize()` at the end of the instruction, which writes the account discriminator to `data` every time, therefore overwriting any changes to change it to `CLOSED_ACCOUNT_DISCRIMINATOR` by any `account.close()` calls in the program. 

This prevents anchor programs from safely closing accounts conditionally in instructions.

**Proposed solutions:**

1. If anchor does not wish to support conditional closing of accounts in instructions, document that `close()` is not meant to be called manually, and that only the `#[close]` decorator is safe.
2. Otherwise, I suggest changing the codegen such that the discriminator is only written on `init`, and subsequent writes only write the struct data. Not sure what the best way to structure this is but I'm thinking a new trait `AnchorInit` with a `init()` function that writes the discriminator and calls a modified `try_serialize()` that only writes the struct data.

P.S. Can't wait for solana 1.9.0 to drop so that we can just change the `close()` impl to realloc data to 0 and not worry about all this.

**Comment by armaniferrante** [comment]
The work for writing the discriminator only on `init` (and `zero`) is being done as part of https://github.com/project-serum/anchor/pull/1415.

**Comment by paul-schaaf** [comment]
`.close` is only meant as an internal function which we are unfortunately not able to hide.

As armani mentioned, 2) will be added soon in some way.

That said, we shouldve definitely documented it. Thanks for reporting this!

**Comment by paul-schaaf** [comment]
documentation has been added to the function so Im closing this
