### ISSUE TITLE
cli: anchor idl fetch should work outside workspaces

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1453]

**Comment by NBNARADHYA** [comment]
@paul-schaaf @armaniferrante I would like to take on this issue! Could you please elaborate more on this ?

**Comment by paul-schaaf** [comment]
anchor idl fetch fetches an idl from the chain and you have the option to save it to a file with the `-o myFile.json` option. 

but currently you can only do this from inside a workspace. so if youre just interestrd in getting an idl you have to create a temporary workspace cd into it and then call it from there. afterwards you can delete the temp workspace. this shouldnt be necessary. you should be able to call it from anywhere

**Comment by paul-schaaf** [comment]
yes exactly!

theres already an option to choose the cluster. e.g. `--provider.cluster mainnet`. but again, this currently only works if youre inside a workspace

**Comment by NBNARADHYA** [comment]
@paul-schaaf Thanks for the clarification! I am on it!
