### ISSUE TITLE
cli: mocha test template should use program.methods not program.rpc

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1463]

**Comment by NBNARADHYA** [comment]
Hi @armaniferrante I would like to work on this issue. Could you please provide more context here ?

**Comment by armaniferrante** [comment]
The api used in the template should use `program.methods` API instead of `program.rpc`, which is older and will be eventually deprecated.

**Comment by paul-schaaf** [comment]
closed by #1732
