### ISSUE TITLE
Writing unit tests in Rust

### ISSUE THREAD

**Issue by fade2black** [project-serum/anchor#1474]
I'm new to Solana programming. I've generated a new project using Anchor. It's created a test folder containing a single typescript file.

1) Can I write unit tests in pure Rust and where should put my tests under the Anchor project? 
2) Is knowledge typescript/javascript (*.js framaworks) must in order to write programs using Anchor? Almost all examples/tutorials/projects on Github contain js files.

**Comment by armaniferrante** [comment]
1. Yes. You can use the solana program_test tool kit for integration tests. See the solana docs for that (unfortunately I dont have a link off hand). If you can't find, try asking in discord.
2. No. You can use rust only if you want.
