### ISSUE TITLE
cli: also clone program data account whenever a bpf3 program is given in [test.validator.clone] in Anchor.toml file

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1481]

**Comment by skrrb** [comment]
should the solana rpc endpoint of the validator be a mandatory field? If not, which one should be used to get the account data to check if it's a program?

https://github.com/project-serum/anchor/blob/a604f8595c875a23b8e13c8569577d6a6b1c79bd/cli/src/config.rs#L565

**Comment by tomlinton** [comment]
Yes it's mandatory. The validator will fail to start if a clone is address is passed without the URL. It'd be nice if Anchor caught that without needing to open the validator log to see it.

**Comment by paul-schaaf** [comment]
@tomlinton is `[test.validator.url]` the cluster that the test validator is deployed to or is that the cluster the accounts are cloned from?

**Comment by tomlinton** [comment]
The URL that the accounts are cloned from. It's directly passed to `solana-test-validator`.
