### ISSUE TITLE
anchor 0.22.0 - missing error code information in idl

### ISSUE THREAD

**Issue by niponchi** [project-serum/anchor#1494]
With `anchor 0.22.0` - Error code information is missing from idl file. Failed rpc call in typescript returns error as `Error processing Instruction 0: custom program error: 0x189c`, instead of readable error message `6300: You are not authorized to perform this action.`

Given the following ErrorCode enum
```rust
#[error_code]
pub enum ErrorCode {
    #[msg("You are not authorized to perform this action.")]
    Unauthorized = 300,
}
```

with `anchor 0.22.0`

```json
{
  "version": "0.1.0",
  "name": "error_code",
  "instructions": [
    {
      "name": "initialize",
      "accounts": [],
      "args": []
    }
  ],
  "types": [
    {
      "name": "ErrorCode",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Unauthorized"
          }
        ]
      }
    }
  ]
}
```

`anchor 0.21.0`
```json
{
  "version": "0.1.0",
  "name": "error_code",
  "instructions": [
    {
      "name": "initialize",
      "accounts": [],
      "args": []
    }
  ],
  "errors": [
    {
      "code": 6300,
      "name": "Unauthorized",
      "msg": "You are not authorized to perform this action."
    }
  ]
}
```

**Comment by paul-schaaf** [comment]
can u send a link to your repo? Our own tests for error msgs all pass.

**Comment by yasushisakai** [comment]
This happened to me when I was trying to update the `project-serum/multisig` program. https://github.com/yasushisakai/multisig/tree/bump_v0.22.0

The generated idl looks like what is reported above; without the `code` and `msg` fields. (the test failed for this matter?)
<details>

```json
      "name": "ErrorCode",
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "InvalidOwner"
          },
          {
            "name": "InvalidOwnersLen"
          },
          {
            "name": "NotEnoughSigners"
          },
          {
            "name": "TransactionAlreadySigned"
          },
          {
            "name": "Overflow"
          },
          {
            "name": "UnableToDelete"
          },
          {
            "name": "AlreadyExecuted"
          },
          {
            "name": "InvalidThreshold"
          },
          {
            "name": "UniqueOwners"
          }
        ]
      }
 ```

</details>

**Comment by tomlinton** [comment]
That works fine for me, but what you describe is exactly the output if I run against the `master` branch instead of `bump_v0.22.0` (without [this change](https://github.com/yasushisakai/multisig/commit/d1d2cdac7301c3fcde333c09b190782edd2edc72#diff-83aaf840f5059217ce44eb4d82fdd90455990034b7aee2baab7ad1ec90dde43eR316)). I also get the incorrect output if I use 0.21.0, so I think you are probably running against the wrong branch or using the wrong verison?

**Comment by yasushisakai** [comment]
@tomlinton @paul-schaaf yes, thanks if was the case that `anchor --version` was `0.21.0`. 

A different issue though, `avm list` showed that I was using `0.22.0` but `which anchor` was pointing to the `npm` bin directory. After deleting the npm one, it correctly used the one installed by `avm`. Checking `which anchor` confirmed this case. Thanks again

**Comment by tomlinton** [comment]
No problem, glad it was solved! 

In the book it recommends [uninstalling the npm version](https://book.anchor-lang.com/chapter_2/installation.html#installing-using-anchor-version-manager-avm) for that reason, whichever is highest in your `PATH` will take precedence and it may not necessarily be avm.

**Comment by niponchi** [comment]
> Maybe youve updated the code to `0.22.0` but not your cli?

this solved my case. totally forgot about the cli version. thanks for the help.
