### ISSUE TITLE
cli: log unresolved account name

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#1496]
The error message here is not that helpful. We should log the account symbol `comp_f.symbol` that is not found https://github.com/project-serum/anchor/blob/master/lang/syn/src/idl/file.rs#L516-L518.

**Comment by migui3230** [comment]
ill take this one on too!

**Comment by migui3230** [comment]
does anchor use a logging library or do you want the variable to just be printed? @armaniferrante

**Comment by armaniferrante** [comment]
> does anchor use a logging library or do you want the variable to just be printed? @armaniferrante

Print is good for now.

**Comment by migui3230** [comment]
#1506

**Comment by migui3230** [comment]
#1506

**Comment by paul-schaaf** [comment]
closed by #1506
