### ISSUE TITLE
Multiple subdirectories that have the same rust file name result in accounts not being picked up "Could not resolve Accounts symbol"

### ISSUE THREAD

**Issue by ChewingGlass** [project-serum/anchor#1499]
Consider the following directory structure:

```
src
   instructions
      instruction_one
         account.rs
      instruction_two
         account.rs
```

This will result in

```
Could not resolve Accounts symbol, lang/syn/src/idl/file.rs:518:22
```

This is reproducible via https://github.com/StrataFoundation/strata/tree/6b933f8707cb495347af52ec200daee7a5e123ae/programs/spl-token-bonding

**Comment by tomlinton** [comment]
I believe https://github.com/project-serum/anchor/pull/1343 will fix this. I tested it with your repro and it generates this IDL (I did not validate this against your source though): https://gist.github.com/tomlinton/44a80e970aae5883994ab3267cd9e582

**Comment by tomlinton** [comment]
#1343 was merged so this should be closed.
