### ISSUE TITLE
lang: API for creating program derived addresses with instruction data

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#150]
Using program derived addresses for account data is cumbersome.  One has to

* allocate space for the account, manually adding `8+` for the account discriminator
* invoke the system program's create account method
* deserialize the data after the account has been created
* manually persist the newly created account (after initializing it)

An example of this taken from https://github.com/project-serum/anchor/pull/86/files#diff-20d471b8d1707e332b0dd96fe3ef98601ff2511362e4eeb3a94ff3c921a797edR167:

```rust 
        // Create account manually.
        let mut vote: ProgramAccount<Vote> = {
            // First create the vote account.
            //
            // Add 8 for the account discriminator.
            let space = 8 + Vote::default().try_to_vec().unwrap().len();
            let lamports = ctx.accounts.rent.minimum_balance(space);
            let ix = solana_program::system_instruction::create_account(
                ctx.accounts.stake.beneficiary.key,
                ctx.accounts.vote.key,
                lamports,
                space as u64,
                ctx.program_id,
            );
            let seeds = [
                ctx.accounts.poll.to_account_info().key.as_ref(),
                ctx.accounts.stake.member.to_account_info().key.as_ref(),
                &[nonce],
            ];
            let signer = &[&seeds[..]];
            solana_program::program::invoke_signed(
                &ix,
                &[
                    ctx.accounts.stake.beneficiary.clone(),
                    ctx.accounts.vote.clone(),
                    ctx.accounts.system_program.clone(),
                ],
                signer,
            )?;
            // Deserialize the newly created account into an object.
            ProgramAccount::try_from_init(&ctx.accounts.vote)?
        };

        // Do any initialization here.
        ...

        // Manually persist changes since we manually created the account.
        vote.exit(ctx.program_id)?;
```

There should be an api or some codegen to make this more friendly. 

For example

```rust
// The seeds can be taken from any of the input parameters to `create_my_account`.
#[program_derived_address([seeds, go, here])]
fn create_my_account(ctx: Context<MyAccounts>, uninitalized_account: ProgramAccount<Vote>) {
   // Initialization here.
}
```

**Comment by NorbertBodziony** [comment]
We can expand already existing `init` flag by `associated` that will indicate that this account will be created from seed.
e.g.
```#[derive(Accounts)]
pub struct CreateExchangeAccount<'info> {
    #[account(init,associated)]
    pub exchange_account: ProgramAccount<'info, ExchangeAccount>,
    pub rent: Sysvar<'info, Rent>,
}

**Comment by Standaa** [comment]
I agree with Norbert. I think expanding the init flags shows intent with more clarity and is more in-line with the existing patterns.

**Comment by armaniferrante** [comment]
I like the idea of an associated attribute. One limitation is that the attribute inside the `#[derive(Accounts)]` struct doesn't have access to the instruction input parameters, which one might want to use as seeds.

However, we can limit the scope of `associated` to be more inline with the associated token program. I.e., associated means account that's a function of program_id + owner.

So the attribute becomes 

```
pub struct CreateExchangeAccount<'info> {
    #[account(init, associated = authority)]
    pub exchange_account: ProgramAccount<'info, ExchangeAccount>,
    #[account(signer)]
    pub authority: AccountInfo<'info>
    pub rent: Sysvar<'info, Rent>,
}
```

**Comment by armaniferrante** [comment]
Moving the associated attribute to a separate issue https://github.com/project-serum/anchor/issues/185.

**Comment by armaniferrante** [comment]
Perhaps a more elegant solution the one originally proposed here is to extend the `#[state]` concept to generate arbitrary program derived addresses. We can do this with a new macro, `#[program_derived_address]` attribute, where the constructor returns two things: 1) the initial state of the account, and 2) the seeds for the program derived address. This will allow one to generate pda accounts where seeds can also be function arguments (one of the limitations of the current `associated` attribute). 

```
#[program_derived_address]
pub struct MyProgramDerivedAddress {
 ....
}

impl MyProgramDerivedAddress {
  pub fn new(ctx: Context<Ctor>, input_data: u8) -> Result<(Self, Seeds)> {
     
  }
}
```

**Comment by dzmitry-lahoda** [comment]
why seed is by ref `&u8`?

**Comment by armaniferrante** [comment]
`input_data` is by ref because the return value needs to be a slice, which has a lifetime. If you want `input_data` to be usable in the slice that's returned, its lifetime must be valid for the return value. In the example, here, rust will elide the lifetimes making them the same (though I haven't compiled this so I could be missing an edge case). 

If the user doesn't want to use `input_data` as a seed, it could just omit the reference, and the macro codegen should be able to figure out what to do.

**Comment by armaniferrante** [comment]
An additional feature mentioned a couples times on discord, is that it would be desireable for one to specify static strings in the pda seeds.

**Comment by armaniferrante** [comment]
The API that I"ve landed on for the first version of this feature will look like this.

```rust
#[derive(Accounts)]
#[instruction(domain: String)]
pub struct TestPdaInit<'info> {
    #[account(init, seeds = [b"my-seed", domain.as_bytes()], payer = my_payer)]
    my_pda: ProgramAccount<'info, DataU16>,
    my_payer: AccountInfo<'info>,
    rent: Sysvar<'info, Rent>,
    system_program: AccountInfo<'info>,
}
```

Where we extend the `seeds` attribute to create a program derived address if the `init` argument is present.

Note that one must specifyh `#[instruction(<args>)]` to access instruction arguments in the scope of the `Accounts` derive.

**Comment by armaniferrante** [comment]
Done by #386.
