### ISSUE TITLE
module not found: error : cant resolve 'path', 'asset', 'process' ...

### ISSUE THREAD

**Issue by supernftier** [project-serum/anchor#1516]
I install @porject-serum on my react project, but above 9 errors appeared when to compile

this is package.json file of my project, please help me

{
  "name": "Others",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@solana/spl-token": "^0.1.8",
    "@solana/wallet-adapter-base": "^0.6.0",
    "@solana/wallet-adapter-react": "^0.12.5",
    "@solana/wallet-adapter-react-ui": "^0.5.1",
    "@solana/wallet-adapter-wallets": "^0.10.1",
    "@solana/web3.js": "^1.29.2",
    "@metaplex/js": "^3.0.0",
    "@project-serum/anchor": "0.17.1-beta.1",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^13.5.0",
    "bootstrap": "^5.1.3",
    "react": "^17.0.2",
    "react-bootstrap": "^2.1.2",
    "react-dom": "^17.0.2",
    "react-icons": "^4.3.1",
    "react-scripts": "^5.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/jest": "^27.4.1",
    "@types/node": "^17.0.21",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "typescript": "^4.5.5"
  }
}

**Comment by tomlinton** [comment]
This is related to webpack 5 no longer including node polyfills by default, see e.g. https://github.com/facebook/create-react-app/issues/11756 for discussion and solutions.

**Comment by fanatid** [comment]
@supernftier you need yo override webpack config, something like this:
```js
const webpack = require('webpack');

module.exports = function (config, env) {
  return {
    ...config,
    plugins: [
      ...config.plugins,
      new webpack.ProvidePlugin({
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
      }),
    ],
    resolve: {
      ...config.resolve,
      fallback: {
        assert: require.resolve('assert'),
        buffer: require.resolve('buffer'),
        stream: require.resolve('stream-browserify/'),
      },
    },
  };
};
```
