### ISSUE TITLE
Tests fail unless --skip-lint flag is set

### ISSUE THREAD

**Issue by schwarzbi3r** [project-serum/anchor#1517]
#1452 adds the requirement for documentation whenever AccountInfo is used, which breaks a large number of tests unless you run them with `--skip-lint` set

Does it make sense to upgrade these tests to pass without `--skip-lint` by adding the required documentation (i.e. `/// CHECK: ...`)?

**Comment by armaniferrante** [comment]
These tests aren't supposed to be secure programs but are testing specific behaviors. So for many of these, no, this doesn't make sense because they are in fact insecure.

**Comment by schwarzbi3r** [comment]
Yeah, I can see the point that these aren't expected to be secure programs, nor the best practices, but on the other side I'd argue that tests shouldn't be excluded from linting because the cost is low and it always feels a bit unhygienic to have tests that require a special flag to run.

Having said that, I appreciate the reasoning and quick clarification. Thanks!
