### ISSUE TITLE
cli: rename `[test.validator.url]`

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1518]
this field is used to tell the validator which cluster to clone accounts from but its name does not indicate that.
It looks like it's the field that configures which cluster the validator is started on.

So we should adjust the name.

`clone_url`, `clone_from`, `clone_cluster`

**Comment by tomlinton** [comment]
All the [test.validator.*] fields are [one to one ](https://github.com/project-serum/anchor/blob/master/cli/src/config.rs#L537-L580) mappings to arguments of `solana-test-validator`.

I think it makes it easier to understand when you can do `solana-test-validator --help` and then configure it as you want by adding the required [test.validator.*] field in your Anchor.toml.

**Comment by armaniferrante** [comment]
I'm in favor of keeping the mapping one to one.

**Comment by paul-schaaf** [comment]
ok we should add that info to the anchor.toml reference. https://github.com/project-serum/anchor-book/issues/20
