### ISSUE TITLE
Anchor Init template still uses ProgramResult instead of the newer Result

### ISSUE THREAD

**Issue by SkullTech** [project-serum/anchor#1526]
#1462 introduced `Result` as a replacement of `ProgramResult`. But the `anchor init` template is not updated according to that change. It still spits out the following code

```
use anchor_lang::prelude::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod coolapp {
    use super::*;
    pub fn initialize(ctx: Context<Initialize>) -> ProgramResult {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

**Comment by tomlinton** [comment]
This was fixed in https://github.com/project-serum/anchor/commit/99403bff7e76deaa818e07bf00f2d9d7236070c1

**Comment by paul-schaaf** [comment]
^ closing this.
