### ISSUE TITLE
Script to automatically bump versions for entire repo

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#153]
Bumping versions should be automated. E.g., all changes here https://github.com/project-serum/anchor/commit/e10f4328b3b9dc016a99616fc63e4f2fa4d816c0.

**Comment by WrRaThY** [comment]
hey
bumping is one thing - imo secondary.
is there any newsletter / news feed where we can subscribe to receive information about updates?
at least in my personal experience - if I received an email/notification on discord - I would probably stop asking you stupid questions on discord which you answer simply by "it was introduced in version X, released 2 days ago"

**Comment by armaniferrante** [comment]
> hey
> bumping is one thing - imo secondary.
> is there any newsletter / news feed where we can subscribe to receive information about updates?
> at least in my personal experience - if I received an email/notification on discord - I would probably stop asking you stupid questions on discord which you answer simply by "it was introduced in version X, released 2 days ago"

The [CHANGELOG.md](https://github.com/project-serum/anchor/blob/master/CHANGELOG.md) has everything you need to know for each release. See that as the source of truth. All versions also tend to be announced in the `#accouncements` channel in discord.
