### ISSUE TITLE
Tutorials are using Result<()> as return type of the functions instead of ProgramResult

### ISSUE THREAD

**Issue by rsWrathionTBP** [project-serum/anchor#1533]
The tutorials functions are all returning Result<()> without using anyhow crate, all fn should be returning ProgramResult so we can use Ok(()) at the end of the functions

**Comment by armaniferrante** [comment]
`Result<()>` is not specific to anyhow. `ProgramResult` should not be used with Anchor, which uses a custom error type to store diagnostic information.
