### ISSUE TITLE
= not implemented for anchor_lang::error::Error

### ISSUE THREAD

**Issue by guibescos** [project-serum/anchor#1538]
I've been struggling to ```cargo test``` my code. 
Basically I want to create a unit test that runs a function and checks the returned error against an Anchor Error.

When I run : 
```assert_eq!(returns_error(), Err(error!(ErrorCode::MyError)))```
I get : 
```error[E0369]: binary operation `==` cannot be applied to type `Result<(), anchor_lang::error::Error>```
Reproducible example : https://github.com/guibescos/anchor-issue-error-equals
Run : ```cargo test```

**Comment by guibescos** [comment]
I seems to me like the equal operation might need to get implemented. Wanted to get some thoughts from the community on how easy this is to PR.

**Comment by callensm** [comment]
This would be a very simple pull request, but what is the use case for equating two errors within the contract code?

**Comment by guibescos** [comment]
rust tests, check my minimal example in the shared repo
