### ISSUE TITLE
Typescript complains when `.accounts()` from MethodNamespace is missing an account

### ISSUE THREAD

**Issue by danmt** [project-serum/anchor#1547]
## Description

`MethodsNamespace` has a mechanism to resolve accounts, with this we can avoid common accounts like `SystemProgram`, as well as PDAs since they are auto-populated.

## Problem

Due to this [change](https://github.com/project-serum/anchor/pull/1539), the accounts parameter is no longer any, which is awesome but now Typescript complains when not all the accounts are provided. This makes it impossible to use the account resolver logic.

## Proposed Solution

While it isn't pretty, we could wrap the accounts method parameter with `Partial`. This would bypass the error but makes it possible for developers to make a method call with *required accounts* missing. I think a better solution would be a mechanism to differentiate mandatory from optional accounts.

NOTE: I'm creating this issue without a PR because I'm not entirely sure which would be the best way to go.

**Comment by callensm** [comment]
ah yep, i'll fix this...just needs an `Exclude` wrapper for the account names for the ones handled by the resolver.

**Comment by danmt** [comment]
I like that solution much better. I'm far from good when it comes to Typescript complex types... As a hotfix for my use case, I did the `Partial` thing I mentioned and it works but yeah, it's kinda crappy. 

My concern with `Exclude` is that I thought that you could either let the resolver put the accounts for you or you can put it manually.

**Comment by callensm** [comment]
My thinking was that if we have an account resolver built in for things like `systemProgram`, `tokenProgram`, etc. then we should start discouraging / preventing people from providing it manually to prevent mistakes. In that case, `Exclude` would be perfect.

**Comment by danmt** [comment]
Totally agree with `systemProgram` and so on, but I'm not entirely convinced on PDAs, don't know why I gotta feel that someone *might* need to add a PDA account manually. This isn't my case, but don't know, that's my **concern**.

**Comment by danmt** [comment]
That means PDA accounts would still need to be manually added?

**Comment by danmt** [comment]
Looking at [this condition](https://github.com/project-serum/anchor/blob/master/ts/src/program/accounts-resolver.ts#L44) it seems like we need to Exclude global chain programs and accounts at PDAs should be optional, so `autoPopulate` is called only when the account wasn't provided.

**Comment by callensm** [comment]
I'm almost done with the PR and will link to this issue to see what my resolution was.

**Comment by danmt** [comment]
Just read the PR and it seems to cover the global chain programs part. But I don't think it solves the issue for accounts at PDAs, the `accounts` method will still ask for those accounts even though they could be auto-populated.
