### ISSUE TITLE
anchor test and msg!() ?

### ISSUE THREAD

**Issue by easydeveloppement** [project-serum/anchor#1549]
Hi,
why when i launch anchor test, and it fails, i do not get the content of msg!() in my program ? I tried to look at the flags, but found nothing relevant
thanks

**Comment by arunavo4** [comment]
The only thing I can think of is you might be using a separate Solana-test-validator somewhere else and there it can be logging it. as msg!() are supposed to be shown in the console itself while running anchor test.
Or else your program could have failed before even hitting the msg!() section. Anyhow, without looking at the code or any other context it's hard to say exactly.

**Comment by easydeveloppement** [comment]
i'm using devnet on solana rpc.
I found my solution : the logs are displayed in .anchor/program-logs
They still don't appear in my console, but they appear in this file, so it's enough for me :)

**Comment by bongdungyeuem27** [comment]
You can use Event
