### ISSUE TITLE
Create Associated Token Account ?

### ISSUE THREAD

**Issue by easydeveloppement** [project-serum/anchor#1553]
Hello, 
i have a question : 
I need to create an associated token account to send an NFT with rust.
So i have 3 solutions :
1) Either i create the account in JS before calling the program => it works great, but it makes the user signs 2 transactions (the first one for creating the account, the second one for calling the program)
2) Either there is a solution to create the token account at the same time that i call my program (like adding an instruction, but can't find any information about that ?)
3) Either i create the account in the rust program, i managed to find the publickey to be created with [spl_associated_token_account](https://docs.rs/spl-associated-token-account/latest/spl_associated_token_account/#) but can't figure out how to create it then and get an AccountInfo struct to use for transfering the NFT

Thank you for any reply that may help !

**Comment by callensm** [comment]
Have you tried initialized the associated token account within the instruction that you're calling?

```rs
#[account(
    init,
    payer = payer,
    associated_token::mint = mint,
    associated_token::authority = payer,
)]
pub token: Account<'info, TokenAccount>,
```

**Comment by fanatid** [comment]
1) You can put 2 messages to 1 transaction so only sign operation will be required.

**Comment by easydeveloppement** [comment]
@fanatid => how ? do you  know somewhere i can find an example ?
@callensm => that really looks like what i'm looking for. Tried it, but got an error : i need to sign the transaction with the account that will be created. I don't really understand how can i get it ? It will not be a PDA, it will be a token account for a wallet. i'm missing someting, but don't know where... thank you in advance ! => wi have an example with seeds, but i think that's not what i'm looking for....?

**Comment by fanatid** [comment]
Not sure about example. Can you publish your code?

**Comment by easydeveloppement** [comment]
Hi, found my answer, i post it here if it can help someone : 

`transaction = {
				accounts: {
					.....
					
				},
				instructions: [
					instruction,
				],
				signers: [...]
			};`

And in instruction, i have `instruction = Token.createAssociatedTokenAccountInstruction(...)`
