### ISSUE TITLE
avm: make `avm use` return error if anchor version is not installed (instead of prompting)

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1562]
this is done to make it avm more similar to nvm

**Comment by SvenDowideit** [comment]
mmm, for the kinds of usage I have, I'd rather that `avm use <version>` where essentially an idempotent assertion - the only time it would error, is if it failed to "make it so".

So if I had a different version installed, `avm` would try to install the requested version, and only return an error in the unlikely event that it fails to.

**Comment by tomlinton** [comment]
Is there a downside to prompting?

I think either is fine, perhaps not prompting is a little more friendly for automated applications, as interactive prompts are kind of annoying when dealing with automated builds.

**Comment by SvenDowideit** [comment]
From my pov - I don't have any time where prompting is welcome - if I've typed a command, its because that's what I want to have happen - and yes - its a opinion :)

**Comment by SvenDowideit** [comment]
TBH I like this - I'm still getting used to longer build times (I've been used to go for so many years), and its still my first week of rust, so I'd be perfectly happy for someone to replace my bad hack with real code :)

**Comment by GeorixYo** [comment]
Hey! can you help me please
Tried to install anchor but constantly have this error where system doesn't see version of avm
![3  20 222 88 17 (geo) 2022-08-15 21 15 46](https://user-images.githubusercontent.com/62509374/184699881-d6f56444-8ee2-4692-afe1-7a22dbc1c8de.png)

**Comment by tomlinton** [comment]
Run avm install 0.25.0 as described in the error
