### ISSUE TITLE
lang: remove `space` inference via `derive(Default)`

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1563]
- inefficient (it calls `Default::default` and then `len`)
- useless for dynamic types

**Comment by Henry-E** [comment]
Neither of these things seem like sufficient reason to remove space inference from `derive(Default)`
- it's inefficient but it's a quality of life improvement, assuming you're not using any dynamic types 
- Dynamic types needing manual space definitions is fine, it's just a byte per u8 or character in a string

Is this being replaced by any way to manually call this? Or some other way to simplify the calculation of how much space is needed. Like should we start adding `LEN` functions to all of our accounts structs now.

(this comment is probably coming too late but thought it worth responding anyway)

**Comment by paul-schaaf** [comment]
> Dynamic types needing manual space definitions is fine, it's just a byte per u8 or character in a string

agree that this is not a big deal

but

> it's inefficient

this is.

we want anchor to be as much of a zero-cost abstraction framework as possible and serializing an entire type just to get its static length is definitely far from that.

> Like should we start adding LEN functions to all of our accounts structs now.

`const` variables (see the tests in this PR)


One thing Ive thought about is a `#[len]` macro that reads the types and writes the `const` variable. I'll create an issue for a discussion on this.

**Comment by paul-schaaf** [comment]
https://github.com/project-serum/anchor/issues/1647

**Comment by Henry-E** [comment]
Just how inefficient is it? There's quite a bit of mental overhead to calculating the size of different accounts and then keeping them up to date. It's sort of the equivalent of how comments and their underlying code sometimes stray from each other. 

That said, I like that there's discussion of alternative solutions and I will comment there too. Thanks for listening!

**Comment by ceciEstErmat** [comment]
Also, this seems to me to be a tool. If you need the efficiency then use space, if you do not care and want the quality of life then use Default. 
Nothing in the framework enforced its use.
