### ISSUE TITLE
cli: add option to `anchor test` that starts a localnet with certain accounts already uploaded

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1595]
these accounts could be specified in some file / yaml config

theres the question whether this should be an anchor feature or a `solana-test-validator` feature that anchor delegates to or a mix of both

**Comment by tomlinton** [comment]
Maybe duplicate of https://github.com/project-serum/anchor/issues/1261?

**Comment by tomlinton** [comment]
> isn't this duplicate behavior from the `[[test.validator.clone]]` functionality in `Anchor.toml`?

That will clone accounts, but there is also `[[test.validator.account]]` which can load an account from a JSON file (analogous to the `--account` flag on `solana-test-validator`). I think this issue is about using that to provide funded accounts for development.

**Comment by paul-schaaf** [comment]
duplicate of #1261
