### ISSUE TITLE
spl crate should allow more token methods such as `initialize_account`

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#160]
It would be useful if the spl crate could have more methods such as the `initialize_account` method. This would make it a bit more convenient for allowing the creation of token accounts within program method calls. I need this functionality for some code I'm writing so if I manage to get it working I will submit a PR.

**Comment by armaniferrante** [comment]
Sounds great. A PR would be appreciated. I've mostly been adding the methods on an as needed basis.

**Comment by armaniferrante** [comment]
Addressed by #166.
