### ISSUE TITLE
Silently installing avm-cli

### ISSUE THREAD

**Issue by sebastiandine** [project-serum/anchor#1617]
I am setting up an Achor dev container but am struggling with the installation of `avm-cli`.
Is there a way I can silently install it? I tried `yes | avm use latest` but it still is promting the request.

**Comment by paul-schaaf** [comment]
does `avm install latest && avm use latest` work?

**Comment by sebastiandine** [comment]
> does `avm install latest && avm use latest` work?

seems like this did the trick. thank you :)
