### ISSUE TITLE
Multiple instructions

### ISSUE THREAD

**Issue by liudonghao** [project-serum/anchor#1630]
On the js side, is it possible to build a transaction that includes multiple instructions, one of which is to call a method of program built with Anchor?

you know, usually we can have something like 'const tx = new Transaction().add(...ixs);' if not using Anchor. 

But, when come to Anchor, I hope the array ixs can include the instruction to Anchor based program method,  what can I do with the following:

const atx = await program.rpc.someMethod()

**Comment by fanatid** [comment]
Yes, you can generate instructions like `program.instruction.someMethod`

**Comment by liudonghao** [comment]
> Yes, you can generate instructions like `program.instruction.someMethod`
cool @fanatid , can you share some links pointing to examples?

**Comment by fanatid** [comment]
https://github.com/project-serum/swap/blob/3da36aaae7af6ce901d68c0280aac34817fe7fd8/tests/swap.js#L181-L212

**Comment by liudonghao** [comment]
> https://github.com/project-serum/swap/blob/3da36aaae7af6ce901d68c0280aac34817fe7fd8/tests/swap.js#L181-L212

thank you very much, really helpful!
