### ISSUE TITLE
Initialize anchor project in existing repository

### ISSUE THREAD

**Issue by jjordan-quantum** [project-serum/anchor#1633]
Is it possible to init an anchor project in an existing repo?

Typically `anchor init {project_name}` creates the directory for a new project, and `anchor new {program_name}` adds a new program to the existing project.

If I already have a repository, and I create a new branch in which I would like to initialize an anchor project, is there a command for that?

Or perhaps I just copy all the files / dirs from an initialized project and edit them as needed?

**Comment by tomlinton** [comment]
Not sure I understand but maybe `anchor init {project_name} && mv {project_name}/* . && rm -rf {project-name}`?

**Comment by jjordan-quantum** [comment]
yeah thats pretty much what I had to do. was checking if there was a command / option for doing this directly, bc i couldnt find one

**Comment by qwen-3108** [comment]
I think allowing initialization into an existing project directory is more consistent with the behavior of common javascript tooling (e.g. `npm`).

**Comment by vendowwws** [comment]
anchor init myproject
cd myproject
