### ISSUE TITLE
Lifetime issue in using ctx.remaining_accounts

### ISSUE THREAD

**Issue by liudonghao** [project-serum/anchor#1639]
```
let account_owner = ctx.accounts.owner.to_account_info();
let remaining_accounts: Vec<AccountInfo> = ctx.remaining_accounts.to_vec();        
for creator in remaining_accounts {
            let ix5 = system_instruction::transfer(
                &account_owner.key, 
                &creator.key, 
                lamports
            );
            invoke(
                &ix5,
                &[
                    account_owner.clone(),
                    creator.clone(),
                ],
            )?;
        }
```

the problem is caused by account_owner, the erros as below:

![image](https://user-images.githubusercontent.com/7846344/158834582-de691bfc-09cc-4643-b981-60beb81ce859.png)

**Comment by liudonghao** [comment]
> the problem is caused by account_owner, the erros as below:

thank you Paul, solved, really helpful, just still don't understand why it works the way it works, LIFETIME!!

**Comment by jiangchuan** [comment]
I am having the same LIFETIME problem. And I have been struggling with it for several hours. What is the solution please?

**Comment by RieserStern** [comment]
Hello everyone, I am interested your working

**Comment by snawaz** [comment]
> > the problem is caused by account_owner, the erros as below:
> 
> thank you Paul, solved, really helpful, just still don't understand why it works the way it works, LIFETIME!!

Did you solve it? How exactly? Could you please share the solution?

**Comment by toygr** [comment]
https://solana.stackexchange.com/a/3365/25353
