### ISSUE TITLE
Anchor build Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by conceptstom** [project-serum/anchor#1645]
WSL2:
When trying to build in a  newly installed project: solblog from 
https://github.com/DougAnderson444/solblog  

I followed the  install instructions carefully at at the Serum Anchor project site: 
https://project-serum.github.io/anchor/getting-started/installation.html#install-rust

But i get this result when i try to build: 
-- > Anchor build Error: No such file or directory (os error 2) <--
![Skærmbillede 2022-03-18 07 07 17](https://user-images.githubusercontent.com/8062795/158947012-6f40f7c3-47fb-4bce-b8e1-3baaf38906fa.png)

**Comment by fanatid** [comment]
Please ask about installation help in https://discord.gg/PDeRXyVURd

**Comment by mateolafalce** [comment]
In your case: `anchor init` after `anchor build`

**Comment by Blessedbiello** [comment]
facing same problem
in the target directory, the idl and the types folders are empty

**Comment by blikq** [comment]
> facing same problem in the target directory, the idl and the types folders are empty

Did you find a solution
