### ISSUE TITLE
 owner = id() doesn't work in version 0.22.1

### ISSUE THREAD

**Issue by liudonghao** [project-serum/anchor#1646]
owner = id() doesn't work in version 0.22.1, but works in 0.20.1 though

**Comment by paul-schaaf** [comment]
Whats the error youre getting?

**Comment by liudonghao** [comment]
> Whats the error youre getting?

![image](https://user-images.githubusercontent.com/7846344/159110600-18f9034a-26c9-4759-a585-330b5e6a466b.png)
![image](https://user-images.githubusercontent.com/7846344/159110631-efc088dd-3105-416c-9440-02511105ed6c.png)

**Comment by paul-schaaf** [comment]
could you also share your `derive(Accounts)` struct?

**Comment by paul-schaaf** [comment]
nvm Im able to reproduce it myself

**Comment by paul-schaaf** [comment]
the PR will fix your issue.

but pls share your struct anyway. I have a feeling you might not need `owner = id()`

**Comment by liudonghao** [comment]
> the PR will fix your issue.
> 
> but pls share your struct anyway. I have a feeling you might not need `owner = id()`

`#[derive(Accounts)]
pub struct PlacePurchaseOrder<'info> {
    #[account(signer,mut)]
    pub buyer: AccountInfo<'info>,
    pub buyer_encrypt: AccountInfo<'info>,

    #[account(signer,mut)]
    pub buyer_wrapped_sol: AccountInfo<'info>,

    #[account(
        mut,
        // owner = id(),
    )]
    pub sale_order: Account<'info, SaleOrder>,

    #[account(mut)]
    pub sol_vault: AccountInfo<'info>,

    pub native_mint: AccountInfo<'info>,
    pub rent: Sysvar<'info, Rent>,    
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,   
}`

Actually, it doesn't matter which struct it's in, as long as it's there, the same error.
BTW: now it works in version 0.22.1? I noticed it's fixed.

**Comment by paul-schaaf** [comment]
no need to use `owner` on `Account` (https://docs.rs/anchor-lang/latest/anchor_lang/accounts/account/struct.Account.html). Account already does the check for oyu

It will be fixed with the next release

**Comment by liudonghao** [comment]
Cool, thank you, I'm kind of old version guy, looks like I should read through all docs of the latest version word by word
