### ISSUE TITLE
cli: allow separate test suites with separate local-validators (when testing on localnet)

### ISSUE THREAD

**Issue by paul-schaaf** [project-serum/anchor#1658]

**Comment by paul-schaaf** [comment]
re: https://github.com/project-serum/anchor/issues/1261#issuecomment-1068778213

> The list of test validator settings is [here](https://github.com/project-serum/anchor/blob/master/cli/src/config.rs#L549-L593). I don't really see anything there that needs to change per test outside of account, clone, and maybe the slots_per_epoch and warp_slot option (and even then, you can probably get away with just loading the data you need under different addresses). The CLI should control all the port, path, etc options to allow for test/ledger isolation and parallelism.

> account, clone, and maybe the slots_per_epoch and warp_slot

those alone justify a separate config for me.

> (and even then, you can probably get away with just loading the data you need under different addresses)

cause this isn't clean. one of the benefits you get by splitting up the tests into separate suites is that you get truly separate validators that are not polluted with unintended state. this would make that separation less useful.

So maybe for all other options, we have a `tests/Test.toml` that specifies those and then if you really want to adjust those options you can override them in your `tests/my-test/Test.toml`?

**Comment by paul-schaaf** [comment]
> Acknowledging --clone will slow everything down significantly for every separate validator, I think we should discourage use of --clone in favour of --account anyway.

Assuming youre using the mainnet url, using `--clone` ensures your test is as close to the real environment though whereas `--account` does not. I'm wondering whether there is a way to make anchor cache cloned accounts and use `--account` from then on. Then you could have faster CI while youre developing and a one time `--clone` at the end of whatever PR youre making to your project to make sure it really all still works. But this is probably something for a different issue.


Armani and I discussed this offline and up with the following design for the dir structure. We basically do what `tsconfig.json` does which is extending a base file. So when youre creating a new repo you have the following structure:

```
.
Anchor.toml
tests
--- suite1
------ Test.toml
------ test.ts
```

where the `Test.toml` inside the suite1 dir just looks like this:
```
extends = ["../../Anchor.toml"]
```

that way you can pull your config from anywhere you like, whether it's the Anchor.toml or a separate Test.toml or even multiple `.toml` files or you dont pull any other config at all and specify it in the Test.toml.

Thinking ahead, this also allows for options like `accounts = ["./accounts/"]` where the accounts can be a format that we specify later

**Comment by tomlinton** [comment]
Sounds good 👍

**Comment by paul-schaaf** [comment]
clsoed by #1681
