### ISSUE TITLE
`avm`  CI friendly ideas

### ISSUE THREAD

**Issue by italoacasas** [project-serum/anchor#1663]
### New command
- `avm update` (install the latest stable version, if not installed)

### Improvements

- `avm install x.x.x` Will not reinstall x.x.x if the version is installed already.
- `avm install x.x.x --force` Will force reinstall

**Comment by paul-schaaf** [comment]
would `avm update` update to the latest `avm` or the latest `anchor` version?

**Comment by italoacasas** [comment]
I was thinking of `anchor`

**Comment by italoacasas** [comment]
> would `avm update` update to the latest `avm` or the latest `anchor` version?

I was thinking of `anchor`

**Comment by paul-schaaf** [comment]
closed by #1670
