### ISSUE TITLE
Can't build the project with anchor@0.23.0

### ISSUE THREAD

**Issue by Beardev118** [project-serum/anchor#1666]
I have updated the @project-serum/anchor version to 0.23.0 and I tried to build in anchor-cli.
But I can't get the success with this new version.
When using the 0.22.1, I got the success.
![image](https://user-images.githubusercontent.com/55624311/159348665-737b3d3c-5451-4590-8829-a4a73282ad4d.png)

**Comment by paul-schaaf** [comment]
have you updated both your versions as well as the cli? (with `avm use latest`)

**Comment by Beardev118** [comment]
Yeah

**Comment by paul-schaaf** [comment]
this is very likely a version mismatch on your side.
make sure that `anchor -V` returns `0.23.0`

**Comment by Beardev118** [comment]
Yeah, I have got that version fully and success the build
But at this time, I think we can't use the spl-token version greater than 3.2.0

**Comment by Beardev118** [comment]
![image](https://user-images.githubusercontent.com/55624311/159365622-bb4f7e96-1c54-4ca9-9b55-a92c1aca1313.png)

**Comment by Beardev118** [comment]
Okay, thank you
