### ISSUE TITLE
Failing Anchor Test often leaves solana test cluster running in the bg

### ISSUE THREAD

**Issue by Standaa** [project-serum/anchor#167]
Launching `anchor test` when the project has not been set up properly often results in the cluster keeping running in the background.
This leads to other errors when relaunching the command.

On mac I would usually have to check the processes running on ports : `sudo lsof -i -P | grep LISTEN` and kill the pid occupying port 8899 (default).

Is there any way to make sure the cluster always stops ?

**Comment by armaniferrante** [comment]
Do you have a reliable way to trigger this?

**Comment by Standaa** [comment]
Not yet. It happens every now and then though. I'll try to replicate.

**Comment by Standaa** [comment]
Closing as I did not encounter this behaviour in a long time.
