### ISSUE TITLE
Anchor deploy doesn't function due to it can't connect to the solana-test-validator. Because localhost can't be started up

### ISSUE THREAD

**Issue by conceptstom** [project-serum/anchor#1676]
![Skærmbillede 2022-03-24 12 04 32](https://user-images.githubusercontent.com/8062795/159903311-b49398c9-4d8f-4b5a-a695-aca10192aa35.png)
Following the Solana docs how to make a system tuning : 
https://docs.solana.com/running-validator/validator-start#system-tuning
sudo $(command -v solana-sys-tuner) --user $(whoami) > sys-tuner.log 2>&1 & ( It must be done it's stated )
Then in another terminal running the  solana-test-validator with the configure: solana config set --url http://127.0.0.1:8899 is NOT firing up a localhost testnode...
I've tried many times the result is always the same:

-> Ledger location: test-ledger
Log: test-ledger/validator.log <- And nothing more happens... 

I mean it should fire up a localhost something like: 
Ledger location: test-ledger
Log: test-ledger/validator.log
Identity: EPhgPANa5Rh2wa4V2jxt7YbtWa3Uyw4sTeZ13cQjDDB8
Genesis Hash: 4754oPEMhAKy14CZc8GzQUP93CB4ouELyaTs4P8ittYn
Version: 1.6.7
Shred Version: 13286
Gossip Address: 127.0.0.1:1024
TPU Address: 127.0.0.1:1027
JSON RPC URL: http://127.0.0.1:8899
⠈ 00:36:02 | Processed Slot: 5142 | Confirmed Slot: 5142 | Finalized Slot: 5110 | Snapshot Slot: 5100 | Transactions: 5142 | ◎499.974295000

**Comment by pisomanik** [comment]
On line 10. It says listening on port `9900`
Does that mean something?

**Comment by conceptstom** [comment]
> On line 10. It says listening on port `9900` Does that mean something?

solana config set --url localhost
Config File: /home/tomcatzy/.config/solana/cli/config.yml
RPC URL: http://localhost:8899
WebSocket URL: ws://localhost:8900/ (computed)
Keypair Path: /home/tomcatzy/.config/solana/id.json
Commitment: confirmed.

No thats strange as stated here: Port 8899 is set.
Can it be that there has to be a dynamic port arrangement - and how to set it if that ?

**Comment by tomlinton** [comment]
Per the screenshot this is an issue with your Solana install and/or your WSL2 setup. I suggest you check the Solana discord and search that as this isn't really an Anchor issue.

**Comment by fanatid** [comment]
Please check that validator actually running (by checking port for example), in logs you can see stack trace about number of opened file descriptors. You need to change `LimitNOFILE` https://docs.solana.com/running-validator/validator-start
