### ISSUE TITLE
How to avoid "bump targets should not be provided with init. Please use bump without a target."

### ISSUE THREAD

**Issue by black-wyvern-dev** [project-serum/anchor#1682]
I built the program on anchor version 0.21.0 and this issue come out "Providing bump = <target> targets with init will now error. On init only, it is required to use bump without a target and access the seed inside function handlers via ctx.bumps.get("<pda-account-name"). For subsequent seeds constraints (without init), it is recommended to store the bump on your account and use it as a bump = <target> target to minimize compute units used ([#1380](https://github.com/project-serum/anchor/pull/1380))"
How can I fix this issue?

**Comment by floomzy** [comment]
The Anchor Book PDA example doesn't set the bump, just includes it:
https://book.anchor-lang.com/chapter_3/PDAs.html

**Comment by callensm** [comment]
@black-wyvern-dev this isn't an issue to be fixed. Like the message is saying, as of `v0.21.0`, when you initialize a new account using the `init` constraint, you no longer provide a value for the `bump` constraint. You simply add it to the list without an `= <value/target>` and Anchor calculates and exposes the bump for you via the `ctx.bumps` `BTree` in your instruction handler.

You can, and is recommended, however to still provide the bump value as previously done for all non-initialization account constraint groups.

**Comment by paul-schaaf** [comment]
as others have pointed out, this is not an issue with anchor so Im closing this
