### ISSUE TITLE
Consider increasing [test.startup_wait] in Anchor.toml

### ISSUE THREAD

**Issue by ELBEQQAL94** [project-serum/anchor#1694]
When i run `anchor test` i got this error:

BPF SDK: /home/youssef/.local/share/solana/install/releases/1.10.4/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
warning: unused variable: `ctx`
 --> programs/myepicproject/src/lib.rs:9:23
  |
9 |     pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
  |                       ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: `myepicproject` (lib) generated 1 warning
    Finished release [optimized] target(s) in 0.35s
cargo-build-bpf child: /home/youssef/.local/share/solana/install/releases/1.10.4/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/youssef/workspace/myepicproject/target/deploy/myepicproject.so

To deploy this program:
  $ solana program deploy /home/youssef/workspace/myepicproject/target/deploy/myepicproject.so
The program address will default to this keypair (override with --program-id):
  /home/youssef/workspace/myepicproject/target/deploy/myepicproject-keypair.json
Unable to get recent blockhash. Test validator does not look started. Check .anchor/test-ledger/test-ledger-log.txt for errors. Consider increasing [test.startup_wait] in Anchor.toml.

OS: Ubuntu 20.0
@project-serum/anchor: v0.23.0
anchor: 0.23.0

**Comment by paul-schaaf** [comment]
it's telling you what to do. increase the startup waiting time. https://book.anchor-lang.com/chapter_5/anchor-toml_reference.html.

pls go to discord for any further support questions https://discord.gg/GVRw4kHB
