### ISSUE TITLE
is BN typing missing?

### ISSUE THREAD

**Issue by sweetim** [project-serum/anchor#1696]
there is no typing available for BN class?

```
import { BN } from "@project-serum/anchor";

let a = new BN(10);

a. // missing auto completion inVScode, and i cant find any typings for BN in the node_modules
```

am I using it wrongly or it is not supported?

**Comment by sweetim** [comment]
it is working with that method!

**Comment by dvrvsimi** [comment]
how is this a fix?
that means a totally different usage for `BN` now
