### ISSUE TITLE
Compile error using Result<()>  ---> "expected 2 generic arguments"

### ISSUE THREAD

**Issue by bubu59** [project-serum/anchor#1722]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/GVRw4kHB (but don't ping maintainers). ⚠️
![image](https://user-images.githubusercontent.com/74093051/161411154-274d190a-4c8d-4826-8f78-e428ec592654.png)
Hi guys, when I was running my code, I ran into the above compile error. I have upgraded my anchor-cli to v0.22.0 but still facing this issue. Any ideas why this might be the case? Thank you!

**Comment by SailorSnoW** [comment]
seems like it use the wrong Result type, try with `anchor_lang::Result<()>` instead ?

**Comment by tomlinton** [comment]
You may have forgotten to update the `anchor-lang` version in `programs/myepicproject/Cargo.toml`

**Comment by paul-schaaf** [comment]
pls use the discord for support https://discord.gg/rnNpg7Ys
