### ISSUE TITLE
Can't init Provider in non-Node environment

### ISSUE THREAD

**Issue by csjiang** [project-serum/anchor#1742]
Hey! We'd like to be able to instantiate `AccountClient` client-side, but it relies on [`Provider`](https://github.com/project-serum/anchor/blob/9f74a288bc/ts/src/provider.ts#L20-L83) which in turn requires a `Wallet` class, which currently relies on the [Node-only `NodeWallet` class](https://github.com/project-serum/anchor/blob/9f74a288bc3ed40534199571c368c276367e3615/ts/src/index.ts#L16
). 

1. Is there a recommended way to work around NodeWallet trying to read from the fs, so that we can use it browser-side?
2. Is supporting client-side usage of Provider on the roadmap?

**Comment by paul-schaaf** [comment]
`Provider` is an interface now that does not include the `NodeWallet` in its definition, so you can implement a Non-Node Provider.

In earlier releases, you can construct a Provider object with a non-node wallet
