### ISSUE TITLE
lang: Rename ProgramAccount and ProgramState to Account and State

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#179]

**Comment by fanatid** [comment]
Not sure when `ProgramState` was renamed/removed, but right now `ProgramAccount` and `State` are deprecated.

**Comment by armaniferrante** [comment]
> Not sure when `ProgramState` was renamed/removed, but right now `ProgramAccount` and `State` are deprecated.

This issue was never addressed, so `ProgramState` is still around and was originally meant to be used in a `#[derive(Accoutns)]` struct for "state" accounts.

**Comment by armaniferrante** [comment]
Sorry for the confusion! This should still be closed. I was just explaining that the rename/remove never happened.
