### ISSUE TITLE
anchor init hello-anchor throwing error

### ISSUE THREAD

**Issue by tenaka1651** [project-serum/anchor#1805]
Running the following command on my Windows 10 machine isn't working

anchor init hello-anchor 

The new project folder is created with content, but the error is displayed at command line 
Error: yarn install failed: program not found

I have anchor-cli 0.24.1 installed
yarn 1.22.15
solana-cli 1.9.5
rustc 1.60.0

I have tried reinstalling and retried this step
cargo install --git https://github.com/project-serum/anchor avm --locked --force

**Comment by fanatid** [comment]
Are you sure that `yarn` is installed? What is result of `yarn --version`?

**Comment by tenaka1651** [comment]
Thanks I gave up on getting it working under Windows.. so much easier to install WSL with ubuntu... all works fine there so I'm closing this issue
