### ISSUE TITLE
Error while loading shared libraries. (libssl.so.1.1)

### ISSUE THREAD

**Issue by Nwqda** [project-serum/anchor#1831]
Hey there! On anchor-cli 0.24.2.

Trying to run the command `anchor test` but when I do so, I get hit with:

```
BPF SDK: /home/user/.local/share/solana/install/releases/1.9.1/solana-release/bin/sdk/bpf

cargo-build-bpf child: rustup toolchain list -v

cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release

/home/user/.rustup/toolchains/bpf/bin/cargo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
I carefully followed all the steps from the official tutorial, https://project-serum.github.io/anchor/getting-started/installation.html#install-rust on a freshly installed version of Ubuntu 22.04.

Do you have any idea how to fix this?

== UPDATE ==

It seems that Ubuntu 22.04 has OpenSSL 3.0.2 installed by default. This seems to be the cause of the problem.

As downgrading is not a good idea, do you have any other solution?

For reference:

```
openssl version  
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022) 

ldd $(which openssl)    
	linux-vdso.so.1 (0x00007ffffa2cc000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f5e0e69a000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f5e0e258000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e0e030000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5e0e846000)
```

== FIX ==

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
```

**Comment by kise999** [comment]
I also had the same issue.
Hope I can use anchor on Ubuntu 22.04

**Comment by fanatid** [comment]
Can you try this? https://askubuntu.com/a/1404383

**Comment by Nwqda** [comment]
Hi @fanatid,

The solution you've shared worked.

```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.2_amd64.deb
```

Thanks.

**Comment by itsbek** [comment]
> Can you try this? https://askubuntu.com/a/1404383

spent some time searching for this. thank you @fanatid
