### ISSUE TITLE
failed to select a version for the requirement `anchor-lang = "^0.20.1"

### ISSUE THREAD

**Issue by black-wyvern-dev** [project-serum/anchor#1847]
Hi everyone! Sorry to bother you.
When I develop smart  contract by anchor I did `cargo build` but this error appears.
```
ubuntu@ip-172-31-25-151:~/apollo/NFT-staking-Death/staking/programs/staking$ cargo build
    Updating crates.io index
    error: failed to select a version for the requirement `anchor-lang = "^0.20.1"`
    candidate versions found which didn't match: 0.24.2
    location searched: crates.io index
    required by package `staking v0.1.0 (/home/ubuntu/apollo/NFT-staking-Death/staking/programs/staking)`
```
In my PC, I am using anchor-version 0.20.1 but should I upgrade it to 0.24.2? Other projects built in v0.20.1 are doing well.

**Comment by fanatid** [comment]
All versions except `0.24.2` were yanked, if you want to use the old one set git repository as a source.
https://crates.io/crates/anchor-lang/versions
