### ISSUE TITLE
ts: Add TX signature to EventCallback

### ISSUE THREAD

**Issue by charlieyou** [project-serum/anchor#1850]
Currently, only the Event and the slot are passed to the EventCallback: https://github.com/project-serum/anchor/blob/282c394666a389ba9e086f974db39de7a6194028/ts/src/program/event.ts#L26

The TX signature is also included in the Logs object that is passed to the LogsCallback: https://solana-labs.github.io/solana-web3.js/modules.html#Logs

It would be *very* useful to have this forwarded to the EventCallback as it would make enriching event data much easier.

In searching to see if anyone else brought this up, I see that Armani posted this issue a while back: https://github.com/project-serum/anchor/issues/136. Adding the signature would likely be required before an Event indexer is useful.

Seems like an easy change to make, and I don't see many downsides? Happy to take it on if the core team agrees.

**Comment by callensm** [comment]
this issue should be closed.

**Comment by armaniferrante** [comment]
Closed by #1851.
