### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by skwidflow** [project-serum/anchor#1891]
Hi, im a complete n00b so while installing yarn and anchor i get an error stating  "The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user " 

how do i resolve this issue. I am logging into the terminal using the amin/ main user profile. 

Thanks

**Comment by fanatid** [comment]
Please check results in google https://www.google.com/search?q=npm+%22permissions+to+access+this+file+as+the+current+user%22
If you have any further questions please ask in discord.
