### ISSUE TITLE
RPC depreciation

### ISSUE THREAD

**Issue by baileyspraggins** [project-serum/anchor#1893]
⚠️ Don't use issues for support questions ("How does x feature work in Anchor? How to do x in Anchor?"). Use the discord instead https://discord.gg/GVRw4kHB (but don't ping maintainers). ⚠️

What is used to call methods from Programs in the client now that program.rpc is depreciated

**Comment by armaniferrante** [comment]
`program.methods.<my-method>().accounts({...}).rpc()` Please see the examples and/or tests.

**Comment by baileyspraggins** [comment]
Every example and/or tests I have seen on here does not utilize this. Am I looking in the wrong spot? Im trying to get this code to work but its saying theres an unknown signer. Not sure if my syntax is wrong or not
<img width="627" alt="Screen Shot 2022-05-14 at 8 41 39 PM" src="https://user-images.githubusercontent.com/62624378/168453700-a0895281-c454-4194-a610-bb4b1e8a8304.png">
.

**Comment by ugunenc** [comment]
I dont know did you solve but you can try this:

```
tx = await program.methods.createPost(TITLE, CONTENT)
.accounts({
    post: postAccount.publicKey,
    author: provider.wallet.publicKey,
    systemProgram: anchor.web3.SystemProgram.programId
})
.signers([postAccount])
.rpc();
```
