### ISSUE TITLE
any complex example with several states/accounts in single instruction?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [project-serum/anchor#191]

**Comment by armaniferrante** [comment]
No there is not. Currently, the `#[state]` account is meant to be used as a single global account shared across the entire program to give the program the illusion of state. If one wants to use multiple accounts, one can use regular instructions and the `#[account(init)]` attribute.

Can you elaborate more on your use case, and provide an example of what you're imagining. It may be a good idea to add a new attribute similar to state, or to allow one to have several state accounts, namespaced by the rust identifier.

**Comment by dzmitry-lahoda** [comment]
yep, for example with multiple accounts. all programs i have ported or wrote where multi accounts, none of them single account

**Comment by dzmitry-lahoda** [comment]
for now anchor looks like all or nothing, but example how to mix attributes and custom code is what real prod dev needs

**Comment by armaniferrante** [comment]
If this feature is added it will probably look something like https://github.com/project-serum/anchor/issues/150#issuecomment-819744251.

Closing in favor of that issue. Thanks for bringing this up!
