### ISSUE TITLE
The declared program id does not match the actual program id

### ISSUE THREAD

**Issue by matteosantama** [project-serum/anchor#1912]
I am trying to familiarize myself with the Anchor ecosystem by following the instructions [here](https://project-serum.github.io/anchor/tutorials/tutorial-0.html#clone-the-repo). I am running into an error when I reach the **Generating a Client** section.

My `lib.rs` is completely unchanged

```rust
use anchor_lang::prelude::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod my_project {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

I've successfully run `anchor build` and `anchor deploy` ...

```
❯ anchor deploy
Deploying workspace: http://localhost:8899
Upgrade authority: /Users/matteosantamaria/.config/solana/id.json
Deploying program "my_project"...
Program path: /Users/matteosantamaria/my_project/target/deploy/unnamed.so...
Program Id: 2uAaYZESqWuvLfPaL9pwUY7g5cWY6oz6NEshreKvMDVD

Deploy success
```

so my `client.js` looks like 

```ts
const anchor = require("@project-serum/anchor");

// Configure the local cluster.
anchor.setProvider(anchor.AnchorProvider.local());

async function main() {
  // #region main
  // Read the generated IDL.
  const idl = JSON.parse(
    require("fs").readFileSync("./target/idl/my_project.json", "utf8")
  );

  // Address of the deployed program.
  const programId = new anchor.web3.PublicKey("2uAaYZESqWuvLfPaL9pwUY7g5cWY6oz6NEshreKvMDVD");

  // Generate the program client from IDL.
  const program = new anchor.Program(idl, programId);

  // Execute the RPC.
  await program.rpc.initialize();
  // #endregion main
}

console.log("Running client.");
main().then(() => console.log("Success"));
```

but when I run 

```
❯ ANCHOR_WALLET=/Users/matteosantamaria/.config/solana/id.json node client.js
```

I get errors complaining that "The declared program id does not match the actual program id". What am I doing wrong here?

**Comment by 0xdeepmehta** [comment]
you need to replace the program id in `declare_id!()` with new one
`declare_id!("2uAaYZESqWuvLfPaL9pwUY7g5cWY6oz6NEshreKvMDVD");`

**Comment by 0xdeepmehta** [comment]
So the general workflow looks like this.
1. `anchor init <program_name>`
2. `anchor build`
3. `anchor keys list`
4. copy the output address and replace the address in `declare_id!()` with it.
5. now write your contract ......
6. `anchor build`
7. `anchor deploy`

**Comment by mirzasetiyono** [comment]
if you already did  https://github.com/coral-xyz/anchor/issues/1912#issuecomment-1133564677 and problem still persist. 
try to make sure everything related to project name are the same, i spent 3 hours debugging and decided to create new project with everything related to name are consistent. it works in my case. 

![image](https://user-images.githubusercontent.com/56542125/184531751-4a19105e-dc41-44f1-a553-27f164f70efd.png)
