### ISSUE TITLE
Feature Request: add pda realloc to account macro

### ISSUE THREAD

**Issue by cavemanloverboy** [project-serum/anchor#1917]
I think this new feature could go in the `#[account()]` macro, e.g.
```rust
#[derive(Accounts)]
#[instruction(new_size: usize)]
pub struct MyAccounts<'info> {
    #[account(
        mut,
        realloc = new_size,
        ...
    )]
    pub my_pda: Account<'info, DataAccount>
}
```
and perhaps skip the realloc if old size is equal to new size.

**Comment by cavemanloverboy** [comment]
If you point me to the right file/scope I'll see if I can throw something together

**Comment by callensm** [comment]
The implementation should also include the requirement of including something like `exempter`  to handle the transfer of lamports to or from the program account to manage the rent exemption increase or decrease related to the reallocation.

**Comment by armaniferrante** [comment]
@cavemanloverboy see https://github.com/project-serum/anchor/tree/master/lang/syn/src.
