### ISSUE TITLE
Expose coder for user defined types as `program.coder.types`.

### ISSUE THREAD

**Issue by vovacodes** [project-serum/anchor#1930]
I've run into a situation recently when I needed to manually deserialize a slice of account data into a type that I have in my IDL, but which is not an account type. Here's like my Rust part looks like:
```rust
#[account]
pub struct Mintlist {
    pub mints: Vec<MintInfo>
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone, PartialEq)]
pub struct MintInfo {
    pub minted: bool,           // 1
    pub metadata_url: [u8; 96], // 96
}
```
On the client I would like to use something like this:

```ts
const mintInfo = program.coder.types.decode("MintInfo", dataSlice)
```

Looking at the codebase it seems like a trivial thing to add and I'm happy to submit a PR if you think it makes sense.

**Comment by kklas** [comment]
You can also do this with anchor-client-gen btw. This is how you'd decode a single type from encoded data https://github.com/kklas/anchor-client-gen/blob/master/examples/tic-tac-toe/generated-client/accounts/Game.ts#L89.

**Comment by vovacodes** [comment]
@kklas thanks for pointing out, this is great. That said, I also believe `anchor` will benefit from exposing this functionality directly as it already has largely implemented internally, just not exposed publicly.

**Comment by kklas** [comment]
Of course!
