### ISSUE TITLE
Unable to get program to log message to solana logs or test-validator logs

### ISSUE THREAD

**Issue by kre8mymedia** [project-serum/anchor#1932]
## Unable to get program to log message to solana logs or test-validator logs
Inside my lib.rs file I've included 3 types of ways that I've found for creating a log. Doesn't see as if any of them worked. Unable to find a log for "HELLO WORLD!" anywhere.

**NOTE:** This is using the Anchor basic-0 example, also tried running the RUST_LOG command from solana docs
https://docs.solana.com/developing/on-chain-programs/debugging#logging

### Steps to repro
1. Add print messages to initialize instruction
2. Run `solana-test-validator`
3. Run `solana logs --url localhost`
4. Run `anchor build` then `anchor deploy` in order to get the program public key
5. Place the program public key in relevant places with in files (lib.rs, client.js, Anchor.toml)
6. Run `anchor build` then `anchor deploy` to redeploy with updated public key to localnet
7. Run `ANCHOR_WALLET=<path_to_keypair> node client.js`
8.  Verify client runs
9. Check test-ledger/validator.log
10. Check terminal that is running step 3

## See LOOM Video for demo
https://www.loom.com/share/9c138d574cf448c0896995e1edffc9d6

**Comment by anoushk1234** [comment]
> ## Unable to get program to log message to solana logs or test-validator logs
> 
> Inside my lib.rs file I've included 3 types of ways that I've found for creating a log. Doesn't see as if any of them worked. Unable to find a log for "HELLO WORLD!" anywhere.
> 
> **NOTE:** This is using the Anchor basic-0 example, also tried running the RUST_LOG command from solana docs https://docs.solana.com/developing/on-chain-programs/debugging#logging
> ### Steps to repro
> 
>     1. Add print messages to initialize instruction
> 
>     2. Run `solana-test-validator`
> 
>     3. Run `solana logs --url localhost`
> 
>     4. Run `anchor build` then `anchor deploy` in order to get the program public key
> 
>     5. Place the program public key in relevant places with in files (lib.rs, client.js, Anchor.toml)
> 
>     6. Run `anchor build` then `anchor deploy` to redeploy with updated public key to localnet
> 
>     7. Run `ANCHOR_WALLET=<path_to_keypair> node client.js`
> 
>     8. Verify client runs
> 
>     9. Check test-ledger/validator.log
> 
>     10. Check terminal that is running step 3
> 
> 
> ## See LOOM Video for demo
> 
> https://www.loom.com/share/9c138d574cf448c0896995e1edffc9d6

The logs generally appear in the .anchor folder in the workspace.
Incase the txn fails then you can only see the logs if you wrap the clien side rpc call with try catch and console log the error, incase the txn is sent you can see the logs in the explorer by searching with the txn hash

**Comment by kre8mymedia** [comment]
@anoushk1234 

> The logs generally appear in the .anchor folder in the workspace.
In case the txn fails then you can only see the logs if you wrap the client-side RPC call with try-catch and console log the error, in case the txn is sent you can see the logs in the explorer by searching with the txn hash

That doesn't seem to address the question. I get the same results when checking program logs running `anchor test` in order to generate the `.anchor` folder in the workspace. When checking program logs and the validator logs in that folder still yields no program log message of "HELLO WORLD!" anywhere. 

In my video, I'm showing just another way as from what I've researched there was a lot of chatter that the test-validator would need to be running to have the message show up in `Solana logs watch` command is run. 

Since I'm trying simply to print a msg and not create an error in my program try/catch would not be applicable to what I'm trying to achieve but getting the message "HELLO WORLD!" to appear anywhere.

**Comment by anoushk1234** [comment]
> @anoushk1234
> 
> > The logs generally appear in the .anchor folder in the workspace.
> > In case the txn fails then you can only see the logs if you wrap the client-side RPC call with try-catch and console log the error, in case the txn is sent you can see the logs in the explorer by searching with the txn hash
> 
> That doesn't seem to address the question. I get the same results when checking program logs running `anchor test` in order to generate the `.anchor` folder in the workspace. When checking program logs and the validator logs in that folder still yields no program log message of "HELLO WORLD!" anywhere.
> 
> In my video, I'm showing just another way as from what I've researched there was a lot of chatter that the test-validator would need to be running to have the message show up in `Solana logs watch` command is run.
> 
> Since I'm trying simply to print a msg and not create an error in my program try/catch would not be applicable to what I'm trying to achieve but getting the message "HELLO WORLD!" to appear anywhere.
> 
> I don't disagree that your understanding is deeper than my own but I'm not understanding where the messsages are being shown during an `anchor test` or are you saying these should be viewed on the devnet? I can see from some of your repos you're using `msg!(<SOMEMESSAGE>)` based on this program file. https://github.com/digxv/solana-splits/blob/main/programs/split/src/lib.rs

You are running this on localnet so after your txn is complete copy the txn hash, go to explorer.solana.com , change network to custom rpc and search using the txn hash. The .anchor folder is unreliable in my experience

**Comment by kre8mymedia** [comment]
@anoushk1234 

You're the man thank you for the help!

![image](https://user-images.githubusercontent.com/40816745/173253217-4bdd4836-6547-460d-ae8f-0b2177ea65ed.png)

![image](https://user-images.githubusercontent.com/40816745/173253229-3cea5b6f-6271-4c2b-a370-a26afc80cc29.png)
