### ISSUE TITLE
`anchor init` does not validate program name

### ISSUE THREAD

**Issue by AdithyaNarayan** [project-serum/anchor#1942]
Rust modules and struct names only support Unicode XID characters (numbers, `-`, `_`, or most letters)

However, this naming rule isn't validated when `anchor init` is run

## Example
```
anchor init invalid_program.name
```
### Excepted Behaviour
Error displayed during `init` command

### Actual Behaviour
`init` command runs successfully and generates code that produces error when running `anchor build` or `anchor test` afterwards

**Comment by callensm** [comment]
this would be a simple regular expression check addition to these existing name checks:
https://github.com/project-serum/anchor/blob/master/cli/src/lib.rs#L521-L530

**Comment by 0xdeepmehta** [comment]
we can also leverage [unicode-xid](https://github.com/unicode-rs/unicode-xid) here, wdyt?

```rust
for char in name.chars() {
    if !UnicodeXID::is_xid_start(char) {
        return Err(anyhow!(
            "Invalid special character, name your project something else!"
        ));
    }
}
```

**Comment by tomlinton** [comment]
Put up another approach in #1949
