### ISSUE TITLE
I used init_if_needed with anchor 0.24.2, but it shows following issue

### ISSUE THREAD

**Issue by cryptoSyndrome001** [project-serum/anchor#1948]
init_if_needed requires that anchor-lang be imported with the init-if-needed cargo feature enabled. Carefully read the init_if_needed docs before using this feature to make sure you know how to protect yourself against re-initialization attacks.rustc

**Comment by armaniferrante** [comment]
As the message says, please enable the `init-if-needed` feature in your Cargo.toml.
