### ISSUE TITLE
Multiple instructions

### ISSUE THREAD

**Issue by AlandKM** [project-serum/anchor#1951]
How can i execute multiple instructions in a single transaction? [This method](https://github.com/project-serum/anchor/issues/1630) seems to not work anymore im getting this error:

`Argument of type 'MethodsBuilder<Idl, IdlInstruction & { name: string; }>' is not assignable to parameter of type 'Transaction | TransactionInstruction | TransactionInstructionCtorFields'.ts(2345)`

my code:
`const tx = new Transaction();`
`tx.add( await program.methods.sendPost(topic, content, 'username').accounts({
            author: wallet.publicKey.toBase58(),
            post: post.publicKey.toBase58(),
        }).signers([post]));
`

**Comment by callensm** [comment]
its because the last function call in the inner chain is `.signers` which returns `MethodsBuilder` in order to maintain chain-ability in the function calls. if you want to construct an instruction to add into a transaction, you need to end the chain with `.instruction()`.

```ts
const tx = new Transaction();
tx.add(
  await program
    .methods
    .sendPost(topic, content, 'username')
    .accounts({ author: wallet.publicKey.toBase58(), post: post.publicKey.toBase58() })
    .signers([post])
    .instruction()
);
```

**Comment by armaniferrante** [comment]
Thanks @callensm for the answer. @AlandKM if you have further questions, please join discord.
