### ISSUE TITLE
temporary value dropped while borrowed

### ISSUE THREAD

**Issue by black-wyvern-dev** [project-serum/anchor#1956]
Hi, I want to make seeds from the seed and bumps.
```
let seeds = &[
            GLOBAL_AUTHORITY_SEED.as_bytes(),
            collection_id.to_string().as_bytes(),
            &[global_bump],
        ];
```
then, I got this error:
error: temporary value dropped while borrowed
label: creates a temporary which is freed while still in use
note: consider using a `let` binding to create a longer lived value
label: creates a temporary which is freed while still in use

**Comment by fanatid** [comment]
```rust
let cid = collection_id.to_string();
let seeds = &[
            GLOBAL_AUTHORITY_SEED.as_bytes(),
            cid.as_bytes(),
            &[global_bump],
        ];
```
