### ISSUE TITLE
Invalid arguments: config not provided

### ISSUE THREAD

**Issue by Morwors** [project-serum/anchor#1960]
Hi and sorry if this isn't the place for this. I am currently trying to create a program transaction but I'm getting the following error:

Error: Invalid arguments: config not provided.

The following is my code

        const transaction = program.transaction.mintNft(v, !1, u || null, {
            accounts: {
                config: config,  //Says this isn't being provided
                ...
            }});
            
Is this a bug or am I not providing config the right way.

Thanks in advance!

**Comment by armaniferrante** [comment]
Please add this question in discord. It's likely user error. If there's reason to think otherwise, please re-open.
