### ISSUE TITLE
Docs incorrectly state that `token::mint & token::authority` can be used without `init` 

### ISSUE THREAD

**Issue by Henry-E** [project-serum/anchor#1961]
Just highlight a possibly incorrect part of the docs
https://github.com/project-serum/anchor/blob/8f7572e8afc713261ad1060437de72a9025ede43/lang/derive/accounts/src/lib.rs#L480-L482

Just tried to do `token::mint == quote_mint` and got an `init must be provided before token` compile error. Which implies that it's not possible to just use a subset of the constraints without `init`.

**Comment by lincot** [comment]
Try updating. It should work on anchor 0.24 (see #1505).

**Comment by Henry-E** [comment]
I just check and I'm on 24.2

**Comment by Henry-E** [comment]
Ah you're right. My CLI says I'm on 24.2 but the project is still compiling with 22. Thanks!
