### ISSUE TITLE
Provide A Way To Disable The "Unsafe Accounts" Check

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#1964]
While this feature certainly has its use, as a seasoned anchor user I find not being able to disable this lint extremely annoying.  It just leads to people (I do this, and have seen public code bases doing this) literally just using `/// CHECK: .` to silence the error.

It makes sense it have it enabled by default, but there shouldn't be any reason to not allow disabling this check. For example using typed accounts like `AccountLoader`, `Account<'info, TokenAccount>` etc.. can increase stack usage by a few bytes. Providing a regular `AccountInfo` can allow reducing the stack size, which is extremely useful with fairly complex instructions, etc..

Forgetting about this lint (or for example when upgrading programs to anchor versions using the lint) makes devex annoying. Nothing like a multi-minute compilation failing because you missed a `/// CHECK: .`, fix it, invoke another multi-minute compilation, only to fail again because the linting error shows 1 error at a time.

**Comment by armaniferrante** [comment]
You can disable it with `anchor build --skip-lint`. Is that sufficient?

**Comment by bonedaddy** [comment]
:facepalm: didnt see that, and yea that works great.
