### ISSUE TITLE
Change the colour of the test titles printed to console

### ISSUE THREAD

**Issue by Henry-E** [project-serum/anchor#226]
In solarized dark theme the test titles are invisible!
![Screenshot 2021-04-26 at 15 00 37](https://user-images.githubusercontent.com/12613144/116095474-5c647e00-a6a0-11eb-8cfa-4e6a1530a283.png)

The only way to view them is by highlighting the text
![Screenshot 2021-04-26 at 15 00 43](https://user-images.githubusercontent.com/12613144/116095470-5bcbe780-a6a0-11eb-9e8c-32a839cb9fae.png)

**Comment by armaniferrante** [comment]
I think this is specific to mocha, since anchor just calls out to it.

**Comment by Henry-E** [comment]
you're right, this is a mocha specific issue.
