### ISSUE TITLE
examples: Escrow example

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#269]
User A constructs an escrow deal:

* SPL token they will give and size
* SPL token counterparty (user B) will give and size
* Can optionally restrict what the pubkey of B is

A can send funds to a program-controlled spl token account using a program instruction at any point
B can send funds at any point.

They can return funds at any point.

If ever both have sent funds, the program sends B's funds to A, A's funds to B, and closes the further use of the deal instance.

(Could also extend this to multiple coins or multiple parties.)

As described by @nishadsingh1.

**Comment by johnrees** [comment]
It might be nice if an escrow example and/or its docs, were somehow linked or comparable to the solana program that gets developed in this tutorial https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction
