### ISSUE TITLE
`anchor init` should default to using typescript instead of javascript

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#275]
Instead of passing `--typescript` to enable typescript, we should default to typescript and pass `--javascript` to disable typescript.

**Comment by AuroraLantean** [comment]
Hi, how can I run anchor test with tests written in typescript? the examples tests are written in JavaScript. I tried 
`anchor test --typescript` and a few others but no success... any idea?

**Comment by armaniferrante** [comment]
> Hi, how can I run anchor test with tests written in typescript? the examples tests are written in JavaScript. I tried
> `anchor test --typescript`, `anchor test -- --typescript `and a few others but no success... any idea?

You can run `anchor init --typescript` or see the the [example](https://github.com/project-serum/anchor/tree/master/examples/typescript).

**Comment by armaniferrante** [comment]
Closed by #889.
