### ISSUE TITLE
Zero Copy Docs "Safety" Link Does Not Work

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#278]
In the docs for zero copy, the [usage](https://docs.rs/anchor-lang/0.5.0/anchor_lang/attr.account.html#usage) section has a link at the bottom for zero copy safety recommendations. Clicking the link does not go anywhere as it appears to reference a local filepath.

**Comment by armaniferrante** [comment]
The link is supposed to link here https://docs.rs/bytemuck/1.5.1/bytemuck/trait.Pod.html#safety.

**Comment by paul-schaaf** [comment]
closing cause this has been fixed
