### ISSUE TITLE
[documentation] zero_copy state strcts have a different syntax (and semantics?) for new() 

### ISSUE THREAD

**Issue by billythedummy** [project-serum/anchor#291]
A struct annotated with `#[state(zero_copy)]` requires a signature of `new(&mut self, ctx: Context<T>)` or `new(&self, ctx: Context<T>)` instead of `new(ctx: Context<T>)` for a non-zero_copy state struct

When the signature for non-zero_copy state structs is used, the compiler throws the following error:
```
error: custom attribute panicked
 --> programs/example_program/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = help: message: Second param must be Context

error: aborting due to previous error
```

IMO the error message is a bit unclear about this requirement.

Additionally I coulnd't find any documentation on this but do #[zero_copy] structs' `new()` have different semantics? Are you just supposed to assign and initialize the fields and return `Ok(())` for a zero_copy state struct as opposed to instantiating it? Because if you did the latter you would be allocating the struct on the stack and run into size limit issues if the struct was large, right?

For example, this is example-4 in the tutorials:

```
#[state]
pub struct Counter {
    pub authority: Pubkey,
    pub count: u64,
}

impl Counter {
    pub fn new(ctx: Context<Auth>) -> Result<Self> {
        Ok(Self {
            authority: *ctx.accounts.authority.key,
            count: 0,
        })
    }
    ...
}
```

Will the zero_copy version of this same state struct look something like this?

```
#[state(zero_copy)]
pub struct Counter {
    pub authority: Pubkey,
    pub count: u64,
}

impl Counter {
    pub fn new(&mut self, ctx: Context<Auth>) -> Result<()> {
        self.authority = *ctx.accounts.authority.key;
        self.count = 0;
        Ok(())
    }
    ...
}
```

**Comment by armaniferrante** [comment]
You are correct see https://github.com/project-serum/anchor/blob/master/examples/zero-copy/programs/zero-copy/src/lib.rs#L30.

The zero copy feature is purposefully not documented right now. It's very experimental and is not in production anywhere.

**Comment by billythedummy** [comment]
I see, thank you! Should I just close this issue then?

**Comment by armaniferrante** [comment]
Yea let's go ahead and close. Thanks for asking.
