### ISSUE TITLE
IDL should be able to translate error enum literal

### ISSUE THREAD

**Issue by jon-chuang** [project-serum/anchor#293]
Currently, errors fail with their Enum value.

This makes it complicated to diagnose the error, one must lookup the error definitions in the original program.

But a cli ought to be able to reexpress program error enum type as their original names.

This could be serviced through proc macros on the enum string literal, which feeds it into the program client/IDL

**Comment by paul-schaaf** [comment]
errors have been reworked and now looking up error definitions in the original program is not necessary anymore so Im closing this
