### ISSUE TITLE
'anchor test' does not deploy program to localnet 'solana-test-validator' cluster

### ISSUE THREAD

**Issue by secretshardul** [project-serum/anchor#323]
`anchor test` runs properly on devnet and on localnet when `solana-test-validator` is not running. However I wish to run it against a `solana-test-validator` localnet cluster because the program will interact with some other predeployed programs.

This gives a `Transaction simulation failed: Attempt to load a program that does not exist` error. The test script doesn't deploy the program as `Deploy success` message is not shown. The address stored in `target/idl/cyclos.json` doesn't show up on localnet Solana explorer.

```sh
(base) hp@MacBook-Pro cyclos % anchor test
BPF SDK: /Users/hp/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
warning: unused variable: `ctx`
 --> programs/cyclos/src/lib.rs:6:23
  |
6 |     pub fn initialize(ctx: Context<Initialize>) -> ProgramResult {
  |                       ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 9.10s

To deploy this program:
  $ solana program deploy /Users/hp/Documents/solana-season-hack/cyclos/target/deploy/cyclos.so


  cyclos
Transaction simulation failed: Attempt to load a program that does not exist 
    
Translating error Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
    at Connection.sendEncodedTransaction (/Users/hp/Documents/solana-season-hack/cyclos/node_modules/@solana/web3.js/src/connection.ts:3357:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Connection.sendRawTransaction (/Users/hp/Documents/solana-season-hack/cyclos/node_modules/@solana/web3.js/src/connection.ts:3318:20)
    at Object.sendAndConfirmRawTransaction (/Users/hp/Documents/solana-season-hack/cyclos/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:25:21)
    at Provider.send (/Users/hp/Documents/solana-season-hack/cyclos/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at Object.rpc [as initialize] (/Users/hp/Documents/solana-season-hack/cyclos/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:32:23)
    1) Is initialized!


  0 passing (5s)
  1 failing

  1) cyclos
       Is initialized!:
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

# Test script in tests/cyclos.spec.ts

```ts
import * as anchor from '@project-serum/anchor'

describe('cyclos', () => {

  anchor.setProvider(anchor.Provider.env());

  it('Is initialized!', async () => {
    const program = anchor.workspace.Cyclos;

    const tx = await program.rpc.initialize();
    console.log("Your transaction signature", tx);
  });
});
```

# Environment

- Anchor 0.6.0
- MacOS Catalina

**Comment by secretshardul** [comment]
Test passes if I use

```sh
anchor deploy && anchor test --skip-deploy --skip-build
```

Is this the intended behavior?

**Comment by armaniferrante** [comment]
If I understand the problem correctly, this is intended. `anchor test` without any arguments will build and deploy programs at *new* addresses on each run. If you want to use a pre-deployed program for your test on an already running localnet, you can update your `Anchor.toml` to set the program.

For example,

```
[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[clusters.localnet]
basic_0 = "BBNZG82FKoqb8hgPL426C1Rwa89zcmQSUjrYx51zcM6M"
```

Would allow one to do what you describe with `examples/tutorial/basic-0/`.

Does this meet your use case? Or do you need to dynamically pass in the address to the cli?

**Comment by secretshardul** [comment]
This solution should work. But I wonder why `anchor test` has different behaviour for  devnet and localnet. When devnet is selected in `Anchor.toml`, the `anchor test` redeploys the program each time. `Attempt to load a program that does not exist` doesn't show up.

**Comment by armaniferrante** [comment]
I see you're correct. To reiterate the points you've made, there are two cases here.

1. The user wants to run `anchor test` against a localnet (launching a validator automatically). In this case, the program should be embedded into the genesis of the local validator (to save time).
2. The user wants to run `anchor test` against a localnet *without* launching a validator automatically. In this case, the flow should work exactly like running `anchor test` against devnet or any other cluster.

This is being addressed here https://github.com/project-serum/anchor/pull/324. Thanks for bringing this up.

**Comment by armaniferrante** [comment]
Completed byhttps://github.com/project-serum/anchor/pull/324.

**Comment by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [comment]
Re: #324 "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." https://github.com/project-serum/anchor/commit/fc9fa90a0b63b6357d050c7a20519aa7a059c3aa 

My context is described here https://github.com/project-serum/anchor/issues/831#issuecomment-1010653240

**Comment by jdaviderb** [comment]
@ANANTASHESHALOKAGREENTARAEGPTRANSHOLON this solved the problem https://github.com/project-serum/anchor/issues/831#issuecomment-1025349658
