### ISSUE TITLE
Fetching program owned accounts in the client

### ISSUE THREAD

**Issue by petscheit** [project-serum/anchor#334]
Hey everybody, 
been working my way through the tutorials and slowly learning. One thing I can't figure out is how to fetch the accounts owned by a program in the client. I've successfully done this by posting a `getProgramAccounts` request to the cluster node with no issues, but can't figure out how to do it with the typescript library natively. Is that feature implemented already or still on the feature list? 

Thanks for the quick progress of anchor, really enjoying it so far!

**Comment by armaniferrante** [comment]
You can't currently get a heterogenous list of all the accounts. You can however get a list of all accounts of a specific type by using

```
await program.account.<myAccount>.all();
```

**Comment by petscheit** [comment]
Exactly what I was looking for. Thanks for the quick reply! I was going to update the docs to mention the method but the deployed TypeDoc doesn't seem to match the current release, so I don't want to muddle around.

**Comment by petscheit** [comment]
Actually, I have one related question if that's ok. When not using associate accounts, to update a user's program account I would fetch the correct account by querying with the authority as a filter and then pass it to the program. Is that the correct way of doing it in Anchor?

**Comment by armaniferrante** [comment]
> Actually, I have one related question if that's ok. When not using associate accounts, to update a user's program account I would fetch the correct account by querying with the authority as a filter and then pass it to the program. Is that the correct way of doing it in Anchor?

Correct. However, in most cases I'd use an associated account for performance (and UX) reasons.
