### ISSUE TITLE
lang: Dynamically fetch rent sysvar for when using `init`.

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#350]
With dynamic sysvars, we can avoid clients having to pass in the rent sysvar. Blocked until this feature is live on mainnet beta.

**Comment by fanatid** [comment]
Is this still blocked?

PR which introduced dynamic sysvars landed to `v1.7`: https://github.com/solana-labs/solana/commit/fa83f3bd738661b38610bb096f84888b669eb9d2
Backported to `v1.6` and available from `v1.6.5`: https://github.com/solana-labs/solana/commit/6da4bec41d45ad16d57963096159ff53615e7cee
Current node stats (https://solanabeach.io/validators):
```
    1.6.20(87.6%)
    1.6.16(8.4%)
    others(4.0%)
```

**Comment by armaniferrante** [comment]
> Is this still blocked?
> 
> PR which introduced dynamic sysvars landed to `v1.7`: [solana-labs/solana@fa83f3b](https://github.com/solana-labs/solana/commit/fa83f3bd738661b38610bb096f84888b669eb9d2)
> Backported to `v1.6` and available from `v1.6.5`: [solana-labs/solana@6da4bec](https://github.com/solana-labs/solana/commit/6da4bec41d45ad16d57963096159ff53615e7cee)
> Current node stats (https://solanabeach.io/validators):
> 
> ```
>     1.6.20(87.6%)
>     1.6.16(8.4%)
>     others(4.0%)
> ```

It is not blocked. The blocker tag currently applied means that it's a requirement for the v1.0.0 release.
