### ISSUE TITLE
Run anchor test for specific program in multiple program project

### ISSUE THREAD

**Issue by lamlephamngoc** [project-serum/anchor#359]
Context: I have many programs in my project, now I would like to run test for specific program so I don't want to build & deploy other programs because it takes times

Problem: Ability to run anchor test for specific a program or a list of program (multiple program) in project

**Comment by armaniferrante** [comment]
As discord on Discord, one can now run `anchor build -p <program-name>` and `anchor test <test-file-name>`.  Changes here https://github.com/project-serum/anchor/pull/362.
