### ISSUE TITLE
Chunk get multiple accounts

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#364]
Automatically chunk requests for get multiple accounts if the number of accounts is over 100 https://github.com/project-serum/anchor/blob/master/ts/src/utils/rpc.ts#L4

**Comment by armaniferrante** [comment]
There's an implementation of this here https://github.com/solana-labs/dapp-scaffold/blob/eef68f4a46717b81549211594334d98bf358f87d/src/contexts/accounts.tsx#L432.

**Comment by xcjaa** [comment]
What does this achieve? I tried calling it on over 1000 accounts and it works fine.

**Comment by armaniferrante** [comment]
> What does this achieve? I tried calling it on over 1000 accounts and it works fine.

My understanding is that the JSON RPC api is limited to 100 accounts. Has that changed?

**Comment by xcjaa** [comment]
I see, I think there isn't a limit on the local validator but

"Default max is 100, by it can be overridden for a specific validator instance by the --rpc-max-multiple-accounts command-line argument"

I'll take this :)

**Comment by xcjaa** [comment]
My bad, I was using `getProgramAccounts` which doesn't seem to have this same limit.

**Comment by armaniferrante** [comment]
Closed by #763.
