### ISSUE TITLE
Confirmation speed

### ISSUE THREAD

**Issue by petscheit** [project-serum/anchor#396]
I'm currently wondering why it takes so long for the `txSig` to be returned when sending a transaction, takes around 5 secs for me currently. Is the `txSig` only returned once the max number of confirmations have been reached? I'm wondering a bit because serum and other solana based apps feel very snappy, while my application is slow. Or are these apps taking an optimistic approach, updating the local application once the tx simulation has passed?  Tried this on localnet and devnet. Any insight would be greatly appreciated!

**Comment by armaniferrante** [comment]
You can use a more optimistic `ConfirmOptions` parameter when constructing your [Provider](https://project-serum.github.io/anchor/ts/classes/provider.html#constructor) or making an RPC via [Context](https://project-serum.github.io/anchor/ts/index.html#context).
