### ISSUE TITLE
How to use beneficiary to find member address?

### ISSUE THREAD

**Issue by yasuoyuhao** [project-serum/anchor#403]
Hey, I use and study [this example](https://github.com/project-serum/anchor/blob/master/examples/lockup/tests/lockup.js).
I have some trouble, How to use beneficiary to find member address? or any find beneficiary's member address method?

Thank you for your time, Solana is great.

[lockup](https://github.com/project-serum/anchor/blob/master/examples/lockup/tests/lockup.js)

**Comment by armaniferrante** [comment]
Good way that's not implemented

* use a deterministic program derived address with the member address as the seed.

Bad way that's implemented:

Use `getProgramAccounts` with a filter. In anchor you can do this with: `program.account.member.all(Buffer.concat([registarar.toBuffer(), beneficiary.toBuffer()]));`, where the registrar and beneficiary are public keys.

**Comment by armaniferrante** [comment]
Closing since issues are for dev related purposes.
