### ISSUE TITLE
Fallback functions

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#409]
As requested by @bonedaddy 

> I want to proxy all non matching instructions to a program but essentially append an extra account into the existing accounts before proxying the instruction. Basically like ethereums proxy contracts.

The syntax might look like this. 

```rust
#[program]
mod program {
  #[fallback]
  pub fn my_handler<'info>(program_id: &Pubkey, accounts: &[AccountInfo<'info>], data: &[u8]) -> Result<()> {
      ...
  }
}
```

**Comment by bonedaddy** [comment]
Are you able to provide a high-level overview of what needs to be changed to accomplish this? Functionality exactly like this is needed for a project I'm working on so I would be happy to add such functionality to anchor.

**Comment by armaniferrante** [comment]
The syntax in #457 omits the need to have a `#[fallback]` macro. Instead it asserts *at most* a single function in the program mod omits the `Context` object and thus treats it as a fallback function, passing through all the raw `entrypoint` args, as shown in the example above.
