### ISSUE TITLE
lang: Build should error when PDA payer is not marked mutable

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#418]
We should be able to parse the accounts at compile time and inspect the payer field to ensure it's marked mutable, giving the developer a more informative error than the current `Cross-program invocation with unauthorized signer or writable account`.

**Comment by iurage** [comment]
-> Anchor should check that the Payer is both mutable and a Signer at compile time to avoid this issue.

Ran into this problem earlier when executing an instruction with CPI using Multisig Program. This mutable/signer check does not show up when executed with the Anchor client, so some discrepancy there.

**Comment by paul-schaaf** [comment]
closed by https://github.com/project-serum/anchor/pull/1271
