### ISSUE TITLE
Event decode has uncaught error for invalid base64 log

### ISSUE THREAD

**Issue by xjcaa** [project-serum/anchor#419]
So I've been playing with events, and I thought my issue was related to this issue: 

https://github.com/project-serum/anchor/issues/356

But I did some further digging and it seems like this line silently fails / hangs, and I'm not sure as to why it happens. 
This would stop the EventParser from processing the log with the emitted event if it was after one of these lines.

I don't think the contents of the log matter, I tried "helloworld", and some other strings with white spaces and numbers.

https://github.com/project-serum/anchor/blob/master/ts/src/coder/event.ts#L50

In my local node_modules in the @project-serum/dist/cjs/coder/event.js, I added this

```
decode(log) {
        console.log("**DECODE**");
        console.log("**ToByteArray**", base64.toByteArray(log));
        const logArr = Buffer.from(base64.toByteArray(log));
```

And when running my test code, I would just see it fail to call `base64.toByteArray(log)`

```
**DECODE**
    ✔ Test (410ms)
```

This probably isn't an anchor issue, but putting it out there.

**Comment by xcjaa** [comment]
Temp fix is just to not log anything in your program and just emit events.

**Comment by armaniferrante** [comment]
I think the problem is that it throws an error that isn't caught so the test doesn't exit cleanly. Instead of not logging anything in the program we probably just need to catch the error for an invalid base64 log and then skip it on the client.
