### ISSUE TITLE
lang: Cpi generated client should validate the program id of the cpi context

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#424]
We should consider requiring the program to use `solana_program::declare_program_id!("")` and using that value to validate the program given to the cpi context.

**Comment by armaniferrante** [comment]
Closed by #686.

**Comment by fanatid** [comment]
Does this change any part of IDL? Like `metadata.address` (IIRC) which is used in tests?

**Comment by armaniferrante** [comment]
> Does this change any part of IDL? Like `metadata.address` (IIRC) which is used in tests?

Not currently, though now that it's expected for a program to define a program id, we might want to define an address section in the IDL. Currently the metadata is just used as an internal CLI detail.
