### ISSUE TITLE
lang: Create accounts for the associated token program

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#434]
The existing token constraint should create SPL token accounts for the associated token program when both `seeds` and `associated` is omitted. 

Currently, the program derived addresses that are created are derived from the executing program, which is more convenient when you have a single PDA account owning multiple vaults of the same mint. However, we should also provide the ability to create standard ATAs in addition to the ability to validate the address (when init is omitted).

Concretely,

```rust
#[account(init, token = <mint-target>, authority = <authority-target>, payer = <payer-target>)]
```

Should create an associated token account using the associated token program, and

```rust
#[account(token = <mint-target>, authority = <authority-target>)]
```

Should validate the address is correct.

In both cases, both `seeds` and `associated` should *not* be in the list of constraint keywords.

**Comment by armaniferrante** [comment]
Labeling as priority 2 until there is demand for the feature.

**Comment by paul-schaaf** [comment]
we now have an API for creating associated token accounts so Im closing this
