### ISSUE TITLE
Accounts: difference between `has_one` and `belongs_to`?

### ISSUE THREAD

**Issue by fanatid** [project-serum/anchor#435]
Currently `anchor` have two attributes for `Attribute` derive macro: `has_one` and `belongs_to`. Doc for `has_one`:
```
Semantically different, but otherwise the same as belongs_to.
````
In the source code, we have only `BelongsTo`. Maybe it worth left only one and deprecate another? Allowing to developer do same thing by two different attribute does not looks good =\

**Comment by armaniferrante** [comment]
Agreed we should remove one. I'm in favor for keeping `has_one` and removing `belongs_to`. What do others think?

**Comment by fanatid** [comment]
I'm ok with `has_one`. Maybe start the poll in the `anchor` channel in discord with pinning `@everyone`?
