### ISSUE TITLE
Anchor Rust Client Request Builder Constructs Signers Vector With Incorrect Order

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#442]
The anchor rust client when sending a transaction via the request builder constructs the signers vector in the [wrong order](https://github.com/project-serum/anchor/blob/master/client/src/lib.rs#L448-L449) when an instruction requires more than one signer resulting in the following error:

```
thread 'main' panicked at 'Transaction::sign failed with error KeypairPubkeyMismatch', /home/solidity/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-sdk-1.7.3/src/transaction.rs:257:13
```

This happens because the first signer is the account paying for the transaction, and when constructing a signed transaction the position of the account signers is validated. I've copied the relevant transction signing code segments below and annotated them 

```rust
    pub fn try_partial_sign<T: Signers>(
        &mut self,
        keypairs: &T,
        recent_blockhash: Hash,
    ) -> result::Result<(), SignerError> {
        // position of signer keys are retrieved
        let positions = self.get_signing_keypair_positions(&keypairs.pubkeys())?;
        // position validation is done here, and fails 
        if positions.iter().any(|pos| pos.is_none()) {
            return Err(SignerError::KeypairPubkeyMismatch);
        }
        let positions: Vec<usize> = positions.iter().map(|pos| pos.unwrap()).collect();
        self.try_partial_sign_unchecked(keypairs, positions, recent_blockhash)
    }

    pub fn get_signing_keypair_positions(&self, pubkeys: &[Pubkey]) -> Result<Vec<Option<usize>>> {
        if self.message.account_keys.len() < self.message.header.num_required_signatures as usize {
            return Err(TransactionError::InvalidAccountIndex);
        }
        // signed keys are pulled here, and the first one is the transaction payer
        let signed_keys =
            &self.message.account_keys[0..self.message.header.num_required_signatures as usize];

        Ok(pubkeys
            .iter()
            .map(|pubkey| signed_keys.iter().position(|x| x == pubkey))
            .collect())
    }
```

**Comment by fanatid** [comment]
Can you point on the line / part of the code where the payer position is important? `Transaction` code only check that all required keypairs are passed.

**Comment by bonedaddy** [comment]
* https://github.com/solana-labs/solana/blob/master/sdk/src/transaction.rs#L413-L424
* https://github.com/solana-labs/solana/blob/master/sdk/src/transaction.rs#L313-L324

**Comment by fanatid** [comment]
@bonedaddy This is the same code that you pasted, I checked it and checked `transaction.rs` source code. That's why I asked line.

`get_signing_keypair_positions` match required signing keys to passed keypairs producing `Vec<Option<usize>>`, `None` in case if keypair do not match any required sign key.
`try_partial_sign` thrown `KeypairPubkeyMismatch` only if `None` exists in resulted `Vec`.

How payer position can throw an error here?

**Comment by bonedaddy** [comment]
I believe the error stems from [this](https://github.com/solana-labs/solana/blob/master/sdk/src/transaction.rs#L422) because the positions are out-of ordered, and according to the docs for [position](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position):

>  position() takes a closure that returns true or false. It applies this closure to each element of the iterator, and if one of them returns true, then position() returns Some(index). **If all of them return false, it returns None**.


* https://github.com/solana-labs/solana/blob/master/sdk/src/transaction.rs#L319-L321

**Comment by fanatid** [comment]
An order does not matter. `position()` will return `None` only if not required keypair is passed. Please check your keys or paste an example for reproducing.

**Comment by bonedaddy** [comment]
You are right it doesn't appear to matter i was unable to reproduce with a minimal program. I double checked my keys, and they seem to be correct. Removing the `.signer()` from the request builder statement where i provide the secondary signer causes the transaction to fail due to a missing signer so that seems to verify the keys are correct. Anyways I'll close this issue and the PR
