### ISSUE TITLE
cli: deploy.ts doesn't compile with tsconfig.json

### ISSUE THREAD

**Issue by cheaney** [project-serum/anchor#472]
During `anchor migrate`, when the `deploy.ts` is [compiled](https://github.com/project-serum/anchor/blob/master/cli/src/main.rs#L1478), it doesn't use the `tsconfig.json`. If you pass a specific file to `tsc`, it doesn't use the project `tsconfig.json`. See [here](https://github.com/microsoft/TypeScript/issues/6591).

Two solutions come to mind:
1. Run `tsc` without specifying `deploy.ts` and compile all the `ts` files in project
2. Add a `tsconfig.json` to the `migrations` directory and run `tsc` without specifying `deploy.ts`

**Comment by cheaney** [comment]
@Standaa would be interested to hear your thoughts on this since you added the ts support for migrations. Also @NorbertBodziony since you added ts support for tests.

**Comment by cheaney** [comment]
Another option:
- Add `ts-node` as a dependency
- Run `ts-node migrations/deploy.ts`

**Comment by armaniferrante** [comment]
> Another option:
> 
> * Add `ts-node` as a dependency
> * Run `ts-node migrations/deploy.ts`

I'm not very familliar with `ts-node` but this feels like the smoothest option.

**Comment by NorbertBodziony** [comment]
Personally, i have been using `ts-node migrations/deploy.ts`

**Comment by cheaney** [comment]
That's how I got it to work on my project as well 😅 I will make a PR to update `anchor migrate` to use `ts-node migrations/deploy.ts`

**Comment by armaniferrante** [comment]
Done by #477.
