### ISSUE TITLE
lang: Initialize mint from accounts context

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#479]
Consider adding an init mint api to the derive Accounts macro similar to how we have the ability to initialize token accounts.

**Comment by Henry-E** [comment]
Info from Armani about how this might work


* Parser: Step 1. https://github.com/project-serum/anchor/blob/master/lang/syn/src/parser/accounts/constraints.rs#L174. Step 2. https://github.com/project-serum/anchor/blob/master/lang/syn/src/parser/accounts/constraints.rs#L243
* Codegen: https://github.com/project-serum/anchor/blob/master/lang/syn/src/codegen/accounts/constraints.rs#L435


The parser has two steps:

1. Parse each syntax-token individually and throw it into a builder.
2. Use the builder to aggregate all the tokens into individual constraints.

So for "constraints" with multiple keywords, like seeds, associated, token, etc, the second merging phase is important to ensure the syntax is properly formed. For example, if init, seeds is provided, then payer must also be provided, which is enforced here https://github.com/project-serum/anchor/blob/master/lang/syn/src/parser/accounts/constraints.rs#L264

**Comment by RohanKapurDEV** [comment]
Should probably close this
