### ISSUE TITLE
addEventListener creates an event parser and subscribes to onLogs per listener

### ISSUE THREAD

**Issue by xjcaa** [project-serum/anchor#493]
Currently `Program.addEventListener` creates a new EventParser for each listener which will all independently parse logs for the specified event. This may cause some issues if you want to listen to multiple events from a single client.

Instead, there should be a map lookup for callbacks, such that the code here:
https://github.com/project-serum/anchor/blob/master/ts/src/program/index.ts#L311-L323

Looks more like:
```
self.eventParser.parseLogs(logs.logs, (event) => {
  if (event.name in self.callbacks) {
    self.callbacks[event.name](event.data, ctx.slot);
  }
});
```

We would only add a single subscription to onLogs, and remove this once the map is empty.

**Comment by steveluscher** [comment]
This all ready to close?

**Comment by paul-schaaf** [comment]
seems so!
