### ISSUE TITLE
illegal hardware instruction  solana-test-validator

### ISSUE THREAD

**Issue by nhamthanh** [project-serum/anchor#504]
I am using Mac M1 Big Sur 11.4, solana-cli 1.7.3, After using rosetta 2 and install openssl@1.1 with homebrew 3.2. 
I run Solana-test-validator and It occur error
 `Ledger location: test-ledger
Log: test-ledger/validator.log
⠙ Initializing...
zsh: illegal hardware instruction  solana-test-validator`

Do I need to re-install solana and rust on terminal rosetta (due to I install it on my default terminal) ? By the way, I can not found command to uninstall solana.

**Comment by fanatid** [comment]
This is not an `anchor` issue, `solana` still does not work properly on M1. There a lot of issues, while most of them are closed and code can be compiled, execution usually fails: https://github.com/solana-labs/solana/issues?q=m1

Better use x86_64 for some time...

**Comment by nhamthanh** [comment]
Sorry, I will move it to solana lab and closed this issue.
