### ISSUE TITLE
bump keyword is not working as expected

### ISSUE THREAD

**Issue by antoineherzog** [project-serum/anchor#521]
We are writing a small anchor program for Crypto Please and we would like to advantage of the bump keyword to create the main data account with PDA during init function.

Following your example in version 0.11.1, I wrote:

```
#[instruction(domain: String, seed: Vec<u8>, bump: u8)]
pub struct Init<'info> {
    // Main Data Acccount being created.
    #[account(
        init,
        seeds = [b"my-seed", domain.as_bytes()],
        bump = bump,
        payer = payer,
    )]
...
```
and It gives me an error during compilation time:

```
solana program deploy /Users/antoineherzog/Documents/GitHub/push-notification-solana/pushnotification/target/deploy/pushnotification.so
thread 'main' panicked at 'Code not parseable: Error("Invalid attribute")', lang/syn/src/idl/file.rs:350:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

if I remove the bump keyword, the program compile successfully.

**Comment by armaniferrante** [comment]
What version is your CLI on?

**Comment by antoineherzog** [comment]
anchor-cli 0.9.0

Should I upgrade it?

**Comment by armaniferrante** [comment]
> anchor-cli 0.9.0
> 
> Should I upgrade it?

Yes. The CLI should be the same version as the crate being used.

**Comment by antoineherzog** [comment]
Ok! doing it now.

**Comment by antoineherzog** [comment]
The error disappeared then. Thank you!
