### ISSUE TITLE
ts: Provide ability to turn off console.logs of instructions logs for transaction errors

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#532]
The client currently automatically outputs all program logs when the transaction fails. We should add settings that disables this, which may be useful when testing sad paths where one expects an error.

This can be done with [features](https://github.com/project-serum/anchor/blob/master/ts/src/utils/features.ts).

**Comment by theycallmeswift** [comment]
@armaniferrante can you mark this as closed? Didn't get pulled in automatically
