### ISSUE TITLE
ts: Instruction decoder should decode hex strings

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#545]
Currently it decodes Buffer's and base 58 strings. Instead of base 58 it should decode hex by default. To decode base58, an optional parameter should be passed in describing how to interpret the string.
 
 See https://github.com/project-serum/anchor/blob/master/ts/src/coder/instruction.ts#L112.

**Comment by masonwoodford** [comment]
Hello could I work on this?

**Comment by armaniferrante** [comment]
> Hello could I work on this?

Please do!

**Comment by masonwoodford** [comment]
> > Hello could I work on this?
> 
> Please do!

Apologies I am new to contributing, I didn't realize this was in Rust, I had thought Python! I don't think I'll be able to figure this out, sorry about that! You can delete my comments to not confuse others if you want.

**Comment by fanatid** [comment]
I'll submit PR for this issue today.
