### ISSUE TITLE
cli: configurable program address?

### ISSUE THREAD

**Issue by fanatid** [project-serum/anchor#551]
Can we add an optional program address to the config that will be used for deploying the program on tests? Right now new address is generated each time.

Which section would be good for this?

**Comment by armaniferrante** [comment]
We can re-use the `[clusters.<network>]` table for this. https://github.com/project-serum/anchor/blob/f067624adda95e18467c735c29c72197d0e2120a/examples/cfo/Anchor.toml#L6

Currently, this is just used to add external  programs to the workspace. But it seems natural to also use it for this purpose.
