### ISSUE TITLE
Potential Bug in `Lockup` Program

### ISSUE THREAD

**Issue by kobby-pentangeli** [project-serum/anchor#553]
In several function calls throughout the [Lockup program](https://github.com/project-serum/anchor/blob/master/examples/lockup/programs/lockup/src/lib.rs#L118), there are instances where seeds are generated, for example:

```rust
        let seeds = &[
            ctx.accounts.vesting.to_account_info().key.as_ref(),
            &[ctx.accounts.vesting.nonce],
        ];
        let signer = &[&seeds[..]];
```

When a field has type `CpiAccount`, calling `.to_account_info()` works; however, when the field's type is `ProgramAccount`, as is the case for the `vesting` field of the `Withdraw` struct, it doesn't work. Rust Analyzer in VS Code shows that the `.to_account_info()` called on `vesting`, `nonce`, `key` and ultimately, the `seeds` variable in the above snippet are all unknown at compile time.

**Comment by armaniferrante** [comment]
This sounds like a bug in VSCode not the program.

**Comment by kobby-pentangeli** [comment]
Although IntelliJ IDEA has similar issue, I'm inclined to agree with you because building the program doesn't produce any errors.

**Comment by armaniferrante** [comment]
Closing as the program does indeed compile and runs in CI.
