### ISSUE TITLE
Not in anchor workspace

### ISSUE THREAD

**Issue by AuroraLantean** [project-serum/anchor#558]
Hi I copied an anchor github repo https://github.com/Henry-E/dog-money
then pasted it into the downloaded anchor repo/examples/
then opened the terminal to issue this command "anchor test" in that dog-money folder, 
then it gave me "Not in anchor workspace."
What did I miss? Please help.

**Comment by armaniferrante** [comment]
The Anchor.toml for that example is invalid (it's now out of date). It needs to be updated to

```
[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"
```

**Comment by AuroraLantean** [comment]
I works!! Thank you! I added [provider] so mine looks this way:
```
[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
```
