### ISSUE TITLE
Unable to build using anchor

### ISSUE THREAD

**Issue by sushantburnawal** [project-serum/anchor#565]
Unable to build using anchor, geting the error below
![image](https://user-images.githubusercontent.com/41643862/127732321-f7ed39ad-f34f-4ce9-b96f-f4efc01e2c29.png)

**Comment by fanatid** [comment]
This should be resolved https://github.com/project-serum/anchor/issues/538.
Please make sure that you have this commit.

**Comment by armaniferrante** [comment]
`solana-frozen-abi v1.7.9` was released tonight and may have broken the build.

**Comment by sushantburnawal** [comment]
so what's the solution here ?? How should I solve this problem

**Comment by sushantburnawal** [comment]
> `solana-frozen-abi v1.7.9` was released tonight and may have broken the build, since the examples aren't locked.

so how can solve this ??

**Comment by dovahcrow** [comment]
> `solana-frozen-abi v1.7.9` was released tonight and may have broken the build, since the examples aren't locked.

BTW why did I only find the version 1.7.0 and version 1.8.0 of solana-frozen-abi in Solana's github (https://github.com/solana-labs/solana/blob/master/frozen-abi/Cargo.toml#L3) but on crates.io they magically have the version 1.7.9.

**Comment by dovahcrow** [comment]
> so what's the solution here ?? How should I solve this problem

Adding `solana-frozen-abi = "=1.7.8"` to your program's Cargo.toml temporarily solved the problem.

**Comment by sushantburnawal** [comment]
@dovahcrow  where did you add the statement `solana-frozen-abi = "=1.7.8" `, I mean under what manifest key??

**Comment by sushantburnawal** [comment]
also there are two cargo.toml files which one should I change?

**Comment by sushantburnawal** [comment]
Thanks @dovahcrow ...it solved the problem

**Comment by michaelhly** [comment]
> > `solana-frozen-abi v1.7.9` was released tonight and may have broken the build, since the examples aren't locked.
> 
> BTW why did I only find the version 1.7.0 and version 1.8.0 of solana-frozen-abi in Solana's github (https://github.com/solana-labs/solana/blob/master/frozen-abi/Cargo.toml#L3) but on crates.io they magically have the version 1.7.9.

Can we re-open this issue? The suggested solution is only a workaround, not a permanent solution.

**Comment by armaniferrante** [comment]
> > > so what's the solution here ?? How should I solve this problem
> > 
> > 
> > Adding `solana-frozen-abi = "=1.7.8"` to your program's Cargo.toml temporarily solved the problem.
> > @sushantburnawal
> 
> ~Can we re-open this issue? The suggested solution is only a workaround, not a permanent solution.~
> 
> Bumping Solana to v1.7.8 solved the issue.

We'll probably have to pin in anchor_lang similar to what we did in https://github.com/project-serum/anchor/pull/539 until this is fixed on the solana end (via a rust version upgrade).

**Comment by andreihrs** [comment]
make sure to have the latest solana-cli version (1.7.10). With the 1.6.2 version, the build was still failing, even with thesolana-frozen-abi = "=1.7.8 workaround.
