### ISSUE TITLE
Error processing Instruction 0: custom program error: 0xa1 Decimal 161

### ISSUE THREAD

**Issue by AuroraLantean** [project-serum/anchor#581]
Hi I see Anchor package has just been updated to 0.12.0, so I have updated the Rust program dependencies to Anchor 0.12.0 in the Cargo.toml file:
[dependencies]
anchor-lang = "0.12.0"
anchor-spl = "0.12.0"

And updated Anchor.toml...
And also updated project-serum/anchor to 0.12.0

Then updated the Rust program as below according to the latest IpoPool example in the Anchor examples:
const provider = anchor.Provider.local();
anchor.setProvider(provider);

Replace "program.provider" by "provider"

const usdcMint = await createMint(provider);
const dataAccount = anchor.web3.Keypair.generate();

await program.rpc.initializeUser(.. {},
//signers: [dataAccount],
//instructions: [await program.account.dataAccount.//createInstruction(dataAccount)],
)

Please see my forked repo: https://github.com/AuroraLantean/SolanaAnchorDemo1
$ yarn install
$ yarn run t1
... this should give you a successful test result for MeMe-Num tutorial.

$ yarn run t2
... this will give you an error below for Dog Money tutorial.
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1
Program 3iz9W2uXTYCSvpxaX5jMPqcyb9Vx5rTxATTXJR1Jt9VX invoke [1]
Program log: Custom program error: 0xa1
Program 3iz9W2uXTYCSvpxaX5jMPqcyb9Vx5rTxATTXJR1Jt9VX consumed 5320 of 200000 compute units
Program 3iz9W2uXTYCSvpxaX5jMPqcyb9Vx5rTxATTXJR1Jt9VX failed: custom program error: 0xa1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1
at Connection.sendEncodedTransaction (.../node_modules/@solana/web3.js/lib/index.cjs.js:4882:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Connection.sendRawTransaction (.../node_modules/@solana/web3.js/lib/index.cjs.js:4841:20)
at async Object.sendAndConfirmRawTransaction (.../node_modules/@solana/web3.js/lib/index.cjs.js:6668:21)
at async Provider.send (.../node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
at async Object.rpc [as initializeUser] (.../node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
at async Context. (.../dog-money/tests/dog-money.js:57:5) {
logs: [
'Program 3iz9W2uXTYCSvpxaX5jMPqcyb9Vx5rTxATTXJR1Jt9VX invoke [1]',
'Program log: Custom program error: 0xa1',
'Program 3iz9W2uXTYCSvpxaX5jMPqcyb9Vx5rTxATTXJR1Jt9VX consumed 5320 of 200000 compute units',
'Program 3iz9W2uXTYCSvpxaX5jMPqcyb9Vx5rTxATTXJR1Jt9VX failed: custom program error: 0xa1'
]
}

0xa1 in hex is 161 in decimal
From your instruction of finding the error code:
https://www.notion.so/Debugging-Custom-Anchor-Errors-b8540dd418c44a4e939ab17c56a3fd3b
https://github.com/project-serum/anchor/blob/master/lang/src/error.rs
but I could not find the error code for 161... please help! Thank you

**Comment by michaelhly** [comment]
This is your error:
https://github.com/project-serum/anchor/blob/0b077c4b349b2888afbad50aacfee058469fabbd/lang/src/error.rs#L54

**Comment by AuroraLantean** [comment]
HI, According to https://project-serum.github.io/anchor/tutorials/tutorial-1.html#initialize-instruction, it seems I need to add this #[account(init)] on one of the InitializeUser struct's fields, and I tried it with no success...
Now I have even reduced the program code to:

```
#[program]
pub mod dog_money {
    use super::*;
    pub fn initialize_user(ctx: Context<InitializeUser>) -> ProgramResult {
        Ok(())
    }
}
#[derive(Accounts)]
pub struct InitializeUser<'info> {
    //#[account(init)]
    program_signer: AccountInfo<'info>,
    #[account(associated = authority, with = usdc_mint)]
    user_data: ProgramAccount<'info, UserData>,
    #[account(signer)]
    authority: AccountInfo<'info>,
    usdc_mint: CpiAccount<'info, Mint>,
    rent: Sysvar<'info, Rent>,
    system_program: AccountInfo<'info>,
}
#[associated]//#[account]
pub struct UserData {
    pub first_deposit: i64,
}
```

And with Anchor testing code:

```
    await program.rpc.initializeUser({
      accounts: {
        programSigner,
        userData,
        authority: provider.wallet.publicKey,
        usdcMint,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        systemProgram: anchor.web3.SystemProgram.programId,
        clock: anchor.web3.SYSVAR_CLOCK_PUBKEY,
      },
      // signers: [dataAccount],
      // instructions: [await program.account.userData.createInstruction(dataAccount)],
    });
```

Any idea where the bug is? Thank you

**Comment by AuroraLantean** [comment]
Also I have tried it:
#[account(associated = authority, with = usdc_mint, init)]
...
#[associated]
pub struct UserData {
pub first_deposit: i64,
}

Then I got this:
error[E0599]: no function or associated item named default found for struct UserData in the current scope
--> programs/dog-money/src/lib.rs:14:10
|
14 | #[derive(Accounts)]
| ^^^^^^^^ function or associated item not found in UserData
...
41 | pub struct UserData {
| ------------------- function or associated item default not found for this
|
= help: items from traits can only be used if the trait is implemented and in scope
= note: the following trait defines an item default, perhaps you need to implement it:
candidate #1: Default
= note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
Any idea?

**Comment by AuroraLantean** [comment]
Hi I got it

```
#[derive(Accounts)]
pub struct InitializeUser<'info> {
    program_signer: AccountInfo<'info>,
    #[account(associated = authority, with = usdc_mint, init)] //ADD ", init"
...
}

#[associated]
pub struct UserData {
    pub first_deposit: i64,
}
impl Default for UserData {
  fn default() -> UserData { 
    UserData{
      __nonce: 0,
      first_deposit: 0,
    }
  }
}
```
Thank you so much!

**Comment by armaniferrante** [comment]
> Hi I got it
> 
> ```
> #[derive(Accounts)]
> pub struct InitializeUser<'info> {
>     program_signer: AccountInfo<'info>,
>     #[account(associated = authority, with = usdc_mint, init)] //ADD ", init"
> ...
> }
> 
> #[associated]
> pub struct UserData {
>     pub first_deposit: i64,
> }
> impl Default for UserData {
>   fn default() -> UserData { 
>     UserData{
>       __nonce: 0,
>       first_deposit: 0,
>     }
>   }
> }
> ```
> 
> Thank you so much!

I would recommend to not use `associated` and instead to use `seeds`. `associted` in its current form will be removed.

**Comment by armaniferrante** [comment]
Can we close this issue?

**Comment by AuroraLantean** [comment]
Hi, how can I use seeds macro? I could not find that in the docs. I have tried those:
#[account(seeds = [authority])]
#[account(seeds)]
#[account(seeds = [authority, usdc_mint])]

**Comment by AuroraLantean** [comment]
Okay I found it: #[derive(Default)] can replace the impl Default for UserData {...}
