### ISSUE TITLE
cli: Add ability to switch between anchor CLI versions

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#586]
This is important for allowing many versions of verifiable builds, because if there's a breaking change in the Anchor.toml, then the CLI won't work. If there's a way to switch between anchor CLI versions, then one can easily produce verifiable builds regardless of the Anchor.toml version being used.

**Comment by paul-schaaf** [comment]
there's also the option of having a separate installer / version manager do this. `anchor-vm` `avm` `anchor-install` ?

although im not experienced enough here to say whether that would be a better option

**Comment by tomlinton** [comment]
I played around with this and was using a separate cli called `avm`. It can't be part of the standard anchor cli because you could switch to an earlier version before it was implemented and not be able to switch back.

**Comment by tomlinton** [comment]
I got reasonably far with this so you can assign it to me if you haven't started work on it 👍

**Comment by armaniferrante** [comment]
> I got reasonably far with this so you can assign it to me if you haven't started work on it +1

Awesome thanks @tomlinton.
