### ISSUE TITLE
How to replace #[associated] with #[account(seeds = [...] Tutorial Basic 5: custom program error: 0xa1

### ISSUE THREAD

**Issue by AuroraLantean** [project-serum/anchor#601]
Hi I was following the tutorial of in the examples folder of this repo...
except I have replaced  `#[associated] `
with `#[account(seeds = [user_data.deposit_last.as_ref(), &[user_data.__nonce]])]`

then it failed to read the associated account's values
`  const userData = await program.account.userData.associated(wallet1, usdcMint);
`

So what is the correct way to update this soon-to-be-deprecated #[associated] ?
```
#[associated]
#[derive(Default)]
pub struct UserData {
  pub authority: Pubkey,
  pub deposit_last: i64,
  pub shares: u64,
  pub reward_debt: u64,
}
```

have updated the Rust program dependencies to Anchor 0.13.1 in the Cargo.toml file
also with updated project-serum/anchor to 0.13.1

Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1
    Program 7ohmkEjMrZHtdGW2kQJutrvhjpPUo1RGkcWwLcxaYzoe invoke [1]
    Program log: Custom program error: 0xa1
    Program 7ohmkEjMrZHtdGW2kQJutrvhjpPUo1RGkcWwLcxaYzoe consumed 3131 of 200000 compute units
    Program 7ohmkEjMrZHtdGW2kQJutrvhjpPUo1RGkcWwLcxaYzoe failed: custom program error: 0xa1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1
    at Connection.sendEncodedTransaction (.../node_modules/@solana/web3.js/lib/index.cjs.js:4882:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (.../node_modules/@solana/web3.js/lib/index.cjs.js:4841:20)
    at async Object.sendAndConfirmRawTransaction (.../node_modules/@solana/web3.js/lib/index.cjs.js:6668:21)
    at async Provider.send (.../node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as createToken] (.../node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
    at async Context.<anonymous> (.../dragon-coin/tests/dragon-coin.js:161:5) {
  logs: [
    'Program 7ohmkEjMrZHtdGW2kQJutrvhjpPUo1RGkcWwLcxaYzoe invoke [1]',
    'Program log: Custom program error: 0xa1',
    'Program 7ohmkEjMrZHtdGW2kQJutrvhjpPUo1RGkcWwLcxaYzoe consumed 3131 of 200000 compute units',
    'Program 7ohmkEjMrZHtdGW2kQJutrvhjpPUo1RGkcWwLcxaYzoe failed: custom program error: 0xa1'
  ]
}

     Error: Invalid account discriminator
      at AccountClient.fetch (/mnt/sda5/0Programming/Solana/anchorRepo0000/node_modules/@project-serum/anchor/dist/cjs/program/namespace/account.js:90:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async AccountClient.associated (/mnt/sda5/0Programming/Solana/anchorRepo0000/node_modules/@project-serum/anchor/dist/cjs/program/namespace/account.js:177:16)
      at async Context.<anonymous> (tests/dragon-coin.js:211:22)

0xa1 in hex is 161 in decimal
then the possible error codes:
    #[msg("The account discriminator was already set on this account")]
    AccountDiscriminatorAlreadySet = 160,
    #[msg("No 8 byte discriminator was found on the account")]
    AccountDiscriminatorNotFound,

Please help. Thank you

**Comment by AuroraLantean** [comment]
It seems I have to add __nonce for unknown reason...
```
#[account(seeds = [user_data.authority.as_ref(), &[user_data.__nonce]])]
#[derive(Default)]
pub struct UserData {
  pub authority: Pubkey,
  pub deposit_last: i64,
  pub shares: u64,
  pub reward_debt: u64,
  pub __nonce: u8,
}
```     
Then I got this: Error Invalid account discriminator
`const userData = await program.account.userData.associated(wallet1, usdcMint);
`

**Comment by AuroraLantean** [comment]
Also this UserData PDA account somehow already has "nonce": somehow already existing, does not matter whether you define it in the PDA struct or not!!!???
`pub nonce: u8`
SO, Never define a variable named "nonce" in an PDA!!!

**Comment by armaniferrante** [comment]
This `#[associated]` feature is being removed in the next release. Please don't use it.

**Comment by armaniferrante** [comment]
`#[associated]` is being removed. Your transformation is correct except your seeds must be changed to

```
#[account(seeds = [b"anchor", user_data.authority.as_ref()], bump = user_data.__nonce)]
```

**Comment by AuroraLantean** [comment]
Hi thanks for replying. my user's PDA is now:
```
#[account]
#[derive(Default)]
pub struct UserPda {
  pub num: u8,
  pub user_acct: Pubkey,
  pub authority: Pubkey,
  pub reward_debt_temp: u64,
  pub stake_amounts: [u64; 20],
  pub stake_times: [u32; 20],
  pub shares_array: [u64; 20],
  pub reward_debts: [u64; 20],
  pub __nonce: u8,
  //pub nonce: u8, somehow already existing!!!
}
```
but if I change #[account] to  #[account(seeds = [b"anchor", user_data.authority.as_ref()], bump = user_data.__nonce)]
I got errors:
error: custom attribute panicked
   --> programs/farm/src/lib.rs:528:1
    |
528 | #[account(seeds = [b"anchor", user_data.authority.as_ref()], bump = user_data.__nonce)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: Only two args are allowed to the account attribute.

error[E0433]: failed to resolve: use of undeclared type `UserPda`
   --> programs/farm/src/lib.rs:516:39
    |
516 |   pub user_pda: ProgramAccount<'info, UserPda>,
    |                                       ^^^^^^^ use of undeclared type `UserPda`

error[E0412]: cannot find type `UserPda` in this scope
   --> programs/farm/src/lib.rs:467:39
    |
436 | pub struct Stake<'info> {
    |                       - help: you might be missing a type parameter: `, UserPda`
...
467 |   pub user_pda: ProgramAccount<'info, UserPda>,
    |                                       ^^^^^^^ not found in this scope

error[E0412]: cannot find type `UserPda` in this scope
   --> programs/farm/src/lib.rs:516:39
    |
514 | pub struct InitUserPda<'info> {
    |                             - help: you might be missing a type parameter: `, UserPda`
515 |   #[account(init, associated = authority, with = user_acct)]
516 |   pub user_pda: ProgramAccount<'info, UserPda>,
    |                                       ^^^^^^^ not found in this scope

error[E0412]: cannot find type `UserPda` in this scope
   --> programs/farm/src/lib.rs:546:39
    |
544 | pub struct UpdateUserPda<'info> {
    |                               - help: you might be missing a type parameter: `, UserPda`
545 |   #[account(mut, associated = authority, with = user_acct)]
546 |   pub user_pda: ProgramAccount<'info, UserPda>,
    |                                       ^^^^^^^ not found in this scope

**Comment by AuroraLantean** [comment]
After reducing the array sizes:
```
#[account]
#[derive(Default)]
pub struct UserPda {
  pub num: u8,
  pub user_acct: Pubkey,
  pub authority: Pubkey,
  pub stake_amounts: [u64; 10],
  pub stake_times: [u32; 10],
  pub shares_array: [u64; 10],
  pub reward_debts: [u64; 10],
  pub __nonce: u8,
  //pub nonce: u8, somehow already existing!!!
}
```
The input struct is working now:
```
#[derive(Accounts)]
pub struct InitUserPda<'info> {
  #[account(zero, seeds = [b"anchor", authority.key().as_ref(), user_acct.key().as_ref()],
    bump,)]
  pub user_pda: Account<'info, UserPda>,

  #[account(signer)]//authority should sign this txn
  pub authority: AccountInfo<'info>,
  
  pub user_acct: Account<'info, UserAcct>,
  pub rent: Sysvar<'info, Rent>,//for init
}
```
