### ISSUE TITLE
lang: Implement `Key` trait without to_account_info() calls

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#608]
Currently the `Key` trait is implemented via a wasteful call to `to_account_info` which incurs a clone on the AccountInfo.

**Comment by fanatid** [comment]
I'm not sure how to do this properly, but with cargo-asm I see a clone with `to_account_info().key` (but was able to run only with `bpf` toolchain, not `bpfel` target).

Decide to count instructions with `sol_log_compute_units`:
```
*ctx.accounts.value.to_account_info().key == clock::ID; // 162
ctx.accounts.value.to_account_info().key == &clock::ID; // 162
*ctx.accounts.value.to_account_info().key == clock::id(); // 176
ctx.accounts.value.key() == clock::id(); // 190
*ctx.accounts.value.mykey() == clock::id(); // 95
*ctx.accounts.value.mykey() == clock::ID; // 82
ctx.accounts.value.mykey2() == clock::id(); // 105
```
with patched anchor:
```
impl<'info, T: solana_program::sysvar::Sysvar> Sysvar<'info, T> {
    pub fn mykey(&self) -> &Pubkey {
        self.info.key
    }
    pub fn mykey2(&self) -> Pubkey {
        *self.info.key
    }
}
```

I think to add `ToAccountInfoRef` trait and change `Key` trait to `KeyRef` with method `key` which return reference, sounds good?

**Comment by armaniferrante** [comment]
> I'm not sure how to do this properly, but with cargo-asm I see a clone with `to_account_info().key` (but was able to run only with `bpf` toolchain, not `bpfel` target).
> 
> Decide to count instructions with `sol_log_compute_units`:
> 
> ```
> *ctx.accounts.value.to_account_info().key == clock::ID; // 162
> ctx.accounts.value.to_account_info().key == &clock::ID; // 162
> *ctx.accounts.value.to_account_info().key == clock::id(); // 176
> ctx.accounts.value.key() == clock::id(); // 190
> *ctx.accounts.value.mykey() == clock::id(); // 95
> *ctx.accounts.value.mykey() == clock::ID; // 82
> ctx.accounts.value.mykey2() == clock::id(); // 105
> ```
> 
> with patched anchor:
> 
> ```
> impl<'info, T: solana_program::sysvar::Sysvar> Sysvar<'info, T> {
>     pub fn mykey(&self) -> &Pubkey {
>         self.info.key
>     }
>     pub fn mykey2(&self) -> Pubkey {
>         *self.info.key
>     }
> }
> ```
> 
> I think to add `ToAccountInfoRef` trait and change `Key` trait to `KeyRef` with method `key` which return reference, sounds good?

Sounds great.

**Comment by fanatid** [comment]
Looks like there is a nicer way to solve an issue... use `AsRef`. But we need it [solana_program::account_info::AccountInfo](https://docs.rs/solana-program/1.7.10/solana_program/account_info/struct.AccountInfo.html) :disappointed: 
If we will have `AsRef` we would able to write: `constraint = ctx.accounts.cpi_account.as_ref().owner == spl_token::ID`

**Comment by fanatid** [comment]
Submitted pull request :arrow_up: 
Current code in branch in my fork: https://github.com/fanatid/anchor/tree/cheaper-key

**Comment by fanatid** [comment]
1.7.11 is out, but not all required crates are published
