### ISSUE TITLE
cli: init command should create a package.json with `@project-serum/anchor`

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#615]
`anchor init` doesn't work out of the box unless one has all the dependencies installed. It should additionally

* add a package.json
* add mocha + @project-serum/anchor 
* run yarn

So that one can immediately run `anchor test` and have it work.

**Comment by WrRaThY** [comment]
also - potentially - it should check if the validator port is already taken (if `--skip-local-validator` was NOT used) and fail early and informatively if it's already in use

**Comment by mccjul** [comment]
#623 I implemented the anchor init. I could do the 2nd part however it could be a good first issue for someone else if they want it.

**Comment by mccjul** [comment]
Actually I did a test with my own project and in fact the way anchor calls the mocha test it actually requires to be installed globally. Would it be okay that I make the script in the anchor toml file run yarn run test or npm run test instead (because then it would actually use the node_modules)?

**Comment by armaniferrante** [comment]
> Actually I did a test with my own project and in fact the way anchor calls the mocha test it actually requires to be installed globally. Would it be okay that I make the script in the anchor toml file run yarn run test or npm run test instead (because then it would actually use the node_modules)?

I think it does use the local node_modules. For example, the CI in this repo works succesfully https://github.com/project-serum/permissioned-markets-quickstart without a global mocha install.

**Comment by WrRaThY** [comment]
@mccjul yeah. thats kind of another issue (for which the is no issue GH issue created AFAIK):
https://discord.com/channels/739225212658122886/752530209848295555/876982827227422730
https://discord.com/channels/739225212658122886/876992945893543963/876993529463840858

**Comment by mccjul** [comment]
Well isn't it because you run anchor test from the package json script? Wouldn't you rather users to use the cli and call anchor test in their terminal instead?

**Comment by armaniferrante** [comment]
Addressed in the latest version (apologies but I don't have the exact commit on hand).
