### ISSUE TITLE
Trying to run basic-0 or other examples

### ISSUE THREAD

**Issue by Joefdez** [project-serum/anchor#618]
I follow the steps and dependency installations, but upon calling anchor deploy or anchor test I get:

Error: RPC request error: cluster version query failed: error sending request for url (http://127.0.0.1:8899/): error trying to connect: tcp connect error: Connection refused (os error 111).

Sometimes accompanied by:

There was a problem deploying: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "" }.

Can anyone help with this?

Thank you.

**Comment by armaniferrante** [comment]
Make sure you don't have a local validator running. `anchor test` will start and shutdown one for you (unless you use the --skip-local-validator) flag.

**Comment by Joefdez** [comment]
Hi, thanks for getting back to me. 

I have checked that the local validator isn't running and I still get the same issue.

**Comment by code-with-joyce** [comment]
@armaniferrante 
HI I'm trying to "anchor deploy" with the basic-0 and it says "Error: RPC request error: cluster version query failed: error sending request for url (http://127.0.0.1:8899/): error trying to connect: tcp connect error: Connection refused (os error 61)

I've already checked that solana-test-validator has stopped. why am i keep getting this error.

**Comment by Aadhinana** [comment]
`anchor deploy` needs a local validator to be running. By doing `anchor deploy` you are trying to deploy the contract on a chain. 

Get it? If there is no chain, then there is no where for the contract to be deployed.

Your error basically means it was trying to reach the local validator running at `http://127.0.0.1:8899` but it found nothing there and connection was refused.

**Comment by aster2709** [comment]
gotcha! 
```sh
anchor test
```
- requires `solana-test-validator` ❌ // it spins up one internally.

```sh
anchor deploy
```
- requires `solana-test-validator` ✅

**Comment by matteosantama** [comment]
As a new user, I found this inconsistency confusing. A quick search of the GH issues clears things up, but consistent behavior between `anchor test` and `anchor deploy` would make onboarding smoother

**Comment by SoftwareArchitect9817** [comment]
Hello

I have an issue that:

Error: Your configured rpc port: 8899 is already in use

Thanks
