### ISSUE TITLE
Empty discriminator should error as not inited

### ISSUE THREAD

**Issue by Henry-E** [project-serum/anchor#625]
If a program account hasn't been initialized, and it is passed into a function that assumes it has been initialized, then the program will error saying the program account has the wrong discriminator. Is it possible to instead detect where the wrong discriminator is because the program account hasn't been inited (maybe it's all zeros or doesn't even have any space allocated to it) and give a more helpful error as result.

**Comment by paul-schaaf** [comment]
closed by https://github.com/project-serum/anchor/pull/1024
