### ISSUE TITLE
docs: Add documentation on errors

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#630]
We should describe how error codes are generated as is described here https://www.notion.so/Debugging-Custom-Anchor-Errors-b8540dd418c44a4e939ab17c56a3fd3b.

Framework errors are in the range 0-300. "Userspace" errors start at an offset of 300. So a program's first custom error code is 300. Second is 301. Etc.

**Comment by AlejoLovallo** [comment]
Hey, it would be pretty awesome if you will be able to do it. For newcomers to Solana, this would be extremely useful !.

**Comment by armaniferrante** [comment]
Docs here https://docs.rs/anchor-lang/latest/anchor_lang/__private/enum.ErrorCode.html.

We should bring that type out of the __private module though.
