### ISSUE TITLE
anchor test -- Error: Cannot find module '@project-serum/anchor'

### ISSUE THREAD

**Issue by mukeshmediratta1966** [project-serum/anchor#638]
mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$ anchor test
BPF SDK: /home/mukeshmediratta/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.18s
Running: /home/mukeshmediratta/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/mukeshmediratta/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so

To deploy this program:
  $ solana program deploy /home/mukeshmediratta/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so

Error: Cannot find module '@project-serum/anchor'
Require stack:
- /home/mukeshmediratta/anchor/examples/tutorial/basic-0/tests/basic-0.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/mukeshmediratta/anchor/examples/tutorial/basic-0/tests/basic-0.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async formattedImport (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/esm-utils.js:88:20)
    at async singleRun (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/cli/run.js:374:5)
mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$

While trying to test the minimal example given in the Anchor getting this error. please help

**Comment by armaniferrante** [comment]
> mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$ anchor test
> BPF SDK: /home/mukeshmediratta/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf
> Running: rustup toolchain list -v
> Running: cargo +bpf build --target bpfel-unknown-unknown --release
> Finished release [optimized] target(s) in 0.18s
> Running: /home/mukeshmediratta/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/mukeshmediratta/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so
> 
> To deploy this program:
> $ solana program deploy /home/mukeshmediratta/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so
> 
> Error: Cannot find module '@project-serum/anchor'
> Require stack:
> 
> * /home/mukeshmediratta/anchor/examples/tutorial/basic-0/tests/basic-0.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   at require (internal/modules/cjs/helpers.js:92:18)
>   at Object. (/home/mukeshmediratta/anchor/examples/tutorial/basic-0/tests/basic-0.js:1:16)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>   at Module.load (internal/modules/cjs/loader.js:937:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>   at ModuleWrap. (internal/modules/esm/translators.js:199:29)
>   at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
>   at async Loader.import (internal/modules/esm/loader.js:178:24)
>   at async formattedImport (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/esm-utils.js:7:14)
>   at async Object.exports.requireOrImport (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/esm-utils.js:48:32)
>   at async Object.exports.loadFilesAsync (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/esm-utils.js:88:20)
>   at async singleRun (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
>   at async Object.exports.handler (/home/mukeshmediratta/.nvm/versions/node/v14.17.5/lib/node_modules/mocha/lib/cli/run.js:374:5)
>   mukeshmediratta@DESKTOP-023N740:~/anchor/examples/tutorial/basic-0$
> 
> While trying to test the minimal example given in the Anchor getting this error. please help

Did you try to `npm install -g @project-serum/anchor` and check your NODE_PATH? Alternatively, you can install it locally in the example workspace.

**Comment by savvyguru** [comment]
Hi @armaniferrante, i tried `npm install -g @project-serum/anchor` and my node path is `/usr/local`. 
I have also installed @project-serum/anchor and it still doesnt work for me.

**Comment by santiagomarcano** [comment]
What worked for me (Mac M1):

Uninstall globally installed npm packages (anchor, anchor-cli and mocha)

`npm uninstall -g @project-serum/anchor`
`npm uninstall -g @project-serum/anchor-cli`
`npm uninstall -g mocha`

Build anchor from source with cargo:

`cargo install --git https://github.com/project-serum/anchor --tag v0.17.0 anchor-cli --locked`

More info [here](https://project-serum.github.io/anchor/getting-started/installation.html#build-from-source-for-other-operating-systems)

Reinstall  packages: 

`npm install -g @project-serum/anchor`
`npm install -g @project-serum/anchor-cli`
`npm install -g mocha`
