### ISSUE TITLE
[QUESTION] Can the transactions be seen in explorer?

### ISSUE THREAD

**Issue by Aadhinana** [project-serum/anchor#647]
`anchor test` spins up a localnet and does all the magic.

Is there a way to see the transaction in the `https://explorer.solana.com/` ? 

Just to see the details would be convenient for a noob like me exploring how and what accounts are getting involved.

Is this even possible?

**Comment by armaniferrante** [comment]
Yes. You can connect the explorer by setting a custom url.

**Comment by Aadhinana** [comment]
Thank you but `anchor test` just runs the program and shuts down the localnet right? 
So even I pre connect to the explorer before `anchor test`. Then it shuts down and I can't check my transactions. 

This is fully on the localnet BTW. 
Is this how its supposed to be? Else. Can this thing be built? Would love to help as well.

**Comment by armaniferrante** [comment]
> Thank you but `anchor test` just runs the program and shuts down the localnet right?
> So even I pre connect to the explorer before `anchor test`. Then it shuts down and I can't check my transactions.
> 
> This is fully on the localnet BTW.
> Is this how its supposed to be? Else. Can this thing be built? Would love to help as well.

Good point. Sounds like we should add a flag to leave the testnet running int he background so that one could use the explorer to see what happened after the tests are run. A PR would be great!

**Comment by Aadhinana** [comment]
Total Noob here. But I'm gonna start digging up code here and try my best. 💪
If anyone wants to help out, it would be great too!
