### ISSUE TITLE
tutorial basic-1,2,3 doesn't work 0,4 work!!!!!

### ISSUE THREAD

**Issue by code-with-joyce** [project-serum/anchor#649]
when I typed "anchor test" it shows

thread 'main' panicked at 'Code not parseable: Error("expected `=`")', lang/syn/src/idl/file.rs:337:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I guess there is something wrong with lib.rs 

solana-cli 1.7.10 (src:03b93051; feat:660526986)
rustc 1.54.0 (a178d0322 2021-07-26)
anchor-cli 0.13.2

**Comment by code-with-joyce** [comment]
it works fine with basic-0 

Here is full log 
`jung:test2/anchor(master❤️🥰❤️) »cd examples/tutorial/basic-0
jung:tutorial/basic-0(master❤️🥰❤️) » anchor test
BPF SDK: /Users/jung/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
   Compiling proc-macro2 v1.0.28
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.75
   Compiling serde v1.0.130
   Compiling serde_derive v1.0.130
   Compiling version_check v0.9.3
   Compiling typenum v1.13.0
   Compiling ryu v1.0.5
   Compiling semver-parser v0.7.0
   Compiling bs58 v0.3.1
   Compiling anyhow v1.0.43
   Compiling serde_json v1.0.67
   Compiling block-padding v0.2.1
   Compiling cfg-if v1.0.0
   Compiling itoa v0.4.8
   Compiling yansi v0.5.0
   Compiling opaque-debug v0.3.0
   Compiling cpufeatures v0.2.1
   Compiling unicode-segmentation v1.8.0
   Compiling memchr v2.4.1
   Compiling feature-probe v0.1.1
   Compiling log v0.4.14
   Compiling rustversion v1.0.5
   Compiling autocfg v1.0.1
   Compiling ahash v0.4.7
   Compiling keccak v0.1.0
   Compiling either v1.6.1
   Compiling regex-syntax v0.6.25
   Compiling lazy_static v1.4.0
   Compiling hex v0.4.3
   Compiling base64 v0.13.0
   Compiling bytemuck v1.7.2
   Compiling semver v0.9.0
   Compiling generic-array v0.14.4
   Compiling proc-macro2-diagnostics v0.9.1
   Compiling bv v0.11.1
   Compiling itertools v0.9.0
   Compiling hashbrown v0.9.1
   Compiling heck v0.3.3
   Compiling num-traits v0.2.14
   Compiling rustc_version v0.2.3
   Compiling solana-frozen-abi-macro v1.7.8
   Compiling solana-frozen-abi v1.7.8
   Compiling solana-program v1.7.8
   Compiling quote v1.0.9
   Compiling aho-corasick v0.7.18
   Compiling regex v1.5.4
   Compiling borsh-derive-internal v0.9.1
   Compiling borsh-schema-derive-internal v0.9.1
   Compiling thiserror-impl v1.0.28
   Compiling solana-sdk-macro v1.7.8
   Compiling num-derive v0.3.3
   Compiling thiserror v1.0.28
   Compiling serde_bytes v0.11.5
   Compiling bincode v1.3.3
   Compiling toml v0.5.8
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling sha2 v0.9.6
   Compiling sha3 v0.9.1
   Compiling proc-macro-crate v0.1.5
   Compiling anchor-syn v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/syn)
   Compiling borsh-derive v0.9.1
   Compiling borsh v0.9.1
   Compiling anchor-attribute-error v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/error)
   Compiling anchor-attribute-event v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/event)
   Compiling anchor-attribute-interface v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/interface)
   Compiling anchor-attribute-state v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/state)
   Compiling anchor-attribute-access-control v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/access-control)
   Compiling anchor-attribute-program v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/program)
   Compiling anchor-derive-accounts v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/derive/accounts)
   Compiling anchor-attribute-account v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang/attribute/account)
   Compiling anchor-lang v0.13.2 (/Users/jung/Desktop/anchor_test/test2/anchor/lang)
   Compiling basic-0 v0.1.0 (/Users/jung/Desktop/anchor_test/test2/anchor/examples/tutorial/basic-0/programs/basic-0)
    Finished release [optimized] target(s) in 41.47s
Running: /Users/jung/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/scripts/strip.sh /Users/jung/Desktop/anchor_test/test2/anchor/examples/tutorial/basic-0/target/bpfel-unknown-unknown/release/basic_0.so /Users/jung/Desktop/anchor_test/test2/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so
Running: /Users/jung/.local/share/solana/install/releases/1.7.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /Users/jung/Desktop/anchor_test/test2/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so

To deploy this program:
  $ solana program deploy /Users/jung/Desktop/anchor_test/test2/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so


  basic-0
    ✔ Uses the workspace to invoke the initialize instruction (111ms)


  1 passing (119ms)

jung:tutorial/basic-0(master❤️🥰❤️) » cd ../basic-
jung:tutorial/basic-1(master❤️🥰❤️) » anchor test
thread 'main' panicked at 'Code not parseable: Error("expected `=`")', lang/syn/src/idl/file.rs:337:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
jung:tutorial/basic-1(master❤️🥰❤️) »        101 ↵`

**Comment by code-with-joyce** [comment]
So, Here's a thing when I changed 

Cargo.toml 
from 
[dependencies]
anchor-lang = { path = "../../../../../lang" }

to 
[dependencies]
anchor-lang = "0.13.2"

And 
#[account(zero)] to #[account(init)] in lib.rs



 It seems to be working......... I spent 3 hours on this What's wrong with this line? I'd like to know!

**Comment by armaniferrante** [comment]
Master has breaking changes. To run the examples, you need to build and use the CLI from master.

**Comment by armaniferrante** [comment]
Should work with v0.14.0. Please re-open if there are still problems.

**Comment by yokiyokx** [comment]
Still having the following issue when running "anchor test"... What does this mean / how do i fix?

thread 'main' panicked at 'Code not parseable: Error("payer must be provided when initializing an account")', lang/syn/src/idl/file.rs:337:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by armaniferrante** [comment]
> Still having the following issue when running "anchor test"... What does this mean / how do i fix?
> 
> thread 'main' panicked at 'Code not parseable: Error("payer must be provided when initializing an account")', lang/syn/src/idl/file.rs:337:58
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Sounds like you're using an old CLI or old program. Make sure everything is on v0.14.0.

**Comment by shivekkhurana** [comment]
I faced the same issue with `v0.15.0`. But its fixed in `v0.16.0`.
