### ISSUE TITLE
object not found

### ISSUE THREAD

**Issue by UrsaEli** [project-serum/anchor#650]
Hi

I encounter this error:

$ sudo cargo install --git https://github.com/project-serum/anchor --tag v0.13.2 anchor-cli --locked
    Updating git repository `https://github.com/project-serum/anchor`
    Updating git submodule `https://github.com/project-serum/stake.git`
**error: failed to update submodule `examples/cfo/deps/stake`**

Caused by:
  object not found - no match for id (3dc83f47b66a8a4189a637368c49dca1341c6b23); class=Odb (9); code=NotFound (-3)

Can you advise?
Thanks.

**Comment by yalis** [comment]
Until it get fixed, I could install it locally from a cloned repo.

```git clone https://github.com/project-serum/anchor
cd anchor
git checkout tags/v0.13.2
cd cli
cargo install --path . --locked
```

**Comment by paul-schaaf** [comment]
this is a very old anchor version so Im closing this for now. lmk if this happens on a newer anchor version too
