### ISSUE TITLE
Failed to install anchor

### ISSUE THREAD

**Issue by tcchen123** [project-serum/anchor#665]
I was trying to install anchor. It hit a error: failed to update submodule `examples/cfo/deps/stake`. 
I have updated Ubuntu on my laptop by following your command 'sudo apt-get update && ....' but anchor still failed to install.
Kindly advise.

Thanks,
ChenTC

![20210902 AnchorError](https://user-images.githubusercontent.com/19972041/131807865-54b4fcb2-2b63-4ede-9bb1-b0ddc2be8188.jpg)

**Comment by RemiBaldy** [comment]
Same error for me on windows

**Comment by pchz** [comment]
Same error as above : 
![image](https://user-images.githubusercontent.com/58364960/131864980-7d4455b8-daf4-4336-90cd-563ff70a6a7d.png)

**Comment by armaniferrante** [comment]
A submodule branch/commit used in `examples/cfo/` was deleted, which is what is causing this. Will be fixed in v0.14.0.

**Comment by RemiBaldy** [comment]
How can we do install it in the meantime ?

**Comment by RemiBaldy** [comment]
How can we install it in the meantime ?

**Comment by armaniferrante** [comment]
> How can we install it in the meantime ?

Remove the v0.13.2 tag to install from master.

**Comment by tcchen123** [comment]
After removing the v0.13.2 tag to install anchor, I hit two errors.
1. error: failed to run custom build command for 'openssl-sys v0.9.66' 
Caused by : Process didn't exit successfully: '/tmp/cargo/-installrSK7Qi/release/build/opein' (exit status:101)

2. error: failed to compile 'anchor-cli v0.14.0 (https://github.com/project-serum/anchor#2cc82bc1)', intermediate artifacts can be found at '/tmp/cargo-installR5wtIO'
Kindly advise.

![20210903 InstallAnchorErr1](https://user-images.githubusercontent.com/19972041/131947730-36c61de4-dcea-4b2c-83f1-fb1981fdef4b.JPG)
![20210903 InstallAnchorErr2](https://user-images.githubusercontent.com/19972041/131947777-f6ea2873-bed8-40a3-be66-d65790381b16.JPG)

**Comment by tcchen123** [comment]
After I install Javascript package again, I still hit error 1. However, error 2 has changed to error 3. See attached.
![20210903 InstallAnchorErr3](https://user-images.githubusercontent.com/19972041/131948813-953946f8-1604-4af2-95da-9761a47a2c23.JPG)

**Comment by armaniferrante** [comment]
Anchor v0.14.0 has been published. Please try cargo installing with the new tag. `cargo install --git https://github.com/project-serum/anchor --tag v0.14.0 anchor-cli --locked`

**Comment by tcchen123** [comment]
Install Anchor v0.14.0, still hit error 1 and this error shown below.
error: failed to compile `anchor-cli v0.14.0 (https://github.com/project-serum/anchor?tag=v0.14.0#5017a1af)`, intermediate artifacts can be found at `/tmp/cargo-installquvrvy`

**Comment by tcchen123** [comment]
To solve Openssl error 1 on Ubuntu 20.04, I run  
$sudo apt-get install pkg-config libssl-dev

After that, install Anchor v0.14.0 again as per your cmd, it worked. 

![image](https://user-images.githubusercontent.com/19972041/131959285-7a87bb4a-f164-49d4-9dd8-0d71d71c8d80.png)

**Comment by fanatid** [comment]
@tcchen123 for Linux anchor also available as an npm package: https://www.npmjs.com/package/@project-serum/anchor-cli
