### ISSUE TITLE
CPI TokenAccount Init errors

### ISSUE THREAD

**Issue by tomjohn1028** [project-serum/anchor#667]
I'm trying to initialize a new TokenAccount in an instruction's Accounts struct. If I comment out the `token::mint` and `token::authority` the following error shows up.

![Screen Shot 2021-09-01 at 7 26 15 PM](https://user-images.githubusercontent.com/32071703/131887468-abceb7e5-40f8-4d99-88a6-37766c674cf2.png)

If I uncomment the token information then there are all these obscure compiler errors. 
![photo_2021-09-02 10 09 35](https://user-images.githubusercontent.com/32071703/131887607-0ac8c400-3d78-4780-9cd3-9314346fb4c2.jpeg)

Cargo dependencies:
````
anchor-lang = "0.13.0"
anchor-spl = "0.13.0"
solana-program = "=1.7.8"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
````

**Comment by Arrowana** [comment]
Can you share the entire `Accounts` struct?
I believe the mint need to be an account provided as a `CpiContext<'info, Mint>`
The mint could be checked with `has_one = option_mint` on option_market

**Comment by tomjohn1028** [comment]
It turns out the macro I was using wasn't in anchor 13 and was released in anchor 14. I'm going to close this issue
