### ISSUE TITLE
error: no such subcommand: `build-bpf`

### ISSUE THREAD

**Issue by UrsaEli** [project-serum/anchor#690]
$ anchor build
error: no such subcommand: `build-bpf`
$ cargo build-bpf
error: no such subcommand: `build-bpf`
$ cargo test-bpf
error: no such subcommand: `test-bpf`

**Comment by armaniferrante** [comment]
> $ anchor build
> error: no such subcommand: `build-bpf`
> $ cargo build-bpf
> error: no such subcommand: `build-bpf`
> $ cargo test-bpf
> error: no such subcommand: `test-bpf`

Have you installed the solana cli?

**Comment by armaniferrante** [comment]
Closing as this appears to be a solana cli installation issue.

**Comment by hetdagli234** [comment]
I faced the same issue, currently in the getting started guide over here:
https://project-serum.github.io/anchor/getting-started/installation.html#install-rust
The Solana CLI command installation goes like this:
`sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)"
`
This installs the older version of Solana CLI v1.8.0, on running `anchor deploy` on this version of CLI, the error same as above is thrown:
`error: no such subcommand: build-bpf
`
The error goes away on using the latest Solana CLI version:
`sh -c "$(curl -sSfL https://release.solana.com/v1.9.2/install)"
`
@armaniferrante Can you correct this on the installation guide page?

**Comment by fanatid** [comment]
@hetdagli234 pull requests are welcomed.

**Comment by hetdagli234** [comment]
Thanks, @fanatid, I think the code on master already has v1.9.1, but the latest release candidate 22 days ago has 1.8.0, the issue should be resolved with the next release.

**Comment by renektonwu** [comment]
@hetdagli234 Hi, have you solved the problem?
