### ISSUE TITLE
Allow #[account(init)] on PDA

### ISSUE THREAD

**Issue by dovahcrow** [project-serum/anchor#696]
Currently the `#[account(init)] ProgramAccount<'info, SomeState>` combo requires you to sign this to-be-initialized account because `system_program::allocate` requires it to be signed. 

This works fine if the address of this is generated using a `keypair`. However, when it comes to the case that the `ProgramAccount` is a PDA, i.e. the address is generated using `Pubkey::find_program_address`, `#[account(init)]` breaks because `anchor` internally checks `AccountInfo::is_signer` which will always return false for a PDA. 

But in reality, calling `system_program::allocate` is fine because that account is a PDA and you just need to pass the seed for the PDA address to `invoke_signed`.

**Comment by dovahcrow** [comment]
NVM I found if you specify seed and bump with init, PDA allocation works as intended.

**Comment by keshrisohit** [comment]
@dovahcrow can you please help me with this , I am also facing the same issue

**Comment by dovahcrow** [comment]
@keshrisohit  Add this to your account `#[account(init, seeds = ["seed"], payer = payer)]`.
