### ISSUE TITLE
docs: Add tutorial with program derived address.

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#70]
Signing with a program is pretty confusing for people using solana for the first time. Not really specific to Anchor but a useful example nonetheless.

**Comment by armaniferrante** [comment]
This should be extended into an entire tutorial providing intuition + design patterns for using program controlled accounts + seeds + associated accounts.

**Comment by noah40povis** [comment]
I found this guide that briefly goes of PDAs: https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction/
Still would like something more clear.

**Comment by paul-schaaf** [comment]
theres a chapter in the anchor book about it now so Im closing this issue
