### ISSUE TITLE
Provider always uses ~/.config/solana/id.json for localnet instead of specified in Anchor.toml

### ISSUE THREAD

**Issue by dvcrn** [project-serum/anchor#701]
Code in question: https://github.com/project-serum/anchor/blob/master/ts/src/provider.ts#L229-L246

As a newcomer to this project, I expected that anchor would load what I specify in `Anchor.toml` under provider.wallet as the default wallet, but from the looks of it it ignores that setting and always tries to load `~/.config/solana/id.json` instead.

**Comment by wjl8** [comment]
Anchor.toml

[provider]
cluster = "localnet"
wallet = "~/.config/solana/my_solana_wallet.json"

[scripts]
test = "mocha -t 1000000 tests/"

**Comment by armaniferrante** [comment]
Addressed by #718.
