### ISSUE TITLE
Usage of #[account(signer)] 

### ISSUE THREAD

**Issue by ppoliani** [project-serum/anchor#704]
I've just read the macros documentation here https://docs.rs/anchor-lang/0.15.0/anchor_lang/derive.Accounts.html.

About the `#[account(signer)]` the following is written:

> Checks the given account signed the transaction.

I'm slightly confused because in the basic-2 example the signer is set to the user field 

https://github.com/project-serum/anchor/blob/master/examples/tutorial/basic-2/programs/basic-2/src/lib.rs#L28

However in the tests the signer that is used is the `counter` account and not the `user`

https://github.com/project-serum/anchor/blob/master/examples/tutorial/basic-2/tests/basic-2.js#L24

Am I missing something here?

**Comment by armaniferrante** [comment]
The javascript `Provider` object signs and pays for all transactions. So it does not need to be added to the `signers` array, as the `user` pubkey is the provider.
