### ISSUE TITLE
Anchor Test Failed after generating project with dashed name

### ISSUE THREAD

**Issue by rharriso** [project-serum/anchor#706]
I had a minor error when working through the minimal example.

1. Create project with dash name: `anchor init fancy-project`
2. Run `anchor test`
3. See error: `TypeError: Cannot read property 'state' of undefined`

Cause:

Looking at the compiled version `workspace.js#attachWorkspace`. I added logs for clarification.

```javascript
function attachWorkspaceOverride(workspaceCache, overrideConfig, idlMap) {
    Object.keys(overrideConfig).forEach((programName) => {
        const wsProgramName = camelcase_1.default(programName, { pascalCase: true });
        const entry = overrideConfig[programName];
        const overrideAddress = new web3_js_1.PublicKey(typeof entry === "string" ? entry : entry.address);

        let idl = idlMap.get(programName);
        console.log('programName', idlMap.keys());
        if (typeof entry !== "string" && entry.idl) {
            idl = JSON.parse(require("fs").readFileSync(entry.idl, "utf-8"));
        }
        workspaceCache[wsProgramName] = new program_1.Program(idl, overrideAddress);
    });
}
```

The output was as follows:

```
fancy-project
programName [Map Iterator] { 'fancy_project' }
```

You can see that the requested program name does not match the entry in the IDL map. 
One uses hyphens, the other uses underscores.

**Comment by grumpyoldman-io** [comment]
Same goes for capitalized names like "MyAppName" it will be built as "my_app_name" in the IDL folder.

**Comment by armaniferrante** [comment]
A quick workaround here is to change the name in the Anchor.toml to be snake case.

**Comment by rharriso** [comment]
Thanks Armani, I suppose the best course of action would be to normalize
the names when the project is generated?

**Comment by armaniferrante** [comment]
That would be a good fix for now.

**Comment by armaniferrante** [comment]
Addressed by https://github.com/project-serum/anchor/pull/711.

**Comment by paul-schaaf** [comment]
projects with dashes in their name seem to work fine now, so im closing this
