### ISSUE TITLE
Better dependencies within the anchor repo for development

### ISSUE THREAD

**Issue by Arrowana** [project-serum/anchor#717]
Doing #716 , i had to iterate the ts lib and test through `anchor test`
Currently everything points to the global possibly present `@project-serum/anchor`

For dev purposes i added a package.json so i could build the ts package then use it.
```{
  "name": "events",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@project-serum/anchor": "file:../../ts"
  }
}
```

Should all tests have better dependency management? This will also avoid painful management when someone switches to a PR touching both sides.

**Comment by armaniferrante** [comment]
Using package.json files in every example/test is a good idea.

**Comment by cqfd** [comment]
@armaniferrante I can take this one (per discord convo).

**Comment by armaniferrante** [comment]
> @armaniferrante I can take this one (per discord convo).

Please do!
