### ISSUE TITLE
Just trying out basic_0 - not able to debug - also, what's the discord channel?

### ISSUE THREAD

**Issue by relaxedtomato** [project-serum/anchor#721]
Just trying to call `solana program deploy basic_0.so` with ` solana-test-validator` running in the background and receive the below error:

`Error: Account [ADDRESS] has insufficient funds for spend (1.06051608 SOL) + fee (0.003345 SOL)`

Not sure what to do next - can we update the discord link (says inactive/invalid)? I can update documentation on both tutorial / repo to clarify the error and discord link.

**Comment by armaniferrante** [comment]
Here's the discord link https://discord.gg/QvkkPxkDUH.

**Comment by ptudan** [comment]
You need to airdrop your account some sol to actually test with.  Unlike truffle/ganache, you don't start with a default amount of currency.  IMO that is the better change than adding an airdrop step in the tutorial.

For now, just run

`solana airdrop 100`

and it will give you 100 SOL in your default wallet.

**Comment by Arrowana** [comment]
> You need to airdrop your account some sol to actually test with. Unlike truffle/ganache, you don't start with a default amount of currency. IMO that is the better change than adding an airdrop step in the tutorial.

If you use the same wallet with `solana-test-validator` and `solana program deploy X`, you should have 500000000 SOL.
Are you sure `solana program deploy basic_0.so` is happening on localnet?

**Comment by relaxedtomato** [comment]
> Are you sure solana program deploy basic_0.so is happening on localnet?

Not sure about this part - can I pass in an argument, or how can I tell that its running on localnet?

**Comment by relaxedtomato** [comment]
> You need to airdrop your account some sol to actually test with. Unlike truffle/ganache, you don't start with a default amount of currency. IMO that is the better change than adding an airdrop step in the tutorial.
> 
> For now, just run
> 
> `solana airdrop 100`
> 
> and it will give you 100 SOL in your default wallet.

I keep getting `Error: airdrop request failed. This can happen when the rate limit is reached.`

**Comment by relaxedtomato** [comment]
Okay, think I figured out a few issues with how things were configured - let me see if I can add some notes to the examples walkthrough.
