### ISSUE TITLE
[Feature Request / Intend to PR] Supporting afterInstructions, where the instructions are run after the RPC call

### ISSUE THREAD

**Issue by vivaviche** [project-serum/anchor#722]
Instructions under the ctx is pre-instructions today. That is the instructions are run *BEFORE* the RPC calls. Here: https://github.com/project-serum/anchor/blob/2f780e0d274f47e442b3f0d107db805a41c6def0/ts/src/program/namespace/transaction.ts#L15

However, it is useful to allow users to include post-instructions. Example would be in a transaction involving wSOL, you need pre-instructions to setup a temporary wSOL account, and then use post-instructions to clean up / close the temporary wSOL account.

I intend to submit a PR to
1. add a `postInstructions` field. Should be here: (https://github.com/project-serum/anchor/blob/8fa867fbd695722b4cc592efd6f7ce462fc18f9b/ts/src/program/context.ts#L34)
2. Add the `postInstructions` to the tx. (e.g. `tx.add(...ctx.postInstructions)`) Adding it here https://github.com/project-serum/anchor/blob/2f780e0d274f47e442b3f0d107db805a41c6def0/ts/src/program/namespace/transaction.ts#L17

Opening an issue first to see if this something that you would accept.

**Comment by Arrowana** [comment]
I would say yes, i often need this and this requires breaking out of the `<program>.rpc.<method>(...)` comfort

**Comment by paul-schaaf** [comment]
we have `postInstructions` now, so it seems like I can close this. lmk if this was talking about sth else
