### ISSUE TITLE
thread 'main' panicked at 'Could not resolve Accounts symbol'

### ISSUE THREAD

**Issue by naveed-ang** [project-serum/anchor#725]
CMD: `anchor test`
Error log:
thread 'main' panicked at 'Could not resolve Accounts symbol', lang/syn/src/idl/file.rs:451:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Getting same error while `anchor build`
*****/solana/anchor/examples/tutorial/basic-1$ anchor build
BPF SDK: /home/malik/.local/share/solana/install/releases/1.7.11/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.32s
Running: /home/malik/.local/share/solana/install/releases/1.7.11/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/malik/Angelium/blockchain/solana/anchor/examples/tutorial/basic-1/target/deploy/basic_1.so

To deploy this program:
  $ solana program deploy /home/malik/Angelium/blockchain/solana/anchor/examples/tutorial/basic-1/target/deploy/basic_1.so
The program address will default to this keypair (override with --program-id):
  /home/malik/Angelium/blockchain/solana/anchor/examples/tutorial/basic-1/target/deploy/basic_1-keypair.json
thread 'main' panicked at 'Could not resolve Accounts symbol', lang/syn/src/idl/file.rs:451:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by naveed-ang** [comment]
while running `anchor build` with suggested env variable: _RUST_BACKTRACE=1_
===>
thread 'main' panicked at 'Could not resolve Accounts symbol', lang/syn/src/idl/file.rs:451:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:1243:5
   3: anchor_syn::idl::file::idl_accounts
   4: anchor_syn::idl::file::parse
   5: anchor_cli::build_cwd
   6: anchor_cli::build_all
   7: anchor_cli::build
   8: anchor_cli::entry
   9: anchor::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by tomlinton** [comment]
Your CLI version has probably fallen behind whatever you have checked out, try:

`cargo install --git https://github.com/project-serum/anchor --tag v0.15.0 anchor-cli --locked`

**Comment by naveed-ang** [comment]
Thanks @tomlinton it got resolved :) but I'm getting another error after this.
while i run `anchor test` now
with node v10.15.3, npm v6.4.1
It's giving error: 
ReferenceError: TextEncoder is not defined

and once i switch to node v11.15.0, npm v6.7.0
it's giving error:
Failed to run test: mocha -t 1000000 tests/: No such file or directory (os error 2)

But I can see tests/ directory at `solana/anchor/examples/tutorial/basic-1/`

**Comment by tomlinton** [comment]
If you are switching node versions with something like nvm make sure you reinstall the required global dependencies (see https://project-serum.github.io/anchor/getting-started/installation.html) and make sure your NODE_PATH is set correctly in your env.

**Comment by ptudan** [comment]
Getting the same issue, more details in this issue https://github.com/project-serum/anchor/issues/731 .  My anchor cli is 0.15 and solana is 1.7.11, so up to date.  Anything else that I could need to update?

**Comment by tomlinton** [comment]
@ptudan you are probably running an up to date master? Either checkout the repo at tag 0.15.0 or build from source with `cargo build` if you want to use master.

**Comment by ptudan** [comment]
@tomlinton Thanks so much, you're totally correct.  To help noobs like me in the future, I suggest we explicitly call out the tagged version in [this page of the tutorial](https://project-serum.github.io/anchor/tutorials/tutorial-0.html#clone-the-repo).  [Created a PR here](https://github.com/project-serum/anchor/pull/732)

**Comment by naveed-ang** [comment]
> If you are switching node versions with something like nvm make sure you reinstall the required global dependencies (see https://project-serum.github.io/anchor/getting-started/installation.html) and make sure your NODE_PATH is set correctly in your env.

Thanks @tomlinton it worked for me, Just updated mocha and booom :)
`npm i -g mocha`
