### ISSUE TITLE
Provide the ability to redeploy programs for each test file

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#73]
Currently the deploy happens once for the entire test suite.

**Comment by armaniferrante** [comment]
A cheap way to implement this would be to effectively run `anchor test <file>` for all test files in the `tests/` directory--enabled by a flag, e.g., `anchor test --redeploy`.

**Comment by paul-schaaf** [comment]
this has been solved by https://github.com/project-serum/anchor/pull/1681 although we might want more configurability eventually (currently each test suite can use their own `Test.toml` but they all share the the same cli args)
