### ISSUE TITLE
ProgramError should also expose the full program as a third parameter beyond msg and code

### ISSUE THREAD

**Issue by tomland123** [project-serum/anchor#740]
Most anchor programs follow the same error numbering system so if you use multiple anchor programs in your client its difficult to separate concerns and call custom error handlers based off program type. A good way to differentiate them would be to expose the name / metadata of the program as well as code and msg. I think for simplicity you can just expose the whole program tho

**Comment by armaniferrante** [comment]
Note that mapping errors is not possible in solana programs, so if error codes conflict between multiple programs, one can't know the program that returned the error. To do this, we one would need to parse the logs and infer which program returned the error code.

**Comment by tomland123** [comment]
are you planning on having the new syntax take multiple idls in a program as an array? I was thinking the opposite would make everyone happy and remove collisions. You would pass in multiple anchor programs each with one to one mapping of an idl and its own naming convention and write some form of abstraction so its just an array.

**Comment by armaniferrante** [comment]
`The problem there is that it doesn't work when a program invokes an opaque interface, since you may have a well defined instruction being called, but error codes are not public. 

One solution that might work is for Anchor to log the full error message. Then clients can extract the error string and display it, instead of relying on the error code being in the IDL and mapping it.

**Comment by tomland123** [comment]
I am not sure why anchor should have to interoperate with opaque interfaces by default.... Those interfaces should be responsible for creating their own standard language and then anchor should integrate with that in my mind.

**Comment by paul-schaaf** [comment]
the new `AnchorError` provides the program the error originated from as well as other info, so Im closing this issue. lmk if theres a need to reopen
