### ISSUE TITLE
CPI to published program

### ISSUE THREAD

**Issue by petscheit** [project-serum/anchor#743]
Is it possible to make a CPI to a program that was published to the anchor registry? I understand how the client can fetch a program IDL from the registry to make deserialize data and make transactions, and am wondering if the same works for anchor programs. I saw the the `[registry]' now has a section in the config file, but I don't understand what exactly that can be used for. 

Keep up the great work, it's extremely impressive how quickly this library is developing!

**Comment by armaniferrante** [comment]
The registry is used to display and allow one to download source code for verified and reproducible smart contract builds. There's some docs here https://project-serum.github.io/anchor/getting-started/publishing.html. 

What you're describing is done by crates.io.

For further discussion on this topic, please join the Discord!
