### ISSUE TITLE
Anchor 14 -> 16: functions exceed stack offset

### ISSUE THREAD

**Issue by tomjohn1028** [project-serum/anchor#752]
When upgrading from anchor 14 to 16 the program is showing compiler errors with: `Error: Function FUNCTION_SYMBOL Stack offset of -4944 exceeded max offset of -4096 by 848 bytes, please minimize large stack variables`

and then instructions fail with access violations `Program failed to complete: Access violation in stack frame 3 at address 0x200003f50 of size 8 by instruction #38646`

Where in Anchor does this additional overhead come from? Is there anyway around it?

**Comment by armaniferrante** [comment]
> and then instructions fail with access violations `Program failed to complete: Access violation in stack frame 3 at address 0x200003f50 of size 8 by instruction #38646`

`ProgramAccount` and `CpiAccount` internally use `Box` to heap allocate. `Account` does not and requires you to explicitly use `Box<Account<'info, MyAccount>>`.
