### ISSUE TITLE
Account struct PDA doesn't work

### ISSUE THREAD

**Issue by djole-nikolic-apfm** [project-serum/anchor#774]
When replacing ProgramAccount with Account struct,  it throws 0xa7 (167).

My ProgramAccount is PDA with bump and seed etc..ProgramAccount struct works fine however...

**Comment by armaniferrante** [comment]
Is the `declare_id!` address set correctly?

**Comment by djole-nikolic-apfm** [comment]
Did that and now it works.

Could you just elaborate the different between the two and also what is Signer struct? 

I thought Signer is the same things as passing #[account(signer)], but when replace it it also doesn't work. I also noticed Signer accounts are not being passed in signers array on frontend...very confusing :((((
