### ISSUE TITLE
missing lifetime specifiers

### ISSUE THREAD

**Issue by naveed949** [project-serum/anchor#784]
when I try to build using `anchor build` it gives following error:
**Error log:**
error[E0106]: missing lifetime specifiers
  --> programs/blindbox/src/lib.rs:24:2
   |
24 | #[program]
   |  ^ expected 4 lifetime parameters
   |
   = note: this error originates in the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
   |
24 | #'a, 'a, 'a, 'a, [program]
25 | mod blind_box {
26 |  use super::*;
27 | 
28 |  pub fn create_box(ctx: Context<Create>, auth: Context<Role>, bx: NftBox) -> ProgramResult {
29 |   let my_boxes = &mut ctx.accounts.my_boxes;

Can you please tell me what I'm missing, as I don't see lifetime parameters are being provided in examples along #[program]

**Comment by naveed-ang** [comment]
Got it fixed :) , I was providing two anchor_lang::context parameters in function `create_box` i.e: ctx & auth. Just removed one and it worked!

No lifetime specifiers need to provide with #[program].
