### ISSUE TITLE
Discrepancy in the  Rust documentation for the account macro

### ISSUE THREAD

**Issue by Ahmed-Ali** [project-serum/anchor#789]
In the [#[account]](https://docs.rs/anchor-lang/0.16.1/anchor_lang/derive.Accounts.html) documentation there is a reference to `ProgramAccount`, which I believe has changed to be `Program`.

And I believe it might also be good to add a row for the `#[account]` which doesn't have any arguments. I saw some of it in the tutorials which is placed sometime on `Account` structs, and sometime on plain Rust structs.

p.s I would be more than happy to start creating PRs instead of issues. But for the time being, I am still just trying to find my way in, hence not much context to be able to tell what would be the right changes to be done.

**Comment by Ahmed-Ali** [comment]
Nevermind, I found the documentation I was looking for: https://docs.rs/anchor-lang/0.16.1/anchor_lang/attr.account.html

Hence, I am not sure if this is actionable anymore. Feel free to close if it is not actionable.

**Comment by paul-schaaf** [comment]
@Ahmed-Ali thanks for reporting this! `ProgramAccount` has changed to `Account` but the docs are still outdated. just created PR.

btw, `#[account]` has different meanings depending on whether it is inside a `deriveAccounts` struct or on a plain rust struct. I find it a bit confusing so theres now an issue for discussion on this too #1168
