### ISSUE TITLE
ts: Anchor clients for non anchor programs

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#799]
The coder/serialization interface should be pluggable so that one can simply create and generate an anchor client for non anchor programs--given an IDL for the non anchor program. The spl token program would be a great first test.

**Comment by Necmttn** [comment]
This is somehow related: https://github.com/project-serum/anchor/issues/1176 with the little direction I can try to do it.

**Comment by armaniferrante** [comment]
Going to do the first part of this. That is, transitioning `Coder` into a common interface.
