### ISSUE TITLE
`anchor test` failed with `TypeError: Cannot read property 'state' of undefined` when project name contains "hyphen"

### ISSUE THREAD

**Issue by wan-nyan-wan** [project-serum/anchor#805]
## Reproduction

Ran commands below and failed.
```
anchor init test-anchor
cd test-anchor
anchor test
...
TypeError: Cannot read property 'state' of undefined
```

But commands below finished normally.
```
anchor init testanchor
cd testanchor
anchor test
# test finished successly
```

## Environment
```
anchor-cli 0.16.1
Ubuntu 20.04
```

**Comment by armaniferrante** [comment]
What version of Anchor are you on?

**Comment by wan-nyan-wan** [comment]
Thanks for the comment. I added an anchor version to Enviroment.

**Comment by wan-nyan-wan** [comment]
Well, I tried again this and the error hasn't occurred. The problem looks like solved. I have troubled you, thanks.

**Comment by segfaultdoc** [comment]
> Well, I tried again this and the error hasn't occurred. The problem looks like solved. I have troubled you, thanks.

What was the solution?

**Comment by armaniferrante** [comment]
> > Well, I tried again this and the error hasn't occurred. The problem looks like solved. I have troubled you, thanks.
> 
> What was the solution?

Addressed by https://github.com/project-serum/anchor/pull/711.
