### ISSUE TITLE
Using repr(C) instead of repr(packed) for zero_copy?

### ISSUE THREAD

**Issue by dovahcrow** [project-serum/anchor#813]
As mentioned in this issue https://github.com/rust-lang/rust/issues/82523, creating references to packed fields will be an error in the future.

**Comment by y2kappa** [comment]
will this make some accounts larger? even so, I think it's much better than deploying something to production and later not be able to compile when it becomes an error

**Comment by dovahcrow** [comment]
> will this make some accounts larger? even so, I think it's much better than deploying something to production and later not be able to compile when it becomes an error

I think so if the fields are not properly arranged previously.
