### ISSUE TITLE
Tutorial Document Issues

### ISSUE THREAD

**Issue by rabinhod** [project-serum/anchor#826]
==> Tutorial-0 Problems : 

  1- In Generating a Client section when i run "node client.js" i get this error 
  
       internal/modules/cjs/loader.js:892
       throw err;
       ^
  
       Error: Cannot find module '@project-serum/anchor'
  
  > solution : npm install @project-serum/anchor
  
  
  2- after install anchor package when i run "node client.js" i get this error

      internal/fs/utils.js:634
          throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
          ^
      
      TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

> solution : ANCHOR_WALLET=/home/ADev/.config/solana/id.json node ./client.js

==> Tutorial-1 Problem : 

i create a client.js file for Tutorial-1 and run these command :
1- > anchor build
2- > anchor deploy
3- then copy program Id and use in my client.js
4- ANCHOR_WALLET=/home/ADev/.config/solana/id.json node ./client.js

but i get this error :

        Running client.
        Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa7 
            Program DD8NzMbBpHb8ySDaZqPpPzxLUp12b74axEnxoDzrvYVz invoke [1]
            Program 11111111111111111111111111111111 invoke [2]
            Program 11111111111111111111111111111111 success
            Program log: Custom program error: 0xa7
            Program DD8NzMbBpHb8ySDaZqPpPzxLUp12b74axEnxoDzrvYVz consumed 9003 of 200000 compute units
            Program DD8NzMbBpHb8ySDaZqPpPzxLUp12b74axEnxoDzrvYVz failed: custom program error: 0xa7

client.js

      const anchor = require('@project-serum/anchor');
      const { SystemProgram } = anchor.web3;
      
      
      const provider = anchor.Provider.local();
      anchor.setProvider(provider);
      
      async function main() {
      
        const idl = JSON.parse(require('fs').readFileSync('./target/idl/basic_1.json', 'utf8'));
      
        const programId = new anchor.web3.PublicKey('DD8NzMbBpHb8ySDaZqPpPzxLUp12b74axEnxoDzrvYVz');
      
        const program = new anchor.Program(idl, programId);
      
        const myAccount = anchor.web3.Keypair.generate();
      
        await program.rpc.initialize(new anchor.BN(1234), {
          accounts: {
            myAccount: myAccount.publicKey,
            user: provider.wallet.publicKey,
            systemProgram: SystemProgram.programId,
          },
          signers: [myAccount],
        });
      
      
      }
      
      console.log('Running client.');
      main().then(() => console.log('Success'));

**Comment by joaoh82** [comment]
This is a bug in the tutorial (will make a PR if no one fixes it sooner), the client.js file expects you to have a `ANCHOR_WALLET` env var (further on you'll run things with e.g. anchor test, which sets it for you). Try doing `ANCHOR_WALLET=~/.config/solana/id.json node client.js`for now.

**Comment by rabinhod** [comment]
> This is a bug in the tutorial (will make a PR if no one fixes it sooner), the client.js file expects you to have a `ANCHOR_WALLET` env var (further on you'll run things with e.g. anchor test, which sets it for you). Try doing `ANCHOR_WALLET=~/.config/solana/id.json node client.js`for now.

Yea, as i told it's work with this command but what about Tutorial-1 problem ? i run my client.js but i get that error
