### ISSUE TITLE
Where we can chat and talk about problems ?

### ISSUE THREAD

**Issue by rabinhod** [project-serum/anchor#827]
Hi
I spend more than 4 days and i stuck in Tutorial-1 and i can not resolve it !!
where we can talk ? Discord channel it's seems not working !  i can not open Discord channel

**Comment by armaniferrante** [comment]
What's your username in Discord? Can you ping me in the "Verify" channel if you are stuck there.

**Comment by rabinhod** [comment]
username : aDev#7068
Thanks


This is exactly what i have access, Nothing

![Screenshot_2021-10-03_22-32-26](https://user-images.githubusercontent.com/49122842/135767875-2bb9cc74-84b9-408e-9d67-70495ff3d52c.png)

**Comment by armaniferrante** [comment]
Weird. Can you try this new link https://discord.gg/ETqDyfXr

**Comment by rabinhod** [comment]
> Weird. Can you try this new link https://discord.gg/ETqDyfXr

It's works

**Comment by armaniferrante** [comment]
Closing. Let's continue any questions in Discord.
