### ISSUE TITLE
Provide ability to skip account initialization if it's already been created

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#852]
Currently the `#[account(init)]` keyword will always initalize an account via CPI to the system program. This means that if the account has already been created, then the instruction will fail. This is undesireable in the event you have two different users in two different apps performing the same action on the same new account, in which case they will both try to initialize and one will fail. Instead, it would be nice if both of them succeeded, and the second user simply didn't try to initialize.

One way of doing this would be to introduce a new `#[account(init_if_needed)]` keyword that simply skipped the initialization logic if the account already exists.

**Comment by armaniferrante** [comment]
Using this as the default behavior is dangerous, e.g., the program might explicitly zero state or set to some starting value that shouldn't be set if it's already been initialized.

**Comment by perlish** [comment]
its helpful but how to create more than one account with program ?

**Comment by armaniferrante** [comment]
> its helpful but how to create more than one account with program ?

This would check the data has been allocated and initialized. If it has not, i.e., zero length data and owned by the system program, then the new account would be initialized. This would support more than one account.

**Comment by perlish** [comment]
> > its helpful but how to create more than one account with program ?
> 
> This would check the data has been allocated and initialized. If it has not, i.e., zero length data and owned by the system program, then the new account would be initialized. This would support more than one account.

so how to avoid  'already in use' Error

**Comment by acamill** [comment]
I vote for this
