### ISSUE TITLE
Add Anchor.toml setting to specify the output directory of all typescript types in `target/types/`

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#855]
This will speed up UI development

**Comment by leonardgee** [comment]
Do you want to make it as a CLI argument also? 

I tried setting the `idl` field in the `Anchor.toml` however it seems like it doesn't produce the IDL to the expected path. 

But setting it explicitly using CLI does produce the output to the expected directory. Reading from the [code](https://github.com/project-serum/anchor/blob/8e52242b8ca838a44e135b48af758fa2b643176c/cli/src/lib.rs#L532), it seems like the CLI only reads the command line input when build?

Anchor.toml as followed:

```
[programs.localnet]
wrapper = { address="Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS", idl = "~/Projects/wrapper/new_idl" }

```

**Comment by armaniferrante** [comment]
We could add a new `types` to `[workspace]`, for example,

```toml
[workspace]
types = "target/types"
```

**Comment by FlorianMilcendeau** [comment]
I'm working on it 🙂

**Comment by fanatid** [comment]
Resolved with #1032

**Comment by lorisleiva** [comment]
Hi 👋 

Thanks for this awesome feature! I just wanted to point out that the current implementation will not include the `metadata` object containing the program ID.

Running `anchor build` generates a new IDL without a `metadata` object and running `anchor deploy` later on will update that IDL file to add the `metadata` object.

Whilst this is the case with the IDL file generated inside the `target` folder, it is not the case for the IDL copied in the custom directory.

I'd happily do a PR for this but my rust is very... rusty... 🥁

**Comment by FlorianMilcendeau** [comment]
hi @lorisleiva,

The IDL copied does not come `target/idl/<idl>.json` which contains the ID program but `target/types/<idl>.ts` I think it would be necessary to add the metadata in `target/types/<idl>.ts` file
