### ISSUE TITLE
Anchor Events Are Extremely Compute Intensive When Used Without Maximal Compiler Optimizations

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/anchor#863]
# Overview

With the default compiler optimizations, logging the same information through `emit!` is approximately 2x more expensive in compute units, than it is to directly use `msg!`.

When using maximal compiler optimizations as follows, the cost increase is drastically reduced, but is still more expensive.

```toml
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
```

While this can solve compute unit usage issues within your own programs, it still leaves programs at risk of reaching compute unit limits when making CPI to third-party programs that emit events, without these compiler optimizations.

As it stands this is more of an edge-case issue, however if the current event system is kept in place I think once more programs are deployed onto Solana, and there is more interconnectivity between programs, this will probably start to become a real issue. 

# Proposed Solution - Avoid Borsh Serialization And Base64  Encoding Completely

Personally speaking I think the best option is to remove serialization and encoding of events, and use proc macros to format the event into a JSON string which is what gets logged. This has the added bonus of being human readable on block explorers.

# Alternative Solutions

* update anchor docs to recommend using the aforementioned compiler optimizations when using anchor events
* when running `anchor init` add the aforementioned compiler optimizations to the default workspace file.  

## Optimize The Process Of Emitting Events

Not exactly sure what this would look like, but there's probably something that can be done. At a quick glance, changing [this function](https://github.com/project-serum/anchor/blob/81e03c5e379cd9a98e13ca8e2ef06b00043de7ab/lang/attribute/event/src/lib.rs#L34-L36) to preallocate the vector entirely would help, but im not sure if this is possible.

**Comment by armaniferrante** [comment]
Have you measured the difference in compute units between JSON vs base64(borsh)?

**Comment by fanatid** [comment]
@bonedaddy can you measure instructions count with this PR? https://github.com/project-serum/anchor/pull/870

**Comment by bonedaddy** [comment]
> @bonedaddy can you measure instructions count with this PR? #870

Yup, I'm actually about to sign off for the night so I'll do this in the morning.

**Comment by bonedaddy** [comment]
> Does compute cost actually increase linearly with the amount of text being printed? This isn't something I've heard of before.

I'm not sure to honest, just used that as a guesstimate. However even if it doesn't scale linearly and its only a 25% increase, a 15% increase, or just a 10% increase, the compute units consumed from events becomes problematic  the more complex your program gets. Even without complex programs, emitting one too many events is enough to cause problems (ie: the harvest + redemption example i mentioned previously).

> No ones arguing against you on these points, just trying to accurately gauge what the problem actually looks like in order to have a strong starting point for figuring out potential solutions. Events and good logging are super important for the whole ecosystem!

Events are very important indeed, but the compute units currently consumed by events will not scale to more complex protocols that involve interacting with many other protocols. It's entirely possible to work around this now, but once transaction wide compute limits are implemented, it will be a blocker.

**Comment by fanatid** [comment]
@bonedaddy not sure why version with `Vec<u8>` does not work :thinking: Reverted, can you try one more time?

**Comment by bonedaddy** [comment]
Unfortunately that made compute units consumption worse :sob: 

Compiling with optimizations:

```
  Log Messages:
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS invoke [1]
    Program log: pev3G58vvc4GAAAAZm9vYmFyewAAAAAAAAADAAAAYmF6AwAAAGJhcgEBAAAAYQEAAABi
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS consumed 7952 of 200000 compute units
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS success
Transaction executed in slot 2:
  Signature: 63CfsfVJqWqnQCcuNK1DnnYDH3exLWYxja3zqy9VFrCTUr9upft8PLod6jmMnBq1PEj3amAsPcSh46dt9UxdQWXo
  Status: Ok
  Log Messages:
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS invoke [1]
    Program log: {"message": "foobar", "number": 123, "such": "baz", "compute_units": "bar", "very_wow": "true", "a": "a", "b": "b"}
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS consumed 1976 of 200000 compute units
    Program Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS success
```

**Comment by fanatid** [comment]
Interesting. Thanks that checked!

**Comment by armaniferrante** [comment]
A new syscall API was added recently, which hopefully addresses some of these concerns. See https://github.com/solana-labs/solana/pull/19764.

**Comment by bonedaddy** [comment]
Interesting, that looks very promising.

**Comment by armaniferrante** [comment]
What mango is doing to make this more efficient for memory usage: https://github.com/blockworks-foundation/mango-v3/pull/134/files

**Comment by paul-schaaf** [comment]
@bonedaddy would you mind benchmarking again with the master branch? master now uses the `sol_log_data` syscall

**Comment by paul-schaaf** [comment]
Did some benchmarks for anchor `0.24.2`:

repo: https://github.com/paul-schaaf/emit-bench (master has the custom profile, `without-profile` branch does not)
results: https://gist.github.com/paul-schaaf/4742a7c474c38807918b2f7e6466b796

summary:
- logging pubkeys in `msg!` is more expensive with or without a custom profile
- without a profile, the code is more efficient now that we have `sol_log_data` but it's still not as cheap as the code with the custom profile
- using the custom profile now even beats `msg!`

> however this doesn't really solve the issue because it means assuming everyone will deploy their anchor programs with these optimizations added.

we can add the custom profile to our cli templates so that every anchor project going forward uses it.
