### ISSUE TITLE
CpiLoader: zero-copy for CpiAccount

### ISSUE THREAD

**Issue by juliotpaez** [project-serum/anchor#871]
Hi!, I need to make CPI calls between zero-copy programs. Following the [zero-copy example](https://github.com/project-serum/anchor/blob/master/tests/zero-copy/programs/zero-cpi/src/lib.rs) I've ended with the following code:

```rust
#[derive(Accounts)]
pub struct ProgramAInstruction<'info> {
    #[account(mut)]
    pub program_a_account: Loader<'info, A>,

    #[account(mut)]
    pub program_b_account: Loader<'info, B>,
}
```

But I get `The given account is not owned by the executing program` when I try to execute it. I've concluded that is because `Loader` checks ownership with the current program.

My question is, how can I have something similar to `Loader` but for CPI, let say a `CpiLoader`?

Thanks in advance

**Comment by rmcwhorter** [comment]
Hey, did you ever solve this? I've got basically the same issue.

**Comment by armaniferrante** [comment]
Yes. `AccountLoader` can be used.
