### ISSUE TITLE
about #699 IDO pool Exchanges user Redeemable tokens for watermelon problem

### ISSUE THREAD

**Issue by yasuoyuhao** [project-serum/anchor#897]
Hello, 

I am using this version of [ido-pool](https://github.com/project-serum/anchor/pull/699) for testing(The PR has been merged to master).

It works well, but when I `Exchanges user Redeemable tokens for watermelon`, I keep appearing `A seeds constraint was violated`.

How can I solve it?

I executed `tests/ido-pool.js` directly, and added try catch on line `453` to get an error:

```
Exchanges second user's Redeemable tokens for watermelon:
Error: 146: A seeds constraint was violated

code: 146,
msg: 'A seeds constraint was violated'
```

```js
try {
      await program.rpc.exchangeRedeemableForWatermelon(firstUserRedeemable, {
        accounts: {
          payer: provider.wallet.publicKey,
          userAuthority: provider.wallet.publicKey
,
          userWatermelon,
          userRedeemable,
          idoAccount,
          watermelonMint,
          redeemableMint,
          poolWatermelon,
          tokenProgram: TOKEN_PROGRAM_ID,
        },
      });
    } catch (e) {
      console.error(e);
    }
```

![CleanShot 2021-10-19 at 23 09 54@2x](https://user-images.githubusercontent.com/17445398/137939493-3b6453e5-9129-46cb-af36-5e5c54f1323e.png)

**Comment by yasuoyuhao** [comment]
> The tests passed in the CI so you must have changed something in one of the seeds

Thanks, But where should I go to change it?

**Comment by Henry-E** [comment]
yes,  for anyone else who runs into a similar issue, the working 50% of the time thing is a good indication the bump is wrong.

**Comment by yasuoyuhao** [comment]
#902 Fit it, thanks all.
