### ISSUE TITLE
 "The given account is not owned by the executing program" by running basic-1

### ISSUE THREAD

**Issue by xiaoyu1998** [project-serum/anchor#943]
Running client.
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa7 
    Program 71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8 invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0xa7
    Program 71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8 consumed 8863 of 200000 compute units
    Program 71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8 failed: custom program error: 0xa7
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa7
    at Connection.sendEncodedTransaction (/home/xiaoyu/work/anchor/examples/tutorial/basic-1/node_modules/@solana/web3.js/lib/index.cjs.js:6591:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/home/xiaoyu/work/anchor/examples/tutorial/basic-1/node_modules/@solana/web3.js/lib/index.cjs.js:6550:20)
    at async sendAndConfirmRawTransaction (/home/xiaoyu/work/anchor/examples/tutorial/basic-1/node_modules/@solana/web3.js/lib/index.cjs.js:8513:21)
    at async Provider.send (/home/xiaoyu/work/anchor/examples/tutorial/basic-1/node_modules/@project-serum/anchor/dist/cjs/provider.js:87:22)
    at async Object.rpc [as initialize] (/home/xiaoyu/work/anchor/examples/tutorial/basic-1/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31)
    at async main (/home/xiaoyu/work/anchor/examples/tutorial/basic-1/client.js:33:3) {
  logs: [
    'Program 71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8 invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0xa7',
    'Program 71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8 consumed 8863 of 200000 compute units',
    'Program 71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8 failed: custom program error: 0xa7'
  ]
}

client.js
`// client.js is used to introduce the reader to generating clients from IDLs.
// It is not expected users directly test with this example. For a more
// ergonomic example, see `tests/basic-0.js` in this workspace.

const anchor = require('@project-serum/anchor');

// Configure the local cluster.
anchor.setProvider(anchor.Provider.local());

async function main() {
  // #region main
  // Read the generated IDL.
  const idl = JSON.parse(require('fs').readFileSync('./target/idl/basic_1.json', 'utf8'));

  // Address of the deployed program.
  const programId = new anchor.web3.PublicKey('71gLMSUmebNALswNydGAcffoRvJrbSjGF1bfzUp8EKR8');

  // Generate the program client from IDL.
  const program = new anchor.Program(idl, programId);

  // The Account to create.
  const myAccount = anchor.web3.Keypair.generate();

  // Create the new account and initialize it with the program.
  await program.rpc.initialize(new anchor.BN(1234), {
    accounts: {
      myAccount: myAccount.publicKey,
      user: anchor.getProvider().wallet.payer.publicKey,
      systemProgram: anchor.web3.SystemProgram.programId,
    },
    signers: [myAccount],
  });

}

console.log('Running client.');
main().then(() => console.log('Success'));`

**Comment by pindaroso** [comment]
Make sure you update the `declare_id!("<Pk>");` line as well as the line in `Anchor.toml` with the public key from the deployment.

**Comment by xiaoyu1998** [comment]
thx
