### ISSUE TITLE
Issues w/ anchor test

### ISSUE THREAD

**Issue by farzaa** [project-serum/anchor#945]
Hey there! On `anchor-cli 0.18.0`.

Trying to run `anchor test` but when I do so, I get hit with:

`Failed to run test: ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts: No such file or directory (os error 2)`.

So, I then did `npm install ts-mocha -g` to see if that would change anything. 

Running the test again, I get 

`node: --dns-result-order= is not allowed in NODE_OPTIONS`.

Just running a boilerplate hello-world project from the docs via `anchor init helloworld`.

I also tried doing `anchor init helloworld --javascript`, then do `anchor test`, and still get: `node: --dns-result-order= is not allowed in NODE_OPTIONS`.

**Comment by itsbek** [comment]
hey there! 
I followed [these](https://project-serum.github.io/anchor/getting-started/installation.html#install-anchor) instructions step by step  but `cargo build` failed and tried the possible solutions listed above but it still keeps failing

My PC is running on Ubuntu 20.04 and the following message was asked to include: 

`$HOST = x86_64-unknown-linux-gnu`
`$TARGET = x86_64-unknown-linux-gnu`
`openssl-sys = 0.9.66`

**Comment by AllanAi** [comment]
`npm install -g ts-mocha typescript` works for me. #942

**Comment by fanatid** [comment]
`--dns-result-order` is fixed in https://github.com/project-serum/anchor/pull/928

**Comment by Eliascm17** [comment]
Got this same kind of error and running `npm i -g mocha` fixed it for me.

**Comment by katopz** [comment]
modify `Anchor.toml` to use `npx` fixed it for me
```toml
[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
```

**Comment by pano-skylakis** [comment]
> modify `Anchor.toml` to use `npx` fixed it for me
> 
> ```toml
> [scripts]
> test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
> ```

Using yarn works as well :)

``` toml
[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
```

**Comment by ali-ahari-hashemi** [comment]
> anchor init aproject --javascript

This fixed it for me

**Comment by ali-ahari-hashemi** [comment]
> ```
> cargo install --git https://github.com/project-serum/anchor anchor-cli --locked
> anchor init aproject --javascript
> cd aproject
> anchor test
> ```

This fixed it for me

**Comment by YuheiNakasaka** [comment]
In case of using `--javascript` option, I modified `Anchor.toml` like this and it worked.

```
[scripts]
test = "node_modules/mocha/bin/mocha -t 1000000 tests/"
```

**Comment by fanatid** [comment]
@YuheiNakasaka please read about `npx`. https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

**Comment by baijifeilong** [comment]
> `npm install -g ts-mocha typescript` works for me. #942

`npm install -g ts-mocha typescript mocha`

**Comment by dataXBT** [comment]
> > `npm install -g ts-mocha typescript` works for me. #942
> 
> `npm install -g ts-mocha typescript mocha`

worked for me after previously having faulty connection issues with node as well

**Comment by yilmazbingo** [comment]
Here is the solution:

https://stackoverflow.com/questions/71818375/anchor-test-error-failed-to-run-test-yarn-run-ts-mocha-p-tsconfig-json-t/71818707#71818707

**Comment by richiehydra** [comment]
Even after using Anchor docs command for installing anchor  i havent got the solution
please rectify:
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.25.0 (https://github.com/project-serum/anchor#fd467df9)`, intermediate artifacts can be found at `/tmp/cargo-installOeao69`
