### ISSUE TITLE
Trying to verify install of anchor is  'Expected "anchor-cli 0.18.2"'

### ISSUE THREAD

**Issue by AlanSwenson** [project-serum/anchor#972]
```
$ anchor --version
Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Globally installed anchor version is not correct. Expected "anchor-cli 0.18.2", found "anchor-cli 0.18.0".
```
OS: Mac m1

What have I done wrong to make my system expect a version that does not yet exist?

**Comment by AlanSwenson** [comment]
restarting my computer seems to have resolved it, if anyone else encounters this weirdness

**Comment by fanatid** [comment]
https://www.npmjs.com/package/@project-serum/anchor-cli is working only on Linux x86_64. I added fields that will block npm package installation on unsupported platforms: https://github.com/project-serum/anchor/pull/976

**Comment by moza88** [comment]
Experiencing the same thing, I don't even think there's a 0.18.2 version.

**Comment by tkoriginal** [comment]
Same issue and I'm on an Intel Mac. It was working until recently.

**Comment by moza88** [comment]
@tkoriginal I asked around on StackOverflow and figured out how to do a Mac Install. With Macs you need to build the project from github using cargo instead of just downloading the dependencies. Below is a link to the StackOverflow question:

[https://stackoverflow.com/questions/69875462/installing-anchor-on-a-macos-anchor-versions-are-not-matching-up](https://stackoverflow.com/questions/69875462/installing-anchor-on-a-macos-anchor-versions-are-not-matching-up 
)

**Comment by aviral17** [comment]
How to Install anchor/cli in Windows ??? After installing and after checking/running ``` anchor --version ```, it shows -------->>

Only x86_64 / Linux distributed in NPM package right now.
Trying globally installed anchor.
Could not find globally installed anchor, install with cargo.

Please help me

**Comment by moza88** [comment]
@aviral17 Unfortunately, I don't have a windows machine to figure this out. I am not sure why it doesn't run on Windows, we should make it compatible with Windows.

One alternative for you is to use a docker image of solana. I am not sure why it doesn't run on Windows, we should make it compatible with Windows.

Here is the docker image:
https://hub.docker.com/r/solanalabs/solana

Here is a detailed article on developing against the Solana docker image. 
https://medium.com/rahasak/deploy-solana-test-network-with-docker-418622c4f566

**Comment by aviral17** [comment]
@moza88 Much Thanks for the help , BTW, I've also tried with WSL (Windows Subsystem for Linux) but still, its not working, But I am Sure, it will work with Docker,   And I've also gone through its Contributer's github page, where they are saying that its in Development phase, but I am sure it will be solved someday!! Further Progress --> Will update soon

**Comment by Abhi-bot-dot** [comment]
> restarting my computer seems to have resolved it, if anyone else encounters this weirdness

Definitely not working for me. Restarted the system, reinstalled everything from npm to yarn, nothing happened, still facing the same error.

**Comment by aviral17** [comment]
Thanks for the help !
Actually I found the solution Just after sending this email. It worked with
``` cargo install --git https............... --locked ``` command. Thats it
and the Job is Done !!
