### ISSUE TITLE
error: not a directory: '/root/.local/share/solana/install/releases/1.8.2/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'

### ISSUE THREAD

**Issue by gurucrypto23** [project-serum/anchor#981]
OS: Ubuntu 20.04 on VMWare in windows 10

I did run "anchor build" on example base-0 program.
And faced that error.

![image](https://user-images.githubusercontent.com/74819805/140614207-4b7aa47b-e780-49a9-8e83-5cb8a8a99234.png)

Let me know how to fix that error.

**Comment by fanatid** [comment]
This is not `anchor` issue, you have a problems with solana tools.

1. Try to remove solana tools completely. Including directories: `~/.cache/solana`, `~/.config/solana`, `~/.local/share/solana`.
2. Do not install tools from root.
3. Try the previous version of the tools (1.8.1).

If problem will not be solved please ask question in discord.

**Comment by ez-krk** [comment]
> This is not `anchor` issue, you have a problems with solana tools.
> 
>     1. Try to remove solana tools completely. Including directories: `~/.cache/solana`, `~/.config/solana`, `~/.local/share/solana`.
> 
>     2. Do not install tools from root.
> 
>     3. Try the previous version of the tools (1.8.1).
> 
> 
> If problem will not be solved please ask question in discord.

works, but no need to delete the whole `~/.local/share` but just `~/.local/share/solana`
