### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by carlomigueldy** [project-serum/anchor#983]
![image](https://user-images.githubusercontent.com/45052332/140639112-6721b0ef-4c4c-42cc-8d88-960e4834f8b6.png)

**Comment by carlomigueldy** [comment]
```bash
carlomigueldy@DESKTOP-Q42TFOP:~/buildspace/nextjs-solana-starter$ node --version
v14.18.1
carlomigueldy@DESKTOP-Q42TFOP:~/buildspace/nextjs-solana-starter$ npm --version
8.0.0
```

**Comment by carlomigueldy** [comment]
Related issue https://github.com/project-serum/anchor/issues/728#issuecomment-938539077

**Comment by carlomigueldy** [comment]
I am on a Next.js project and got it fixed by adding the webpack config on `next.config.js`
```js
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  webpack: (config) => {
    config.resolve.fallback = { fs: false, path: false };
    return config;
  },
};
```

**Comment by mwilc0x** [comment]
> I am on a Next.js project and got it fixed by adding the webpack config on `next.config.js`
> 
> ```js
> /** @type {import('next').NextConfig} */
> module.exports = {
>   reactStrictMode: true,
>   webpack: (config) => {
>     config.resolve.fallback = { fs: false, path: false };
>     return config;
>   },
> };
> ```

clutch solution, thank you!
