### ISSUE TITLE
Failed to install anchor-cli with cargo install --locked

### ISSUE THREAD

**Issue by jimcal** [project-serum/anchor#987]
TL;DR: Tried to run `cargo install --git https://github.com/project-serum/anchor --tag v0.18.0 anchor-cli --locked`, but result in error related to the dependencies.

Context: Try to install anchor, but running into errors on dependencies (see below.) I suspect the dependency version is mismatching, however, as a Rust n00b, I don't know how to solve the problem. Should I be attempting changing what's in Cargo.toml or even Cargo.lock? 

With --lock or without, you can see for my local dev environment, the dependencies are what is missing. I am on MacOS 12.01 (Not M1) 

```
➜  ~ cargo install --git https://github.com/project-serum/anchor anchor-cli --locked
    Updating git repository `https://github.com/project-serum/anchor`
  Installing anchor-cli v0.18.0 (https://github.com/project-serum/anchor#54f24e55)
    Updating crates.io index
error: failed to select a version for the requirement `anyhow = "=1.0.43"`
candidate versions found which didn't match: 1.0.41, 1.0.40, 1.0.39, ...
location searched: crates.io index
required by package `anchor-cli v0.18.0 (/Users/[$USER]/.cargo/git/checkouts/anchor-bf03d42499b9267c/54f24e5/cli)`
➜  ~ cargo install --git https://github.com/project-serum/anchor anchor-cli    
    Updating git repository `https://github.com/project-serum/anchor`
  Installing anchor-cli v0.18.0 (https://github.com/project-serum/anchor#54f24e55)
    Updating crates.io index
    Updating git repository `https://github.com/project-serum/serum-dex`
error: failed to compile `anchor-cli v0.18.0 (https://github.com/project-serum/anchor#54f24e55)`, intermediate artifacts can be found at `/var/folders/z1/m6lwplyx66nfqj8159j9m1j40000gn/T/cargo-install0oBnIe`

Caused by:
  failed to select a version for the requirement `reqwest = "^0.11.4"`
  candidate versions found which didn't match: 0.11.3, 0.11.2, 0.11.1, ...
  location searched: crates.io index
  required by package `anchor-cli v0.18.0 (/Users/[$USER]/.cargo/git/checkouts/anchor-bf03d42499b9267c/54f24e5/cli)`

```

**Comment by jimcal** [comment]
FWIW, I am aware of https://github.com/project-serum/anchor/issues/984. In fact, I tried that with no avail before I open this current issue. Any information you'd like to see me provide, I'd be happy to.

**Comment by fanatid** [comment]
The provided log is missing `--tag v0.18.0`. (54f24e55 is master, not tag v0.18.0)

Try to clone the repository and compile `anchor-cli` binary. I'll close the issue on github, please ask installation questions in discord.

**Comment by jimcal** [comment]
@fanatid , thanks! Was trying to get !verify at Discord since Sunday.
