### ISSUE TITLE
Make timeout error message more visible in `anchor test`

### ISSUE THREAD

**Issue by Faris999** [project-serum/anchor#989]
I've been struggling with this problem with `anchor test` before on a boilerplate project from `anchor init --javascript`.  

```Unable to start test validator. Check .anchor/test-ledger/test-ledger-log.txt for errors.```

It turns out that it was a timeout issue. I fixed it by adding this snippet to `Anchor.toml`

```
[test]
startup_wait = 100000
```

I couldn't have figured it out myself if it weren't from other people. I suggest to make the error message about the timeout more apparent. Thanks 😁

**Comment by fanatid** [comment]
Can you propose an error message which should be shown?

**Comment by PaulEbose** [comment]
You can:
- "Unable to start test validator. Check {} for errors. Consider increasing test.startup_wait in Anchor.toml."
- Comment it out in the default template.
